### ISSUE TITLE
Policies

### ISSUE THREAD

**Issue by Thalassicus** [Thalassicus/cep-bnw#1]
https://drive.google.com/file/d/0B58Ehya83q19aTJkc05PMmFaMEU/edit?usp=sharing

I finished the early plans today (linked above). I need help completing the edits to match the plan. If you decide to edit a policy tree, please post which tree(s) you plan to work on so we don't duplicate our efforts. Use the "policies" branch of the github repository while working on this task.

Before:
- [x] Plan policy updates
- [x] Remove policy links

Update:
- [x] Tradition (stackpointer)
- [x] Liberty (AlyDash)
- [x] Honor (kcinlober)
- [x] Piety (AlyDash)
- [x] Patronage (Thalassicus)
- [x] Aesthetics (AlyDash)
- [x] Wealth (Thalassicus)
- [x] Exploration (Thalassicus)
- [x] Knowledge (AlyDash)

For each policy we need to check:
- Grid position
- Policy names
- Policy data
- Policies tab of the "CEP_Language" and "Good For flavors" tables, in the Communitas folder of google drive:
  https://drive.google.com/folderview?id=0B58Ehya83q19eVlvWXdmLXZ6UUE

**Comment by Thalassicus** [comment]
I plan to work on the Exploration tree.

**Comment by stackpoint** [comment]
I'm on my mobile device so I can't test on my desktop but odg is an open office format? There are multiple open office programs? Which one do you recommend?

**Comment by Thalassicus** [comment]
This is an "open document drawing" file, which I open with LibreOffice Draw.

**Comment by Thalassicus** [comment]
I created placeholder files for each policy tree in the "/Policies/Trees" folder to use for edits. These files also include disabled code from before BNW for reference.

**Comment by stackpoint** [comment]
I'll start with tradition.

EDIT: The document looks like a powerpoint. I'm not sure why google docs can't preview the file, especially since it must be an open standard.

EDIT2: I hope you don't mind me editing your post to include assignments to be clear.

**Comment by Thalassicus** [comment]
That's a good idea, thank you.

**Comment by Thalassicus** [comment]
Later down in the "diagrams" document plans you can also see some old plans for the policies. It includes possible names for each policy, which could be helpful if you're unsure what to call a policy.

**Comment by GrantSP** [comment]
I will give a shot at Honor

**Comment by stackpoint** [comment]
I wrote some code to make dummy branches for wonder unlocks (since wonders only take PolicyBranchType) here: https://github.com/Thalassicus/cep-bnw/commit/031431c70dc0539e6fab45be8f98b6cc132314b0#diff-46ba56e9b5f25ce8962ec29f988022f9

However, this code is pretty rough ~~but for example, if I wanted the Oracle to unlock at legalism, all you need to do to hook into this is to define a new PolicyBranchType:~~

~~I plan to make my code more modular so if you can follow the naming scheme POLICY_BRANCH_X for unlocks at POLICY_X then it should work out.~~

UPDATE: See https://github.com/Thalassicus/cep-bnw/issues/1#issuecomment-28760062

**Comment by Thalassicus** [comment]
Here's the language file:
https://docs.google.com/spreadsheet/ccc?key=0Ap8Ehya83q19dHhmOUdwN0VCT1Nma2ZjY3k1bGhNZXc&usp=sharing

**Comment by stackpoint** [comment]
With this commit: https://github.com/Thalassicus/cep-bnw/commit/b65d3865b28980da24ee21b7c09381c51cea05b0 the wonder policy unlocks should be complete. All you need to do to correctly assign it is shown below.

For example, if I wanted the Oracle to unlock at Legalism, define a new PolicyBranchType with the name of the Policy you want it to unlock at:

``` xml
    <PolicyBranchTypes>
        <Row>
            <Type>POLICY_LEGALISM</Type>
            <Description>TXT_KEY_POLICY_LEGALISM</Description>
            <Help>TXT_KEY_POLICY_LEGALISM_HELP</Help>
            <Title>TXT_KEY_TRADITION_TITLE</Title>
        </Row>
    </PolicyBranchTypes>
```

And then tie the building into that policy branch type:

``` xml
    <Buildings>
        <Update>
            <Where Type="BUILDING_ORACLE" />
            <Set PolicyBranchType="POLICY_LEGALISM"
                 />
        </Update>
    </Buildings>
```

**Comment by stackpoint** [comment]
I just recalled that I have not updated the flavor values for the tradition branch and I am not familiar with flavors enough to do so.

**Comment by Thalassicus** [comment]
I decided to match policy tooltip style to the format of other tooltips. Following the same pattern for policies will improve consistency across the game, and make it easier to see policy effects at a glance.

[ICON_CULTURE] Culture: +1

I lead tooltips with icons because the human mind identifies visuals more quickly than language. The icon lets us instantly see the line gives culture. The next part shows the bonus in words, and the final part shows the specific amount of culture. If we don't need or want culture, the quantity doesn't really matter, so the number is the least important detail. This orders tooltips from most to least important information.

**Comment by Thalassicus** [comment]
I uploaded the LeadersAI spreadsheet. Go to the "Policy Priorities" tab to set AI flavors. These are the same as the "good for" ratings shown to humans.

https://docs.google.com/spreadsheet/ccc?key=0Ap8Ehya83q19dFpPbnNDMFhmM2I2YjVXR04tQWN0V2c&usp=sharing#gid=8

Each policy needs at least one "high priority" flavor. Use this scale:

8 : high priority
4 : average
2 : low priority

Use your best judgement to figure out what policies are good for. If a policy gives culture, it should have a flavor_culture priority.

**Comment by AlyDash** [comment]
Knowledge tree is finished.
( • _ •)
( • _ •)>⌐□-□
(⌐□_□)

**Comment by GrantSP** [comment]
Apologies but I wont be able to do the Honor policy in time.
Massive electrical storm has fried my system.
Had to post this from my phone.  Could be days before I get it back.

**Comment by kcinlober** [comment]
I can take a stab at the Honor policy tree. I am new to this, so I may have several questions along the way

**Comment by Thalassicus** [comment]
That sounds wonderful! The basic steps are:
1. Get the project (see the [collaboration guide](https://github.com/Thalassicus/cep-bnw/wiki/Collaboration-Guide)).
2. Figure out how Firaxis did policy effects (see the [finding data guide](http://forums.civfanatics.com/showthread.php?t=475076)).
3. Update the effects to match the plans.
4. Update the [text descriptions](https://docs.google.com/spreadsheet/ccc?key=0Ap8Ehya83q19dHhmOUdwN0VCT1Nma2ZjY3k1bGhNZXc&usp=drive_web#gid=10).
5. Upload changes with the github app.

**Comment by kcinlober** [comment]
Cool, I followed the collaboration guide and got all set up with the github app. I am part of the way through editing the cep_honor.xml at the moment. I have been flipping back and forth between that, the Firaxis CIV5Policies.xml and the CEP_tradition.xml updates to figure out how to change things. So far so good, except I am not 100% sure how to make it so that the opener for Honor doesn't unlock the statue of zeus building (I followed stackpointer's directions  and I think I have it set to that the proper policy unlocks it). Am i correct in thinking that this would work?

```
 <Update>
        <Where Type="BUILDING_STATUE_ZEUS" />
        <Set PolicyBranchType="NULL"
         />
</Update>
```

**Comment by kcinlober** [comment]
I do have skype, btw: nrebol

**Comment by Thalassicus** [comment]
Yes, that should remove the policy requirement. I added you to my skype contact list and the group channel.

**Comment by Thalassicus** [comment]
Please skip the process of linking policies to wonders for now. I'm rethinking where they should go. I also wrote code to automatically create the dummy policy branches we need:

```
INSERT INTO PolicyBranchTypes(Type, Description, EraPrereq, AIMutuallyExclusive)
SELECT Type, Description, 'ERA_FUTURE', 1 FROM Policies;
```

**Comment by Thalassicus** [comment]
I'm going to push back this update one week to consider which wonders to link to which policies, and give us more time to finish the policy trees.

**Comment by Thalassicus** [comment]
I'd like to release this tomorrow. Please sync any remaining changes with github, or email me your work at: thalassicus@hotmail.com

If you have unfinished stuff, just send what you've got, and I'll complete the rest. Thank you everyone for all your help! This wouldn't have been possible without you. :)

**Comment by Thalassicus** [comment]
Thank you everyone for all your hard work! I've got the final version ready, and plan to release this update tomorrow.
