### ISSUE TITLE
DLC Wonder Compatiblity

### ISSUE THREAD

**Issue by GrantSP** [Thalassicus/cep-bnw#10]
Formerly: BUILDING_MAUSOLEUM_HALICARNASSUS (+DLC Compatibility)

I have again found this error message appear in my logs:
MT_Initialize: ERROR  City_GetBuildingsOfFlavor: BUILDING_MAUSOLEUM_HALICARNASSUS does not exist in GameInfo.Buildings  (FlavorType=FLAVOR_GOLD)

The actual error is easy to figure out the problem I am facing is, is this building still in the game? I can see where it is defined in the core xml but all the saved debug databases from all the different versions of the game I have don't show it in the Buildings table. I can't see why it is not there.
I know our code makes use of it with 'Building_FreeUnits' and 'Building_ResourceYieldChanges', but why isn't it actually in the database?

I am I the only one with this error?

**Comment by stackpoint** [comment]
This is strange. BUILDING_MAUSOLEUM_HALICARNASSUS has an ID of 95 and looks normal to me in the Buildings table. Is your CEC_Wonders.xml file loading correctly?

**Comment by GrantSP** [comment]
The problem is worse than that. I don't have that building in a vanilla game! The building ID's go to 93 then jump to 113 and carry on from there.

I'll close this, it isn't our concern. I will look further a field to find the reason for it

**Comment by stackpoint** [comment]
This seems to be an issue that this mod has with players who don't own the "Wonders of the Ancient World" DLC. It might be looking into a way to make it compatible in that case.

**Comment by GrantSP** [comment]
On second thoughts this should stay open for those exact reasons.

Any changes we make that affect the gameplay/functionality of ALL players should be compatible with whatever DLC they have installed.
To rename a wonder is one thing, if you have that wonder in your DLC then it will show in the game, if you don't then you won't know and the game will go on.
To rename something to a name that is already used in the main game files is a mistake.

Now the issue I faced was strange for a couple of reasons.
- Although I didn't have the full DLC I had some of the XML files that defined the buildings (Firaxis error perhaps), so I assumed I must have everything and was amazed that the game was lacking what I thought a default building.
- The Statue of Zeus from the Wonders DLC also showed up as the Statue of Zeus in my games until I installed the Wonders DLC as a standalone, not bundled with the Korea DLC. It now is getting renamed to Parthenon which is now also a default building with different abilities.

So, we must be sure any changes made are only going to affect gameplay if the required files are on a user's system.
Any changes must NOT conflict with any other unit/building/etc. that may be on a user's system.

Question, does the new Hanse building constitute a conflict with our Hanseatic League?
In the mean time a reverting of name for the Statue of Zeus would be in order.

**Comment by stackpoint** [comment]
This actually shouldn't be too difficult an issue to tackle. You can do a check when modifying flavor or yields to check whether the wonder actually exists or not. I'm not sure how exactly to format it in xml/sql but I believe it possible.

The Statue of Zeus issue might stem from from the fact that it was added into the vanilla game by BNW for the honor opener. It might have a different building ID or text field than the DLC wonder.

**Comment by Thalassicus** [comment]
For reference, the "stable" branch of the project should not make any changes to wonders at this time. Those changes should only be in the "wonders" branch.

**Comment by Thalassicus** [comment]
I think I solved this with a line at the end of CEAI_Buildings.sql:

``` sql
DELETE FROM Building_Flavors WHERE BuildingType NOT IN (SELECT Type FROM Buildings);
```

**Comment by stackpoint** [comment]
It looks like the Temple of Artemis is also a DLC wonder so it should not be used as the honor opener.

**Comment by skodkim** [comment]
Great Wall seems to be the non-dlc early wonder that thematically seems to fit Honor then, doesn't it?

\Skodkim

**Comment by stackpoint** [comment]
The Great Wall is a very defensive wonder.

**Comment by skodkim** [comment]
Agreed, but looking at the tech tree it seems to be the only wonder that has some kind of military use.

\Skodkim

stackpointer notifications@github.com skrev:

> The Great Wall is a very defensive wonder.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Thalassicus/cep-bnw/issues/10#issuecomment-33197407

## 

Sendt fra min Android telefon med K-9 Mail. Undskyld hvis jeg er lidt kortfattet.

**Comment by GrantSP** [comment]
I have started a discussion about this on [Civfanatics](http://forums.civfanatics.com/showthread.php?t=522735).
Hopefully with some more input we might be able to finally end this DLC wonder issue.
