### ISSUE TITLE
Promotion: Amphibious

### ISSUE THREAD

**Issue by GrantSP** [Thalassicus/cep-bnw#100]
Is this promotion supposed to grant embarkation, even when it has not been researched?

The large number of barbarians I now encounter mean my units have reached this promotion way earlier than I normally expect so I'm not sure if it always did this. I usually had Optics long before they got this far.

If so, it also means a unit can gain Embarkation without having to return to home territory.

**Comment by Thalassicus** [comment]
Yes, this was an intended buff for the promotion. It's a fun early exploration bonus. I used to never get amphibious. I now promote at least 1 scout with amphibious when I start near islands.

The embarkation bonus can't be applied to settlers, and becomes useless/obsolete after we have Optics, which balance the effect's early value.

**Comment by GrantSP** [comment]
Thanks
