### ISSUE TITLE
Stable - Livestock flavor

### ISSUE THREAD

**Issue by Thalassicus** [Thalassicus/cep-bnw#101]
The stable is missing a "good for" rating for its resources. We need to create this flavor and assign it to the stable:

FLAVOR_RES_LIVESTOCK

/Cat/Tools/Cat_Misc.sql
/Cat/Tools/Cat_Data.xml

https://docs.google.com/spreadsheet/ccc?key=0Ap8Ehya83q19dGtjX2JldHBzdXhRbGNxVFgxT1E2OHc&usp=drive_web#gid=3
/Cat/Text/En_US/Flavors.sql

https://docs.google.com/spreadsheet/ccc?key=0Ap8Ehya83q19dFpPbnNDMFhmM2I2YjVXR04tQWN0V2c&usp=drive_web#gid=25
/Ceg/AI/Flavors/CEAI_Buildings.sql

**Comment by GrantSP** [comment]
I think I have gotten this done. You may want to check the Google Spreadsheets just to make sure I haven't corrupted the formulae.
