### ISSUE TITLE
Unable to load texture

### ISSUE THREAD

**Issue by fcukman** [Thalassicus/cep-bnw#102]
so I do not understand how no one else has this problem. I get the following error in loading screen which crashes the game:
Unable to load texture [civilopediaTopButtonsWorldCongress.dds]
I run the game from steam and have the G&K expansion. and of course I am only running the communitas mods. and have already tried deleting the cache and modUserData folders. I have also tried an older version (3.8) and the newest version posted and the problem exists in both versions.

**Comment by GrantSP** [comment]
Is this the same issue (and user) as [this](http://communitas.wikia.com/wiki/Forum:Texture_Load_Error?t=20130920074442).

You say you do not have the expansion BNW. This is the source of the error.
There are two files in the Firaxis core files that refer to this *.dds. both of which are ONLY in the 2nd expansion.

CAT, an integral part of the whole Communitas Project, modifies some files to add enhanced features. It is in this mod that the conflict is happening.
CivilopediaScreen.xml & CivilopediaScreen.lua are both using the BNW as a base for the modifications.

The only solution, for the time being, is to install BNW.
Thalassicus, the project lead, has mentioned that he _MIGHT_ be able to _ONE DAY_ make it backward compatible.

The Steam load screen should make this explicit when installing this mod. Perhaps there is a difference with the way these things are checked on Macs and PCs?
At any rate I am sorry but you will not be able to install and use the Communitas Project without BNW. I am unaware of any place you may find an older version of GEM that will work, as you say it was after Steam updated that you saw this problem, it is also after Steam updated its core files that the older mods (CivUP & GEM) were rendered broken by Firaxis' patches.

**Comment by stackpoint** [comment]
This mod must be run with BNW.
