### ISSUE TITLE
Brazilwood Camp lacks "Good For:" values

### ISSUE THREAD

**Issue by GrantSP** [Thalassicus/cep-bnw#103]

**Comment by stackpoint** [comment]
This means that the improvement is missing AI Flavor values.

**Comment by GrantSP** [comment]
Yeah I've started a few issues related to this one. I will begin to fix these things after I become more familiar with the rationale behind them.

**Comment by stackpoint** [comment]
Here is the relevant spreadsheet: https://docs.google.com/spreadsheet/ccc?key=0Ap8Ehya83q19dFpPbnNDMFhmM2I2YjVXR04tQWN0V2c&usp=drive_web#gid=7

It should probably be given flavor values similar to the Moai and Village (trading post).

**Comment by GrantSP** [comment]
I had another look at this. I've just updated the spreadsheet to include it and also the Chateau, I don't believe that had been included either.
Not had a chance to see the end result ingame just yet, if anyone wants to look over the values first.

**Comment by Thalassicus** [comment]
It looks right, I added the changes.
