### ISSUE TITLE
Ranged Blitz only -10 % combat strength

### ISSUE THREAD

**Issue by bernd-das-brot** [Thalassicus/cep-bnw#105]
In the combat screen ranged blitz is shown as -10% combat strength only. Describtion says it should be -25%.

**Comment by stackpoint** [comment]
I believe that the correct value is -10%. The text description should be synced up with the actual combat value. The combat value should be double checked also.

**Comment by bernd-das-brot** [comment]
From a balance point of view this should be at the very least -25%. Ranged Blitz ist totally overpowered

**Comment by stackpoint** [comment]
I can't remember the specific thread but this has been discussed extensively on the forums. You should make any concerns about the specific value in the forums. 

Here's an older thread regarding this: http://forums.civfanatics.com/showthread.php?p=12190567&highlight=90%25+75%25#post12190567 

However, I couldn't find the more recent, specific thread where Thal conceded the point. You may want to open a new thread instead.

**Comment by stackpoint** [comment]
This should be fixed in the next build.
