### ISSUE TITLE
Feed the World gives double boni

### ISSUE THREAD

**Issue by bernd-das-brot** [Thalassicus/cep-bnw#107]
(v. 3.12.1) follower belief: Feed the World gives its +3 food bonus two times! Every shrine and temple each produce +3 food from buildings AND +3 food from religion. So double the intended bonus.

**Comment by skodkim** [comment]
Just tested this and its only a text issue. You get only the +3 food/shrine (/temple) but the info in the city screen says +3 from Religion in the food yield section and the shrine also says +3 food. However you only get the intended +3 food from the Buildings.

Issue should be closed.

\Skodkim

**Comment by stackpoint** [comment]
Was there something confusing that we should've clarified? Or is this just a matter of user confusion?

**Comment by skodkim** [comment]
I don't really see how it could be clarified.

\Skodkim
