### ISSUE TITLE
Pottery Description Change

### ISSUE THREAD

**Issue by Hawawaa** [Thalassicus/cep-bnw#108]
Not in game right now but below good for it says Naval Bombardment. I don't think that fits. :P

**Comment by stackpoint** [comment]
AI flavors for the building needs to be double checked.

**Comment by GrantSP** [comment]
I have started another issue that discusses ALL the techs and the associated flavors.
In my latest game Pottery had NO AI flavors.

**Comment by stackpoint** [comment]
Are techs supposed to have no AI flavors?

**Comment by GrantSP** [comment]
Have a look at this other [issue](https://github.com/Thalassicus/cep-bnw/issues/117).
