### ISSUE TITLE
[3.12.1] Temple and Shrine faith bonuses not changed

### ISSUE THREAD

**Issue by skodkim** [Thalassicus/cep-bnw#109]
Hi

Release notes from 3.12.1 says "Reduced the Temple faith bonus from religious resources, and moved the bonus to Shrines" but it seems these were left out.

Have looked thorugh the commits and haven't been able to find anything related to this and as the screenshots below show they do not seem to be updated.

\Skodkim

![civ5screen0020](https://f.cloud.github.com/assets/6018459/1833058/a5f5202e-73c2-11e3-99e0-3179f027e0f8.jpg)
![civ5screen0019](https://f.cloud.github.com/assets/6018459/1833057/a5f52092-73c2-11e3-935e-0e4c395bed71.jpg)

**Comment by stackpoint** [comment]
Looks like this one hasn't actually been implemented yet. The next release should address it.

**Comment by skodkim** [comment]
3.12.2 does not adress this

\Skodkim

**Comment by skodkim** [comment]
This was fixed in 3.13
