### ISSUE TITLE
City liberation

### ISSUE THREAD

**Issue by GrantSP** [Thalassicus/cep-bnw#11]
With the change made to the city capture function, has the ability to "liberate" the cities been lost?

After a protracted battle between 3 civs I had the opportunity to take a city back but despite a tooltip saying what would result from liberating the city, no such option presented itself.

**Comment by stackpoint** [comment]
Here's an extensive report of the new city taking options: http://forums.civfanatics.com/showthread.php?p=12858023#post12858023

This also might be related: https://github.com/Thalassicus/cat/issues/3

**Comment by Thalassicus** [comment]
The intended behavior is described below. If it doesn't work this way, there's bugs in the code.

**Mercy**
Turns city into a puppet.

**Force**
Turns city into a puppet, and half the population instantly dies.

**Wrath**
Occupies the city. Half the population instantly dies, and one more dies per turn until the city disappears. Only available for non-capital cities.

The options above destroy all defense, happiness, and strategic-resource buildings in the city (and no others). Cities of size 2 or larger lose 1 population, which turns into a defensive unit who appears near the defender's capital. Resistance lasts for a number of turns equal to (p - 0.1p^1.5), where p is the population of the city before its capture. This equals city population for small cities, and tapers off to around half population for large cities.

Annexing a puppet turns it into an occupied city. This adds 1 unhappiness plus population/3. This raises the unhappiness of a size 9 city by 4 (1+9/3). Building a courthouse in a city turns it into a normal city, removing the unhappiness.

**Liberate**
This returns control to the original owner with no destruction or resistance. It's only available for cities defended by someone other than the original owner. This gives a diplomatic bonus, bigger if the liberated city was a capital. Resurrecting a player who was previously defeated also resets all former diplomacy modifiers before adding an even bigger diplomacy bonus.

**Comment by stackpoint** [comment]
Looks like the SetOccupied(false) was being used in the city taking function. This was allowing the occupation status of the city to change as SetOccupied has to be set to true in order for liberation to be possible.

I wasn't sure why SetOccupied has to be modified at all since the only reason for it to change would be if the city was retaken, liberated or gifted back to the city owner and the new city taking options shouldn't modify any of that. So I commented it all out.
