### ISSUE TITLE
[3.11.1] (Ducal) Stables require ressources EDIT: works, how do I delete?

### ISSUE THREAD

**Issue by mitsho** [Thalassicus/cep-bnw#111]
...but only 3 out of 5 (horse, cow, sheep). It should either also require deer or elephants or none of them. (I'd fix it myself as soon as I figure out this commit thingy here. .. :))

EDIT: No, sorry everything is okay, I was sleeping and just went by the red message of why I couldn't build the stables. IT is however "bad" that it shows all possible options of why I can't build it (in this case: missing sheep + missing horses + not enough gold to buy) instead of just the relevant one....

So how do I delete an issue? :) sorry for that.

**Comment by GrantSP** [comment]
Don't worry about deleting it, just **Close** it and it will soon fade from our collected memory.
