### ISSUE TITLE
CAT Civilpedia Error on Start Game

### ISSUE THREAD

**Issue by saulshanabrook** [Thalassicus/cep-bnw#112]
![screen shot 2014-01-02 at 7 58 53 pm](https://f.cloud.github.com/assets/1186124/1836902/f250a2a4-7412-11e3-9d9c-c6eb8bf39797.png)
![screen shot 2014-01-02 at 7 58 57 pm](https://f.cloud.github.com/assets/1186124/1836903/f2566cca-7412-11e3-8a67-2fec2cc77ec8.png)
![screen shot 2014-01-02 at 8 02 21 pm](https://f.cloud.github.com/assets/1186124/1836904/f25a336e-7412-11e3-9bfe-6501962703f8.png)

**Comment by GrantSP** [comment]
This looks very similar to this [issue](https://github.com/Thalassicus/cep-bnw/issues/102).
The screenshots look very 'Mac-esque', there may be an issue with how Firaxis has set up the texture definitions.
There is a recent update that is designed to address this issue, have you used the _Latest_ commit from the repository?
If you could provide as much detail as possible to help us pinpoint this, Firaxis Civ version, other mods, that sort of thing.

**Comment by saulshanabrook** [comment]
Yeah you are write, I didn't realize I needed brave new world. I have the campaign edition for mac.
