### ISSUE TITLE
Reword the 'Abilities:' text

### ISSUE THREAD

**Issue by GrantSP** [Thalassicus/cep-bnw#114]
The 'Abilities:' text is very obtuse in giving some information. It should be rewritten to use the same text as is used for the tooltips.
This is true for both the 'Abilities' section with the icons and the 'Abilities' section that uses text to describe the unit.

Specifically the values used should say if they are % of not.
When promotions are shown it should display the actual name of the promotion in the same way the tooltips do.

eg.
The Ottoman Janissary has the promotion _Camaraderie_ which grants a +15% bonus when a friendly unit is in an adjacent tile.
The pedia has this in the 'Abilities:' section
- **when Adjacent to a friendly military unit: 15**

The tooltip which appears when mousing over the promotion icon says:
- **Camaraderie**
-    **+15% when Adjacent to a friendly unit**

(on another note, the tooltip and icon for _Camaraderie_ do not appear in the Flag Promotions above the actual unit.)

eg.
The 'Defense vs Ranged' modifier is worded in the pedia as:
- **Ranged Defense Mod: 50**

whereas the tooltip words it this way:
- **Defense vs Ranged: 50**
-    **+50% Defense vs Ranged Damage**

There are probably many more examples but the point is, if we can use the same text from the tooltip to display in the pedia abilities section, it will both be easier to see what is actually happening and the chances of mismatched text will be eliminated.

**Comment by stackpoint** [comment]
It makes sense to standardize the civiliopedia and tooltip entries to display the same thing.

**Comment by GrantSP** [comment]
The file _Text_TW_PromotionStats.sql_ looks to use the **TXT_KEY_PROMOTION_EFFECT_[name]** as the text for display, whereas the pedia uses the text as defined by **TXT_KEY_PROMOTION_[name]_HELP**.

Why is this necessary? I believe the **TXT_KEY_PROMOTION_EFFECT_[name]** are only used by the mod.
Wouldn't it be advisable to just use the **TXT_KEY_PROMOTION_[name]_HELP** as defined in either the vanilla files or the adjusted ones by the mod?

**Comment by GrantSP** [comment]
Another example provided as a chance to bump this back to the top.

TXT_KEY_PROMOTION_ANTI_TANK is defined by us as: "Bonus vs Tanks (100)"

The vanilla code defines it as: "Bonus vs Tanks (100)"

Exactly the same. Why bother to define them if there is no change?
If we can use the TXT_KEY tags as they exist, both the TAG & the text, then the chances of error is reduced and we provide a more unified gaming experience.

**Comment by stackpoint** [comment]
It's possible that the bonus was modified in earlier iterations of the mod (GEM).

**Comment by stackpoint** [comment]
Were you able to find the TXT_KEY_PROMOTION_EFFECT_[name] in the database? I couldn't find the text in the table for some reason even though the file should be loading.

**Comment by GrantSP** [comment]
This is another example of duplication introducing error.
This is defined in CAT in _Text_TW_PromotionStats.sql_ & CEG in _Armies.sql_, but is commented out in CEG. 
So now the vanilla TXT shows in the pedia and CAT's in the tooltip. Luckily they happen to match.

**Comment by GrantSP** [comment]
Correction. The CEG has it listed twice and it is only the first instance that is commented out.

**Comment by GrantSP** [comment]
And they are different. CEG has it at 50 CAT & vanilla has it at 100

**Comment by stackpoint** [comment]
So the only problem is that CAT has it listed (possibly) unnecessarily?

**Comment by GrantSP** [comment]
The TXT_KEY_PROMOTION_ANTI_TANK specific case yes, but the code needs to be modified to use the pre-existing TXT_KEY tags not specific tags for the tooltip writer.

I'm not quits sure how the tags are called or even where it can be changed.
Ideally we should use the same tags for the tooltips and the pedia.

**Comment by stackpoint** [comment]
Also, I think TXT_KEY_PROMOTION_EFFECT_[name] is used by the tooltip writer to define the promotions/effects/penalties that have a varied value. Such as TXT_KEY_PROMOTION_EFFECT_ADJACENT_FRIENDLY with "for units in adjacent tiles". The tooltip writer would then take the value defined by the mod (let's say 15) and then fill in the blanks "+15% for units in adjacent tiles".

**Comment by stackpoint** [comment]
This should(?) allow us to not have set the specific values inside the text and let the tooltip writer to fill in the blanks.

**Comment by GrantSP** [comment]
Yeah sorry I can't offer any help here. I think that is a fair assumption. Certainly would be the best option.
I think it works something like:
{1_prefix}: {2_sign}{3_value}% {TXT_KEY_}
to provide the finished text like:
[ICON_STRENGTH]: +15% Strength in forests

or whatever the thing is that we are defining.
That way if we change the value to 25% we don't have to change anything.

All the TXT_KEYs can be formulated like this, I think, and we can also look at the building texts like the Wonders I was doing the other day.
