### ISSUE TITLE
Disable Restart Button

### ISSUE THREAD

**Issue by wguldin** [Thalassicus/cep-bnw#115]
(formerly "Can't pick production in city when game is restarted")

If you hit "restart game" on your first turn, a new game will load, and you will be able to found your capital. You can't choose what to produce in that city, though. The button to do so doesn't work.

**Comment by GrantSP** [comment]
There are difficulties with _some_ of the lua code not being reloaded upon restarts. This is part of the reason why the Load Game menu option is removed from the ingame menu.

It is a Firaxis fault as it will also give weird results if you first start a _vanilla_ game and then quit to the main menu and then start a modded game. The end result is you have to quit to desktop at times.

**Comment by wguldin** [comment]
Ah, thanks for the clarification. I'll close the issue then.

**Comment by stackpoint** [comment]
Before my hiatus, I was able to identify the files needed to disable the restart button. I'll look into it again when I have some more free time.

**Comment by stackpoint** [comment]
Restart disabled here: https://github.com/Thalassicus/cep-bnw/commit/02699f5d2b12f987c8fc5bc7ceb9521892e3e62e
