### ISSUE TITLE
Frigate has "Naval Bombardment" flavor

### ISSUE THREAD

**Issue by GrantSP** [Thalassicus/cep-bnw#116]
This melee ship still has the flavor of "Naval Bombardment" as one of it's _Good for:_ abilities.

There doesn't appear to be any other mismatched types of ships with this flavor.

EDIT:
Some of the other naval units don't seem to have the same sort of flavors as their related units.

The flavors are NAVAL, NAVAL_GOLD, NAVAL_RECON, NAVAL_BOMBARDMENT, FLAVOR_OFFENSE & FLAVOR_DEFENSE
I'll shorten these to N, NG, NR, NB, NO & ND.
The value for each flavor is added immediately after. eg. NO8 for NAVAL_OFFENSE with a value of 8.
eg.

Units that aren't currently used are also included in this list. Submarines aren't as they are slightly different to discuss.

Battleship -- Ranged -- ND4, NB8 & NO8
Bireme -- Ranged -- NB8 & NR4
Dromon -- Ranged -- NB16 & NR8
Caravel -- Melee -- N8 & NR8
Carthaginian Quinquereme -- Ranged -- NB16 & NR8
Destroyer -- Melee -- N & NR
Dutch Sea Beggar -- Melee -- NG8 & N16
English SoL -- Ranged -- NB16 & NR16
Frigate -- Melee -- N8 & NB4
Galleass -- Ranged -- NB8
Galley -- Ranged -- NB16
Ironclad -- Ranged -- ND4, NB8 & NO8
Korean Turtle Ship -- Melee --ND8, N16, NR16 & NO8
Missile Cruiser -- Ranged -- ND4, NB8 & NO8
Missile Destroyer -- Melee -- N8 & NR8
Portuguese Nau -- Melee -- NR16 & N16
Privateer -- Ranged -- NB8 & NR8
Liburna -- Melee -- N16 & NR16
Venetian Galleass -- Ranged -- NB16

As you can see not all _Ranged_ ships share the same flavors and not all _Melee_ ships are "flavored" the same either.
The question I see is, just what are the criteria for _FLAVOR_s? Additionally what determines the values assigned?

I think special attention should be placed on the 'Frigate & Galleass.

**Comment by GrantSP** [comment]
I was just about to start assigning Flavors to these units when this question occurred to me:

Why are assigning Flavors in identical files in both CAT & CEG?
Surely the CEG file **CEAI_Units.sql**, where these FLAVORs are set, is redundant?
CEG is dependent on CAT which assigns them it the **CEAI_Units.sql** in that directory.

These two files are identical, except for the LoadedFile command at the bottom of the file. (this too is strange as the necessity to check for the changes made in one will be pointless as those changes are made in the other. The changes are made if one or both files load and only fails if both aren't loaded.)

I believe we can safely remove the file found in CEG as it serves no purpose.
Yes?

**Comment by stackpoint** [comment]
Nope. I believe that these flavor files sets the flavor values for the custom buildings/units added by CEG.

**Comment by GrantSP** [comment]
Whether they set custom buildings/units only, or also adjust vanilla stuff, (which I believe they do). To have the same file in different locations is strange. Don't you agree?

**Comment by stackpoint** [comment]
The flavor code is automated so it goes: loads CAT -> Mods vanilla flavors -> CEG -> Mods CEG + vanilla flavors. We can't remove the files from either mod.

**Comment by GrantSP** [comment]
But why? The files are identical!
If CAT loads and nothing changes with CEG, there is no need to have the CEG file.
If we need a blank file as a placeholder in CEG then fine, but having to change 2 files for the same task is crazy.

**Comment by stackpoint** [comment]
CEG has additional units/buildings so the automatic flavor code needs to load flavors for those new units/buildings.

**Comment by GrantSP** [comment]
I have no idea what you are talking about. :confused: 
There is no new code in the CEG version of the file.
That means CEG stuff is defined in CAT, which is OK. But that negates the need for the CEG version.

**Comment by stackpoint** [comment]
One of the ways that file assigns flavors is through it's UNITCOMBAT. I know that CEG reassigns some UNITCOMBAT classes so that's a change. I don't know if there's any other code other than Unit_ResourceQuantityRequirements that assigns flavors without using UNITCLASS. I also can't remember if CEG adds any new units with the vanguard line removed that doesn't add a new UNITCLASS. Maybe some of the naval units.

**Comment by GrantSP** [comment]
Hmm...
I'm not convinced but I will defer to your judgment.
What I will therefore do is assign more reasonable FLAVORs to these naval units in the CEG version and let the chips fall where they may.

**Comment by stackpoint** [comment]
For example, we add UNITCLASS_BIREME in CEG that doesn't exist in CAT. So although the CAT flavor files have a check that adds flavors to units that have UNITCLASS_BIREME, none actually exist in CAT.

You should also keep both files identical if possible.

**Comment by GrantSP** [comment]
This is exactly the type of thing we need  to **avoid**.

On the one hand we make the Tootipwriter to avoid needlessly handwriting the TXT_KEYs everytime, and then we go and duplicate files that have no bearing on what they actually do.

If UNITCLASS_BIREME isn't in CAT, which it isn't, then it shouldn't be defined there.
The whole purpose of the differentiation in the modules was, I thought, so they could be modular.
If we continue to have crossovers between the mods then the need to keep them separate becomes lost.

@skodkim had a similar experience with where to place some text for a change he made. The only place where a similar thing was found was in the CAT mod despite the changes taking place in CEG.

I just do not fathom the need to make things more complicated than they need. It does nothing to make this more accessible to modders. Having to jump through hoops just to change a UNIT_FLAVOR. :anger: 

I feel sorry for you having to bear the brunt of my venting all the time. Sorry. :smiley: 

Ok, I will keep both files in sync. Let's move on.

Really, that's the anger emoticon?!!

**Comment by stackpoint** [comment]
The way the code is written is that it checks for UNITS in UNITCLASS_BIREME. If that check fails then there are no flavors made for biremes. So there are no compatibility problems in that respect since the flavors are only written in CEG.

**Comment by GrantSP** [comment]
@stackpoint I think you misunderstand my position. It isn't the efficacy of the code that I question, its the point of it.
I have no doubts about what is done to which units/buildings and how. The question for me is always: why?
The rationale for a lot of things is lacking and that means, for me at least, the need to get that clear first so I can properly evaluate the changes.

Let me give you an example. I changed the visibility of the atolls/isles and gave an explanation in my commit comments, remember. That clearly states my rationale for that change.
Aside from this issue we are discussing we also had the Anti-Tank thing a couple of days ago. If it was explained somewhere clearly why that was made there would be no need for me to question. I may not agree with it, but I could see some decision making took place and I would leave it to those that like to balance things to take up the questioning.
I am not a difficult person by nature but I do get upset by these small, easily fixed omissions.

I'm not expecting you to agree with my every remark but I do expect this mod to easier to change than it is at the moment. This feels more like a programmers exercise than a mod.

</end_rant>
