### ISSUE TITLE
Tech FLAVORS

### ISSUE THREAD

**Issue by GrantSP** [Thalassicus/cep-bnw#117]
The following TECHS are lacking FLAVOR values and hence there are no _Good For:_ labels assigned to them in the UI.
- Pottery
- Writing
- Drama & Poetry
- Construction
- Engineering
- Theology
- Education
- Architecture
- Printing Press
- Scientific Method
- Electricity
- Mass Media
- Electronics
- Plastics
- Ecology

All these techs have FLAVORs assigned in the vanilla game.
Why are they now blank? Also the database now has a number of NULL _TechType_s with _FlavorType_s & _Flavor_s assigned.

As with the Unit Flavors, what is the criteria for assigning _FLAVOR_s and their values?

**Comment by stackpoint** [comment]
When I looked at the Techology_Flavors table, I believe I saw flavors for the above technologies. I also saw a bunch of NULL TechTypes assigned Flavor values but nothing in CEAI_Techs.sql to indicate that behavior.

**Comment by stackpoint** [comment]
I just double checked and it may be "build.PrereqTech" that's causing the NULL value to be set. Since some buildings don't have a PrereqTech and that value would be NULL.

This can be solved at the end using something like:

``` sql
DELETE FROM Technology_Flavors WHERE TechType IS NULL;
```

**Comment by stackpoint** [comment]
Fixed here: https://github.com/Thalassicus/cep-bnw/commit/4cf7328f9c27ee6f7a517a686a94d76b68de52d3
