### ISSUE TITLE
[3.12.1] Renowned warrior

### ISSUE THREAD

**Issue by skodkim** [Thalassicus/cep-bnw#118]
Option two of the Renowned Warrior event doesn't give any meaning.

You have the option of upgrading you warrior to a spearman for the price of 300 gold, which seems like a really bad deal given that the Spearman is (in the current version) cheaper to build than the Warrior.

\Skodkim
![civ5screen0009](https://f.cloud.github.com/assets/6018459/1839114/adedbf8e-7471-11e3-8785-6b76687c35f3.jpg)

**Comment by stackpoint** [comment]
This seems like a severe balance issue with this option. Any suggestions for an alternative?

**Comment by GrantSP** [comment]
The best option would be the next upgrade of that unit in whatever flavor your civ has.
So for 100 Gold (300 is way too much) upgrade to a swordsman with no resource hit.
Or, give some really good promotions to help the unit.

**Comment by skodkim** [comment]
Renowned Archer should probably also be changed so you have the option to upgrade to a composite Bowman in ste
ad of a chariot Archer.

Both changes are rather easy and have been included.

\Skodkim

![mods zip](https://f.cloud.github.com/assets/6018459/1858200/92512c3e-7787-11e3-99b7-c0e1780ed579.jpg)

**Comment by skodkim** [comment]
Fixed for next version

\Skodkim
