### ISSUE TITLE
[3.12.1] Wrong info about influence from killing barbarians close to CS

### ISSUE THREAD

**Issue by skodkim** [Thalassicus/cep-bnw#119]
When you kill a barbarian unit close to a city states borders you're told that your influence with them has increased by 12 when in fact it changes by 15.

CEP changes the value in Diplomacy\CED_Data.xml

The original text string "TXT_KEY_NOTIFICATION_MINOR_BARB_KILLED" goes:

<Row Tag="TXT_KEY_NOTIFICATION_MINOR_BARB_KILLED">          <Text>You have killed a group of Barbarians near {1_CivName:textkey}! They are grateful, and your [ICON_INFLUENCE] Influence with them has increased by 12!</Text>
</Row>

\Skodkim

**Comment by skodkim** [comment]
Where should I put this this fix?

\Skodkim

**Comment by GrantSP** [comment]
In the CAT mod open the file _Core.sql_. It is divided into sections for different types of messages.
From line 7 it is for **City-States**, add a new line using the same format as the others with the modified text you have devised.

It would really be good if we could have that _Influence_ value assigned to a stored value somewhere so that the text key could stay the same and only the value needs adjusting. Maybe another day.

**Comment by skodkim** [comment]
What is the point of making the text string in the CAT module if the value is changed in the CEG module? As I understand it you can use the former without the latter even though I have never tried it.

\Skodkim

**Comment by GrantSP** [comment]
That's a question I ask all the time. I see no reason for this type of
change to be in CAT, yet that's where the other changes are so just go with
it.

**Comment by GrantSP** [comment]
Then again, if you can find similar changes in CEP, you could put it there.

**Comment by skodkim** [comment]
I already looked in CEG and there's really nowhere logical to put it so I guess I'll just put it in CAT - unless Thal suddenly jumps in to this discussion and says otherwise (I could also make a note in the commit for him)

\Skodkim

**Comment by stackpoint** [comment]
Did you make the corresponding change to the google spreadsheet?

**Comment by skodkim** [comment]
No

see https://github.com/Thalassicus/cep-bnw/commit/645bf30319e5a68ba76b09c777f478b8eadaec81#commitcomment-5019366

\Skodkim
