### ISSUE TITLE
Flag Promotions

### ISSUE THREAD

**Issue by GrantSP** [Thalassicus/cep-bnw#120]
In [this issue](https://github.com/Thalassicus/cep-bnw/issues/114) I made mention of the fact the Ottoman promotion _Camaraderie_ is not shown above the unit.

Looking further into this it appears the file **FP_Data.sql** is used to decide which promotions are shown or not based on a database tag _IsVisibleAboveFlag_.

The selection of the specific promotions could do with some refining.
There are a lot of needless specific selections and some not used promos still referenced.

It looks like most of the Civ unique promos aren't shown above the flag. Why?
Just how are the decisions to show a promotion made?

**Comment by stackpoint** [comment]
Looking at the [code](https://github.com/Thalassicus/cep-bnw/blob/new-features/Cin/Cin/Interface/FlagPromotions/FP_Data.sql), it seems like the logic (most likely straight from GEM) is that all the promotions are invisible by default, except for the following promotion are visible (which look like the promotions you gain through experience):

``` sql
UPDATE UnitPromotions SET IsVisibleAboveFlag = 0;

UPDATE UnitPromotions SET IsVisibleAboveFlag = 1
WHERE Type IN (
    'PROMOTION_IGNORE_TERRAIN_COST_NOUPGRADE'   , --not on all units
    'PROMOTION_IGNORE_TERRAIN_COST'             , --not on all units
    'PROMOTION_SKIRMISH'                        , --earned
    'PROMOTION_MORALE'                          , --not on all units
    'PROMOTION_STATUE_ZEUS'                     , --not on all units
    'PROMOTION_MERCENARY'                       , --Germans
    'PROMOTION_DESERT_POWER'                    , --barbarians
    'PROMOTION_ARCTIC_POWER'                    , --barbarians
    'PROMOTION_HILL_FIGHTER'                    , --barbarians
    'PROMOTION_WOODSMAN'                        , --barbarians
    'PROMOTION_BOMBARDMENT_1'                   , --
    'PROMOTION_BOMBARDMENT_2'                   , --
    'PROMOTION_BOMBARDMENT_3'                   , --
    'PROMOTION_BLITZ'                           , --
    'PROMOTION_LOGISTICS'                       , --
    'PROMOTION_EXTRA_SIGHT_NOUPGRADE_II'        , --China
    'PROMOTION_EXTRA_MOVES_I'                     --
```

The other group that are visible are the persistent upgrades which aren't penalties or not upgradable or on the list specifically:

```
) OR (Class = 'PROMOTION_CLASS_PERSISTANT' AND NOT (
       Type LIKE '%PENALTY%'
    OR Type LIKE '%NOUPGRADE%'
    OR Type IN (
        'PROMOTION_ROUGH_TERRAIN_ENDS_TURN'     , --penalty
        'PROMOTION_ONLY_DEFENSIVE'              , --penalty
        'PROMOTION_NO_DEFENSIVE_BONUSES'        , --penalty
        'PROMOTION_MUST_SET_UP'                 , --penalty
        'PROMOTION_CITY_SIEGE'                  , --demolish
        'PROMOTION_CITY_ASSAULT'                , --demolish
        'PROMOTION_NEW_UNIT'                    , --
        'PROMOTION_DEFENSE_1'                   , --
        'PROMOTION_DEFENSE_2'                   , --
        'PROMOTION_CAN_MOVE_AFTER_ATTACKING'    , --
        'PROMOTION_GREAT_GENERAL'               , --
        'PROMOTION_INDIRECT_FIRE'               , --
        'PROMOTION_FREE_UPGRADES'               , --citystates
        'PROMOTION_ANTI_CAVALRY'                , --Ottomans
        'PROMOTION_MEDIC_GENERAL'               , --Mongolia
        'PROMOTION_SENTRY'                      , --America
        'PROMOTION_DEFENSIVE_EMBARKATION'       , --Songhai
        'PROMOTION_FREE_PILLAGE_MOVES'          , --Denmark
        'PROMOTION_OCEAN_MOVEMENT'              , --England
        'PROMOTION_OCEAN_IMPASSABLE'            , --Korea
        'PROMOTION_HANDICAP'
    ))
);
```

I'm not sure which of these you feel are needlessly specific but I can help review any of these promotions you feel can be removed from either category and we can proceed autonomously from there.

But I feel the reason that many of the promotions aren't shown to prevent clutter. You can see the clutter above the AI units in this [video](http://www.youtube.com/watch?v=PrA4gpJ2idc).

**Comment by GrantSP** [comment]
Agreed, this looks like almost a straight copy from GEM. It needs a bit of _massaging_.
e.g. the Ottomans has a promo "Anti Cavalry" listed, I don't think this exists anymore and the one promo they do have "Camaraderie" isn't in the code.

The easiest option is to set **ALL** promos as invisible and then assign rules to switch the needed ones back to visible.
So we would then have Civ specific promos shown if they affect the outcome of battle, ie. if the Combat outcome panel refers to a value from a promo, that promo needs to be shown.
Promos that the game assigns that have no bearing on combat or movement decisions need not be shown.
These icons should only serve as an an aid in determining our choices, not just shown for the sake of being shown.

I don't know if it is possible but if we could remove the promo that is superseded from the display that would free up the interface. Probably can't do that though.

At any rate, this is **way** down the list of things needed.

**Comment by Thalassicus** [comment]
I added more documentation to this code to explain the pattern.

The basic pattern is "equipment" effects do not show over units, and don't upgrade with the unit. This is anything we can see immediately by looking at the unit, like how an archer can only attack at range because it uses a bow.

Effects from unique units are in a weird grey area I've never been able to completely decide on. Some upgrade with the unit, while others don't. At the very least I'll set this one to visible.
