### ISSUE TITLE
[3.12.1] Yields sum in city view off

### ISSUE THREAD

**Issue by skodkim** [Thalassicus/cep-bnw#121]
It seems yields in the city view are off. To be more precise the sum is off while the individual components seem ok.

Look in the attached screenshots. Science sum says 12, while the components say 6 from Population and 4 from Buildings. I have 6 Population (=6 science)+Capital/National Yields (=4 science) so 10 seems to be correct.

Gold sum seems off too while the others seem ok.

Edit: Culture sum seems off too

\Skodkim

![civ5screen0014](https://f.cloud.github.com/assets/6018459/1844200/382a6160-7509-11e3-9439-95ebbc30f85d.jpg)
![civ5screen0016](https://f.cloud.github.com/assets/6018459/1844201/382a6c3c-7509-11e3-83e5-f9d5a3859354.jpg)
![civ5screen0017](https://f.cloud.github.com/assets/6018459/1844238/5a9c157c-750e-11e3-8db8-631ead33defb.jpg)

**Comment by GrantSP** [comment]
Are these examples using just the Communitas mods? This hasn't been an issue for at least a couple of versions.
I saw this sort of thing at least 3 months ago but since the YieldLibrary updates I have not seen it.

**Comment by skodkim** [comment]
GrantSP notifications@github.com skrev:

> Are these examples using just the Communitas mods? This hasn't been an
> issue for at least a couple of versions.
> I saw this sort of thing at least 3 months ago but since the
> YieldLibrary updates I have not seen it.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Thalassicus/cep-bnw/issues/121#issuecomment-31593053

## 

Sendt fra min Android telefon med K-9 Mail. Undskyld hvis jeg er lidt kortfattet.

**Comment by skodkim** [comment]
No it isn't. Should have mentioned that. None of the other mods change city view (or the yield library) though.

If no-one else can confirm this I guess I'll just have to test it later on using only the communitas mods.

\Skodkim

GrantSP notifications@github.com skrev:

> Are these examples using just the Communitas mods? This hasn't been an
> issue for at least a couple of versions.
> I saw this sort of thing at least 3 months ago but since the
> YieldLibrary updates I have not seen it.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Thalassicus/cep-bnw/issues/121#issuecomment-31593053

## 

Sendt fra min Android telefon med K-9 Mail. Undskyld hvis jeg er lidt kortfattet.

**Comment by skodkim** [comment]
Just tested using a clean install on v 3.12.2 (no other mods than ingame editor). Gave myself a bunch of Buildings and checked the yields. As seen in the screenshots these were off Again.

Edit: Just hit Next Turn and now they seem ok...

\Skodkim
![civ5screen0026](https://f.cloud.github.com/assets/6018459/1857664/8e867d44-777c-11e3-9d27-fb1f89f4b997.jpg)
![civ5screen0024](https://f.cloud.github.com/assets/6018459/1857663/8e85e58c-777c-11e3-9b68-e062bde81625.jpg)

**Comment by skodkim** [comment]
Just tested Again with 3.12.2 and otherwise only Ingame Editor installed. There's definately some weird issues going on here and I have a hard time understanding what triggers it.

The game starts ok, I quickly gave myself a monument and a shrine and the issues started. First thing I noticed is that there would be a one turn lag before the city view was updated. Then yield infos would start becoming incorrect. I also noticed that when I picked the Hagia Sophia that Mousing over the specialists the city view said that they'd give +1 faith (they didn't though - another bug), while there was no info on this in the yields section in the left side of the screen. I'm certain however that this info was shown in another game I just played...

Cache etc cleared prior to test!

\Skodkim

![logs zip](https://f.cloud.github.com/assets/6018459/1872184/c2e936c8-78a1-11e3-889d-d9d3eed7b3f2.jpg)

**Comment by stackpoint** [comment]
Let me try to piece together some of the pieces of this puzzle. Some of this information may be incorrect since I haven't had a chance to look at the yield library since November.

The 1 turn lag may or may not be caused by the way IGE grants buildings. If it isn't then YieldLibrary needs to update the Yields cache (?) everytime a building is constructed as opposed to inbetween turns. Actually, this may not actually be a problem in normal play since I believe that you can't rush construction mid-turn. So you'd only need to update the Yields cache when purchasing a building or being granted one through policies. Not sure if this is being done already.

The dissonance between projected yields and actual yields could be the tooltip code showing the correct yields from various places (policies, buildings) but the YieldLibrary failing to grant those yields for various reasons.

**Comment by skodkim** [comment]
You may be correct in that the one turn lag is because of the way IGE grants buildings. I don't remember if I've seen it in a real game (been testing so many things I kind of lost track). I'll test later with a great engineer to quicken up the process.

The dissonance is definitely not because of IGE since I see this all the time during games (and I don't grant myself buildings with IGE).

Sounds like the yield library could really use a brush up. Sound like it causes bugs with several wonder and (I think) also the missing culture from cultural buildings with the policy Ceremonial Rites.

\Skodkim

**Comment by skodkim** [comment]
Just thought of a "normal" way of gaining Buildings mid-turn: rush buying.That may be why I'm seing this so much, since I do a lot of rush buying.

\Skodkim

**Comment by Umbrood** [comment]
Happens to me as well, I just got this from steam workshop yesterday, I am assuming that is the latest version.
Not only does it show wrong yields in city, but in world as well.

Also, the yields that are displayed, the number shown does not coincide with any tile in the vicinity, ( As in I have a tile that shows 10 hammers, but no tile in the city gives that many, ).

Aside from communitas I also run infoaddict, if that changes anything?

**Comment by skodkim** [comment]
May be related to this issue: https://github.com/Thalassicus/cep-bnw/issues/179

\Skodkim

**Comment by stackpoint** [comment]
This is definitely connected to the YieldLibrary problem. City View should be better with yields now. Further reports should be brought up in that issue.
