### ISSUE TITLE
Venice gets settler for building pyramids

### ISSUE THREAD

**Issue by qqqbbb** [Thalassicus/cep-bnw#124]
Maybe replace that settler with merchant of venice?

**Comment by stackpoint** [comment]
Yes, it probably should.

Best (only?) way to do this is through the lua. Though there's a lot of lua running overhead already. We may have to write a custom lua code that grants a settler/merchant.

I believe all the settler -> merchant conversions in vanilla is done with the DLL.

**Comment by stackpoint** [comment]
Here's some background on the Venice settler conversion: http://forums.civfanatics.com/showthread.php?t=500676

Looks like using the BuildingConstructed hook to check if the leader has NoAnnexing active then to find the settler and replace it seems to be the way to go.

**Comment by Thalassicus** [comment]
I'd use the NewUnit lua event instead of BuildingConstructed. That will point to the settler. The building might be created before the settler, which might mean no settler exists yet when BuildingConstructed runs.

**Comment by Thalassicus** [comment]
Fixed this bug.
