### ISSUE TITLE
Siege tower bonus vs cities

### ISSUE THREAD

**Issue by qqqbbb** [Thalassicus/cep-bnw#126]
Siege tower has 300% ranged bonus vs cities but it has no ranged attack.

**Comment by GrantSP** [comment]
Correct. The promo _City Siege_ was swapped with _City Assault_.
Not sure if we should just revert the swap or make an exception for the Assyrian Battering Ram. It is the only **MELEE** unit in the group that gets the change, so the promo no longer fits. However I am not sure why we need to swap these promos in the first place.

**Comment by GrantSP** [comment]
This can be discussed in the new issue, #207 .
