### ISSUE TITLE
Can build improvements on forest/jungle before researching tech to remove them.

### ISSUE THREAD

**Issue by wguldin** [Thalassicus/cep-bnw#127]
Playing as Korea, I started with the normal free worker and noticed on a jungle tile that I could turn it into a farm after 12 or so turns. The tooltip said it was jungle until it was fully improved, then it became a normal farm, with Korea's science bonus. 

I believe this also happened with forests. I didn't test this with Marsh, though.

This was on version 3.12.2, by the way.

**Comment by stackpoint** [comment]
Did we enable farms on jungles again? Though they definitely should not be constructable on forests.

**Comment by wguldin** [comment]
No, the jungle is removed in the end, you're just able to build a farm and remove the jungle in the process as Korea before you've researched the tech required (animal husbandry and the wheel, IIRC) to remove jungle and forest.

**Comment by skodkim** [comment]
Just tested using Korea in 3.13. I was able to build Farms on Jungle Tiles from turn 1 without having discovered animal husbandry. I was not able to do it on forests.

Did not test with other civs.

\Skodkim

**Comment by stackpoint** [comment]
Not a Korea specific issue. I could not replicate with forests. Found the code, regarding farms on jungles, should be fixed in the next build.
