### ISSUE TITLE
[3.12.2] Sistine Chapel does not modify culture in cities

### ISSUE THREAD

**Issue by skodkim** [Thalassicus/cep-bnw#130]
Tested with 3.12.2+Ingame Editor (cache cleared etc. prior to test).

The Sistine Chapel gives +1 culture but the 25% modifier to culture in all cities does not work.

Confirmed in different games and from other users on civfanatics.

\Skodkim

**Comment by skodkim** [comment]
May be related to this issue: https://github.com/Thalassicus/cep-bnw/issues/179

\Skodkim

**Comment by stackpoint** [comment]
This should be working in theory but needs to double checked this with the new features branch. Further problems should be brought up in the linked issue.
