### ISSUE TITLE
[3.12.2] Wat Pha Kraev does not modify gold and culture

### ISSUE THREAD

**Issue by skodkim** [Thalassicus/cep-bnw#131]
Tested with 3.12.2+Ingame Editor (cache cleared etc. prior to test).

The Wat Pha Kraev gives +1 faith but the 10% modifier to culture and gold from temples and shrines (only tested with the latter) does not work.

Confirmed in different games and from other users on civfanatics.

\Skodkim

**Comment by skodkim** [comment]
May be related to this issue: https://github.com/Thalassicus/cep-bnw/issues/179

\Skodkim

**Comment by stackpoint** [comment]
This should be working in theory but needs to double checked this with the new features branch. Further problems should be brought up in the linked issue.
