### ISSUE TITLE
Ceremonial rites isn't working properly

### ISSUE THREAD

**Issue by brutha2** [Thalassicus/cep-bnw#132]
Also, I have a problem with the ceremonial rites policy, it says in the city screen that buildings are getting the +1 culture from culture buildings, but it's not adding up to the total; it say +13 when I'm only getting +11 per turn. Everything else in the mod seem to be working fine. Here's a screenshot:

![2014-01-10_00003](https://f.cloud.github.com/assets/6180391/1889162/3595ea60-7a17-11e3-884a-acd95782d4e8.jpg)

**Comment by skodkim** [comment]
Ceremonial rights bug is already documented here: https://github.com/Thalassicus/cep-bnw/issues/54

The other bug is documented here: https://github.com/Thalassicus/cep-bnw/issues/121

Concerning the latter I would very much like you to write your experiences in that thread as it had so far seemed like I was the only one who experienced this and I/we have so far had a hard time finding out what was going on.

\Skodkim

**Comment by brutha2** [comment]
It's all connected to the ceremonial rights thing: it's just showing the culture that my city should have with CR as if it was working. If the CR issue is known about, I'm not sure what else I can add and I'm sure it'll be sorted for the next version!
