### ISSUE TITLE
Puppetted city does not access it's city tile.

### ISSUE THREAD

**Issue by brutha2** [Thalassicus/cep-bnw#134]
So, I was given a city in a peace settlement, and it immediately started starving because it wasn't using the food from the city tile for some reason (as if that tile didn't produce anything).  I have also got the lua file, though I'm not sure how to attach it.

![2014-01-11_00004](https://f.cloud.github.com/assets/6180391/1894112/c0f824dc-7ad1-11e3-9d05-8ba5ff9cc6c5.jpg)
![2014-01-11_00003](https://f.cloud.github.com/assets/6180391/1894113/c156d3ba-7ad1-11e3-8f87-737f911db470.jpg)

**Comment by skodkim** [comment]
If you rename the lua file as a jpg you can drag and drop it.

\Skodkim

**Comment by brutha2** [comment]
Here's the lua file.
![lualua](https://f.cloud.github.com/assets/6180391/1894262/0b28db22-7add-11e3-9717-e064fe5c85c8.jpg)
I've also attached the save file if that helps.
![korea 2](https://f.cloud.github.com/assets/6180391/1894266/3291f8ce-7add-11e3-8e65-ab73d3cb1ca3.jpg)

**Comment by stackpoint** [comment]
I believe this is a vanilla bug as shown here: http://forums.civfanatics.com/showthread.php?t=518430

But it's definitely possible for the mod to be causing this problem too. We'll have to wait until the vanilla bug is sorted out before we can isolate any problems with the mod though.
