### ISSUE TITLE
Conquistador Formatting Error (CEL_End.sql not loading)

### ISSUE THREAD

**Issue by stackpoint** [Thalassicus/cep-bnw#135]
I can't link to the code in GitHub since it hasn't been uploaded but it's in the released version. The below code is causing CEL_End.sql to fail loading. I can't identify any formatting errors but it must be in there.

``` sql
 --
-- Dummy Conquistador with no religious spreads remaining, but still alive
--

INSERT INTO Unit_AITypes(UnitType, UnitAIType)                            SELECT 'UNIT_SPANISH_CONQUISTADOR_2', UnitAIType    WHERE UnitType = 'UNIT_SPANISH_CONQUISTADOR';
INSERT INTO Unit_ClassUpgrades(UnitType, UnitClassType)                    SELECT 'UNIT_SPANISH_CONQUISTADOR_2', UnitClassType    WHERE UnitType = 'UNIT_SPANISH_CONQUISTADOR';
INSERT INTO Unit_FreePromotions(UnitType, PromotionType)                SELECT 'UNIT_SPANISH_CONQUISTADOR_2', PromotionType    WHERE UnitType = 'UNIT_SPANISH_CONQUISTADOR';
INSERT INTO Unit_ResourceQuantityRequirements(UnitType, ResourceType)    SELECT 'UNIT_SPANISH_CONQUISTADOR_2', ResourceType    WHERE UnitType = 'UNIT_SPANISH_CONQUISTADOR';
INSERT INTO Unit_Flavors(UnitType, FlavorType, Flavor)                    SELECT 'UNIT_SPANISH_CONQUISTADOR_2', FlavorType, Flavor WHERE UnitType = 'UNIT_SPANISH_CONQUISTADOR';  
```

See: http://forums.civfanatics.com/showthread.php?t=518797

**Comment by skodkim** [comment]
@stackpoint or whoever is able to do this, I think we need to make a hotfix until we find a better solution for this. Have been going through the files and There’s a lot of leader specific Things that are affected by this bug. Instead of making a pull request I'll upload a hotfix here for someone to publish (if you agree). Two Things are addressed:

1: The above mentioned lines are commented out in CEL_End.sql. This makes the rest of the file load and prevents further leader related bugs
2: The dummy unit UNIT_SPANISH_CONQUISTADOR_NO_RELIGION has been commented out in CEL__J_Z.xml. Before it was buildable for all civilizations and it seems to be part of a half build solution.

\Skodkim

![hotfix zip](https://f.cloud.github.com/assets/6018459/1910523/feba48ce-7d18-11e3-9572-aa8d221984b0.jpg)

**Comment by stackpoint** [comment]
I actually don't know how to compile a release version. At least with the civ5mod file, and I think the game does a md5sum check so I can't just replace the file as if it was just an archive file.

**Comment by skodkim** [comment]
@stackpoint Guess we'll have to wait for someone else to do it then.

Would just like to add that you misunderstood the purpose of the attached files. It was not meant for someone to just replace the files of a new release but to look at the changes and merge them in to the project (if they agree with the changes).

\Skodkim

**Comment by stackpoint** [comment]
Yeah, your changes look fine. We'll have to wait until Thal uploads his local changes made in 3.13 before I could merge your files though.

**Comment by stackpoint** [comment]
Gothic has identified the section of code here: http://forums.civfanatics.com/showthread.php?p=13008967#post13008967

**Comment by skodkim** [comment]
Yes, (must have been on Skype) UNIT_SPANISH_CONQUISTADOR_2 simply doesn't exist anywhere else in the mod so something's definitely fishy about the statement.

I did however try replacing it with UNIT_SPANISH_CONQUISTADOR_NO_RELIGION (might just have been a typo) but this doesn't fix the problem so there may be a syntax error as well.

I wish I knew sql better!

\Skodkim

**Comment by GrantSP** [comment]
I don't know if it was mentioned elsewhere and I missed it but if you are discussing something in a branch other than the **Stable** one, it would be helpful if you mention which one.

I was searching through the _Leaders_ code trying to find this elusive _Conquistador bug_ only to find it in the **New-Features** branch.
Ironing out bugs that aren't released into the wild is fine but probably not an _Issue_ as such, more like a "Work in progress".

Anyway, now at least I know what to look for when I get home.

@stackpoint About your comment above regarding the _md5_ checksum on the files. If you are making a release for Steam this is **absolutely** essential as Steam uses this to do its version checking. With any other method of distribution it makes no difference, the game itself does not use _md5_ checksums to verify files. So you could take all the files on GitHub, compile them in ModBuddy and then manually change them, thus making the _md5_ checksum fail and the game wouldn't even know.

**Comment by GrantSP** [comment]
I have a question about this new unit.
**Why?**
Without having the vanilla code in front of me to compare, but just looking at the code, it seems all we are doing is removing the _Unwelcome Evangelist_ & _Rival Territory_ promotions, and giving it an extra religion spread and then renaming it to **UNIT_SPANISH_CONQUISTADOR_NO_RELIGION**.
It is this renaming that necessitates the CEL_End.sql code to assign the unit into the correct tables.

Is just modifying the existing unit not good enough?

**Comment by stackpoint** [comment]
@GrantSP, I was unaware that Thal had built 3.13 off the new features branch which is why I hadn't commented out the bugged code yet. Since the code in question did not appear in GitHub's code search function, I had assumed that he had just not uploaded it yet...

**Comment by GrantSP** [comment]
Oh is that what is happening, we have a few users out there with a
different version to what is on GitHub?
That makes it a whole new ball game.
Well if we can't wait we could just compile the stable branch as release or
even just the CEG mod as a hotfix.

Do you know if the Steam release is affected?

**Comment by stackpoint** [comment]
As far as I know, 3.13 is built off the new-features branch. I was under the incorrect assumption that Thal hadn't updated the repo.

**Comment by stackpoint** [comment]
Fixed here: https://github.com/Thalassicus/cep-bnw/commit/a0dc58fe0aa077e313e0eb59d05edda950a9f64d

**Comment by stackpoint** [comment]
Not exactly fixed. CEL_Events.lua:278 has code in place to use these units.

**Comment by stackpoint** [comment]
UNIT_SPANISH_CONQUISTADOR_2 definitely needs to be renamed UNIT_SPANISH_CONQUISTADOR_NO_RELIGION but the syntax issue with the SQL needs to be solved as well as making the unit invisible and not constructable.

**Comment by GrantSP** [comment]
There is the FROM clause missing between each SELECT & WHERE clauses.
There needs to be a:
FROM Unit_AITypes

If we rename the unit and fix this sql it might  just work.

**Comment by GrantSP** [comment]
Because the formatting was different it didn't register with me straight
away.
Sql goes:
Command - choice - location - criteria

**Comment by stackpoint** [comment]
Isn't location optional since it's drawing from the same table?

**Comment by GrantSP** [comment]
Hmm... well it might be ok but I am pretty sure if you use a WHERE there
must be FROM

**Comment by GrantSP** [comment]
OK I just got home a little while ago and I have just now grabbed the code as it stands and have made myself a version to work with.

This Conquistador thing is interesting.
- I removed the comment marks and restored the code to include the new unit.
- Renamed the new unit to include the _NO_RELIGION suffix
- Added an override to make the unit only available to Spain
- Changed the sql to have a FROM clause

The result, no errors and only Spain looks to have the new unit but, I can't believe this is the way to make the Conquistador spread religion. Something just feels clunky and tacked on.

I will continue to try and figure this out but it is probably best to release with this unit removed.

**Comment by stackpoint** [comment]
I think that the unit is only supposed to be a placeholder and isn't actually supposed to be constructable in cities. We need to figure out how to make the unit invisible to the pedia, the tech tree, and not constructable in cities. 

Maybe we can set the units' ObsoleteTech to TECH_AGRICULTURE so to make sure the unit isn't constructable.

Not sure if the Units table has flags to hide the unit in the TechTree or the Pedia.

**Comment by GrantSP** [comment]
Making it invisible in the pedia should be ok but we will probably have the same problems with the tech tree as we with the Marine and AA Gun. That's why they are shunted off to the dark depths of "Future Tech" :)

**Comment by stackpoint** [comment]
Okay, figured out a way to get rid of the units in the tech tree and tested it on the marine and the anti-tank gun. You can do this by setting ObsoleteTech to TECH_AGRICULTURE and PrereqTech to NULL. This works by letting the unit be constructable without a tech (and not be shown in the tech tree) while getting obsoleted from the start of the game (TECH_AGRICULTURE).

See https://github.com/Thalassicus/cep-bnw/commit/1d1581b3ba1df178f4c780106564de0ad7531f83

**Comment by GrantSP** [comment]
You have beaten me to it.

I am at the moment writing up the commit for the change for this 'bug'.

I have been able to successfully make the dummy unit invisible and
unbuildable and now the 'real' unit can spread religion and when it gets
down to the last religion spread it converts into this dummy 'no religion'
unit.

Everything looks like it works as we want.

On 27 January 2014 11:49, stackpointer notifications@github.com wrote:

> Okay, figured out a way to get rid of the units in the tech tree and
> tested it on the marine and the anti-tank gun. You can do this by setting
> ObsoleteTech to TECH_AGRICULTURE and PrereqTech to NULL. This works by
> letting the unit be constructable without a tech (and not be shown in the
> tech tree) while getting obsoleted from the start of the game
> (TECH_AGRICULTURE).
> 
> See 1d1581bhttps://github.com/Thalassicus/cep-bnw/commit/1d1581b3ba1df178f4c780106564de0ad7531f83
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Thalassicus/cep-bnw/issues/135#issuecomment-33336021
> .

## 

"There are 10 types of people in the world: those who understand binary,
and those who don't."

**Comment by stackpoint** [comment]
I haven't done any work on the conquistador so you can handle everything regarding that.

**Comment by stackpoint** [comment]
@GrantSP fixed it here: https://github.com/Thalassicus/cep-bnw/commit/03fd14e30a0544ae0d2f6c1824c17fb911dcc62c
