### ISSUE TITLE
v3.13 Korea has no science on farms

### ISSUE THREAD

**Issue by WilsontheRed** [Thalassicus/cep-bnw#137]
Started 3 games as Korea, clearing the cache before the 3rd.  The worked farm did not generate 2 science.

**Comment by skodkim** [comment]
Looking at the files shows that it is assigned. However there may be a syntax error.

Another thing is that it seems that the trait gives +2 production to scientists and +2 science to engineers, which seem unintended. Can you confirm this?

\Skodkim

**Comment by stackpoint** [comment]
See: http://forums.civfanatics.com/showthread.php?t=518797 and https://github.com/Thalassicus/cep-bnw/issues/135

**Comment by skodkim** [comment]
I can comfirm that that this is because of https://github.com/Thalassicus/cep-bnw/issues/135

There's is however also another issue where Korea's trait unintentionally gives 2 production to scientists and +2 science to engineers. This will be fixed in the next version.

\Skodkim
