### ISSUE TITLE
v3.13 -- Iron for Roman cities overrides pre-existing luxuries

### ISSUE THREAD

**Issue by wguldin** [Thalassicus/cep-bnw#138]
This may be desired behavior, but on a game as Rome I founded a city on gems and the gems were erased, replaced by the iron guaranteed by the UA. Seems like a bug to me, but not sure if that feature will allow a luxury on the same tile as the iron.

**Comment by stackpoint** [comment]
This uses the same mechanic as the Indonesian UA to grant resources under the city. It will overwrite the existing resources under the city to do so. Not sure what we should do about it.

**Comment by wguldin** [comment]
Could the bonus be moved to the capital alone? 3-5 iron available right away? I feel like you are more likely to found an expansion on a luxury, for the instant happiness while expanding, then you are your capital.

It also lowers the chance that this could impact your game in a not fun way (5 chances of it happening in a game to one chance).

**Comment by stackpoint** [comment]
You should bring this up for discussion in the Leaders thread on civfanatics.
