### ISSUE TITLE
Jaguar upgrades to spearman?

### ISSUE THREAD

**Issue by ShmooDude** [Thalassicus/cep-bnw#140]
Shouldn't it upgrade to swordsman as its a soldier (warrior)?

**Comment by stackpoint** [comment]
UU Warriors upgrade into spearmen in order to avoid them encountering the iron requirement that swordmen have. I may add a later obsolete date (Metal Casting) for them like we did for scouts. For further discussion on the topic, you should bring this up in the main forums for a wider audience.
