### ISSUE TITLE
[3.13] Marketplace and East India do not give trade gold

### ISSUE THREAD

**Issue by skodkim** [Thalassicus/cep-bnw#145]
Marketplace and East India does not increase gold from trade routes (while the caranesary does).

Tested using 3.13 and only Ingame Editor enabled (saw it it another game using other mods and decided to test).

The city shown below just built a Marketplace, Before it was also +2 gold from trade routes.

\Skodkim

![civ5screen0013](https://f.cloud.github.com/assets/6018459/1942093/b1f8fcce-7f93-11e3-9eef-eca7b4a5e34b.jpg)

**Comment by GrantSP** [comment]
When was this change supposed to happen? Apart from the TXT change for the Market I can't see any code implemented for it or even when it was discussed to be a good idea.

If it is supposed to be a change that is to happen we can change the **TradeRouteLandGoldBonus** for those buildings to 200, the same as the Caravansary.

**Comment by skodkim** [comment]
I'm not in front of my gaming computer right now but I'm pretty sure the marketplace and East India Company should give gold from trade routes - As I recall it this is default BNW but I may be wrong. I', pretty sure t also says they do this in the (automatic) description of the buildings. Don't you agree?

Anyway I looked in the xml/sql and it seems to be implemented ok.

To test it I set up a scenario map with one AI city surrounded by three of mine (same distance). Then I made sure the cities had different combinations of the buildings in question and tried establishing trade routes. The conclusion was the buildings had no trade route related effect on gold. The test was however made unnecessarily difficult by this bug: https://github.com/Thalassicus/cep-bnw/issues/121

I suspect this may be yet another bug concerning the yield library.

\Skodkim

**Comment by GrantSP** [comment]
Yeah I'm still on holidays at the moment and have no access to my game system. I think you may right about the yield library though, after my last comment on #121 I did some looking and found it was happening most of the time, I just wasn't seeing it.
I get back next week and will have a look myself. 
Glad to see you making inroads into these things. 
Well done.

**Comment by skodkim** [comment]
May be related to this issue: https://github.com/Thalassicus/cep-bnw/issues/179

\Skodkim

**Comment by stackpoint** [comment]
Probably not. If the vanilla BNW caravansary can increase trade route gold then I don't see why we'd need any YieldLibrary functions to do so too.

**Comment by skodkim** [comment]
The Marketplace and East India Company uses the _TradeRouteRecipientBonus_ and _TradeRouteTargetBonus_ fields while the caravansary uses the _TradeRouteLandGoldBonus_ field

Just tested with new features build and the Marketplace and East India Company still does not give additional gold from trade routes while the caravansary does.

\Skodkim

**Comment by GrantSP** [comment]
What about the other buildings that use _TradeRouteRecipientBonus_ & _TradeRouteTargetBonus_ like the Colossus, Hanse, Bank, Satrap's Court or Bazaar?
Do they get the increase?

I'm about to do some testing now.

**Comment by GrantSP** [comment]
Is this still current? I just tried a number of games with the unique variants of the market and all seemed to do as expected. The East India Company also seemed to give the bonus it said.

**Comment by skodkim** [comment]
Great if it's working. I haven't tested for a couple of weeks but the conclusion there was that it didn't work. Could it be yield library activation?

On 2. mar. 2014 06.13.38 CET, GrantSP notifications@github.com wrote:

> Is this still current? I just tried a number of games with the unique
> variants of the market and all seemed to do as expected. The East India
> Company also seemed to give the bonus it said.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Thalassicus/cep-bnw/issues/145#issuecomment-36446425

## 

Sendt fra min Android telefon med K-9 Mail. Undskyld hvis jeg er lidt kortfattet.

**Comment by GrantSP** [comment]
I've been using  3.14.1 for all my tests, so I would have to say no.
Yield library hasn't been activated in this version

**Comment by skodkim** [comment]
Hmm, not in front of my computer today so I have no way of testing but I've tested this several times. Are you sure your gold output is changing after building them and that trade routes gets boosts (that it's not just display)?

On 2. mar. 2014 07.29.32 CET, GrantSP notifications@github.com wrote:

> I've been using  3.14.1 for all my tests, so I would have to say no.
> Yield library hasn't been activated in this version
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Thalassicus/cep-bnw/issues/145#issuecomment-36447531

## 

Sendt fra min Android telefon med K-9 Mail. Undskyld hvis jeg er lidt kortfattet.

**Comment by GrantSP** [comment]
Not sure what you mean by 'being just a display thing'.

How did you test it to verify that?

**Comment by skodkim** [comment]
I think the tool tips displayed the bonus but after turnover I could tell that I didn't get increased gold output after building the buildings.

When looking at trade route yields they were the same (roughly) for cities with and without the buildings do in that case the display actually indicated it didn't work.

I'd certainly like to test this again before you close the issue but I'm happy if it works.

On 2. mar. 2014 07.39.21 CET, GrantSP notifications@github.com wrote:

> Not sure what you mean by 'being just a display thing'.
> 
> How did you test it to verify that?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Thalassicus/cep-bnw/issues/145#issuecomment-36447672

## 

Sendt fra min Android telefon med K-9 Mail. Undskyld hvis jeg er lidt kortfattet.

**Comment by GrantSP** [comment]
Okay, I'm doing another test with just a simple map and one city.

I've got 2 caravans giving 2 Gold each.
The Gold Income in the CityView shows 11 Gold, 7 from buildings & terrain and 4 from the trade.

Next turn I build the bazaar (Arabic Market variant)
The Gold now shows an extra 6(rounded down) 25% for the modifier and 2 extra for each trade.

Okay a couple of turns later and the values are:
3 Gold from terrain, 6 from Buildings and 5.21 from trade plus the 25%
I'm just about to give the East India Company.

Now the city gets an extra 5 Gold into the treasury, 4 +25% from the Company plus,
the trade from the city is 5 Gold 4 + 25%.
The description seems to imply it is 4 Gold for **each** trade route, perhaps it is only a 4 Gold for trade out of the city, taken as a whole, not each route.

**Comment by GrantSP** [comment]
Looking closer at the descriptions and the code of all the buildings that use either:
_TradeRouteRecipientBonus_ &_TradeRouteTargetBonus_
compared to those that have:
_TradeRouteLandGoldBonus_ or _TradeRouteSeaGoldBonus_
I think that is the result.

The recipient & target bonuses are just a per city rate whereas the LandGold or SeaGold bonuses are on each route.

**Comment by GrantSP** [comment]
So it would seem your opening post is indeed correct. Only our understanding of the results needed to be enhanced.

**Comment by skodkim** [comment]
Sorry if I'm being daft here but I don't understand how the buildins work from your description.

Could you elaborate?

**Comment by GrantSP** [comment]
The buildings with TradeRouteRecipientBonus  or TradeRouteSent donation get
the 4 gold for each trade route. It is just for each city. So if city has 4
trades to only 2 cities it gets only 2 \* 4 gold.
But if 5 cities trade with it it will get 5 \* 4 gold from them.

Buildings like caravansary get gold for each route.
So 1 city with 7 trade routes to anywhere get the bonus for each route.

East India Company is designed to attract as many different routes as
possible.

**Comment by skodkim** [comment]
Just tested this again today and I'm still not sure how it works:
- If I try to create a new trade route the output is shown as the same (with some modifiers for e.g, resources) for cities with/without a marketplace
- If I create a marketplace in a city with a trade route I don't seem to get +4 gold from the trade route (based on top panel)

\Skodkim
