### ISSUE TITLE
[3.13] Boudicca's Drudic Lore bonus reverts to Vanilla after researching Pottery

### ISSUE THREAD

**Issue by QuinRiva** [Thalassicus/cep-bnw#146]
In version 3.13, the Druidic Lore bonus seems to break once pottery is researched.  It works fine until pottery is researched, and then reverts to the vanilla +1 faith if adjacent to a Forest/Jungle.

**Comment by GrantSP** [comment]
The code has not changed for this trait since version 3.7. Are you sure you are not just seeing the change from an **unimproved** tile to an **improved** tile?

**Comment by stackpoint** [comment]
Is this an issue? Anybody else able to reproduce this?
