### ISSUE TITLE
(V3.13) Mercenary Army doesn't spawn landsknechts

### ISSUE THREAD

**Issue by pastuch** [Thalassicus/cep-bnw#147]
In my last 2 games when I selected Mercenary Army the landsknechts did not spawn. This also happened to me in 3.12.2.

In 3.13 I am playing as Dido. Fresh install of civ, no other mods. Communitas Map.

**Comment by stackpoint** [comment]
Should be fixed here: https://github.com/Thalassicus/cep-bnw/commit/f0b26112bcf6382b830a2787f5506bf49d7b73b7
