### ISSUE TITLE
Hoplites don't gain phalanx promotion (as stated on promotion list)

### ISSUE THREAD

**Issue by wguldin** [Thalassicus/cep-bnw#148]
When attacking barbarian brutes (soldier category units), Greek Hoplites don't appear to have the Phalanx promotion, as indicated on the unit promotions list when the unit is selected.

**Comment by stackpoint** [comment]
It looks like the soldier line has been renamed(?) back into UNITCOMBAT_MELEE? I'm not sure but I think the idea is that it should get the bonus vs mounted and melee, so I'll add the bonus.

**Comment by stackpoint** [comment]
Fixed here: https://github.com/Thalassicus/cep-bnw/commit/7748fd12368380279f416c467fa9b884f410ccae

Now that I think of it, this was an old change made by me. I can't find the specific issue but I misread somewhere that the bonus was ONLY supposed to be +50% vs mounted when the bonus was previously only +50% vs melee. Well it should be fixed now either way.
