### ISSUE TITLE
Babylon gains one scientist at writing (Civilization UA says 2 are granted).

### ISSUE THREAD

**Issue by wguldin** [Thalassicus/cep-bnw#149]
Playing as Babylon, only one great scientist was received after writing, instead of two, as the civ UA text says.

**Comment by GrantSP** [comment]
Update your system, this was fixed a few commits ago.

**Comment by stackpoint** [comment]
The download hasn't been updated in a week.

**Comment by GrantSP** [comment]
Ahh...

That would be a problem then.
Is there a big release that is delaying the process?

**Comment by stackpoint** [comment]
Not that I know of, it's just that Thal hasn't been around this week and I don't feel comfortable making releases myself. But Thal needs to update the repo with 3.13 so I can address some of the bugs with that release.

**Comment by GrantSP** [comment]
Fair enough.

**Comment by skodkim** [comment]
I'm writing a PM to ExpiredReign right now (think he used to make releases), It's high time we had a release of 3.13.1 - especially so we can make a hotfix of https://github.com/Thalassicus/cep-bnw/issues/135. Right now people are A) playing with half bugged leaders and B) making a lot of error reports that have already been fixed.

\Skodkim

**Comment by GrantSP** [comment]
Just in case it isn't clear, I'm ExpiredReign. ;)

I'm still on holidays and away from game system. When I get back on Monday
I will be able to get back in to it.

**Comment by skodkim** [comment]
You are? Well you just got a PM at Civfanatics then :-)

\Skodkim

**Comment by stackpoint** [comment]
I only see @GrantSP :+1:

**Comment by skodkim** [comment]
Sorry, I don't understand you here. AFAIK you aren't able to send PM's using Github?

Anyway the message I just posted:

---

Hi ExpiredReign (/GrantSP  )

Welcome back! As I recall you can make CEP releases, right?

It's high time we had a release of 3.13.1 and Thal is nowhere to be seen.

Especially we need a hotfix of the conquistador bug. Right now people are A) playing with half bugged leaders and B) making a lot of error reports that have already been fixed. There's also a lot of other fixes.

I've posted a few files in the conquistador thread (issue 135) that fixes the loading problem of the sql file and also removes a copy of the conquistador unit that seems to be a dummy unit. There may be a better solution but we haven't been able to come up with one.

\Skodkim

**Comment by stackpoint** [comment]
Well if @Thalassicus doesn't pop back in by Monday I'm sure @GrantSP can manage something.

**Comment by GrantSP** [comment]
Guys, I (GrantSP aka ExpiredReign) am just another hacker like you.
The releases are just compiled mods from ModBuddy all zipped up into a
package and uploaded to GitHub. Nothing special. If I can do it you
certainly can. I am quite confident in the skills you have displayed.

Yes I can do it when I get back but there really isn't anything stopping
you from doing it. Thalassicus wont mind. I certainly don't.

Just to clear up any confusion further as to the different names. I was on
GitHub regarding a number of other projects and at first carried my
Civfanatics user name after I joined Thal in this project. My early commits
were under ExpiredReign but after awhile I just dropped the change and
reverted to using the same GitHub name. If I could do the same on
Civfanatics I probably would. It was just a quirky response to my being
pensioned off, and I went through a phase of feeling "past my use by date".
Now I have something I can be invested in that name seems out of place.

Anyway, probably too much information there. Apologies for that.
What it all boils down to is: we all can make commits and upload releases
if needed.
Skodkim, if you are having difficulties with the cloned repos and merges
perhaps we should look at adding you as a collaborator? It makes it easier
and doesn't involve any more commitment than you are already giving. I'll
Skype Thal and ask him.

On 21 January 2014 18:50, stackpointer notifications@github.com wrote:

> Well if @Thalassicus https://github.com/Thalassicus doesn't pop back in
> by Monday I'm sure @GrantSP https://github.com/GrantSP can manage
> something.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Thalassicus/cep-bnw/issues/149#issuecomment-32827487
> .

## 

"There are 10 types of people in the world: those who understand binary,
and those who don't."

**Comment by skodkim** [comment]
@GrantSP It would be great if you would Skype Thal as I'm finding the whole merge thing tough to handle :-)

\Skodkim
