### ISSUE TITLE
[Wonder] MT_Plot.lua:76: attempt to call global 'Vector2' (a nil value)

### ISSUE THREAD

**Issue by GrantSP** [Thalassicus/cep-bnw#15]
Had this ERROR message popup in my log. It always followed a WARN notification about my having built Machu Pichu in Akkad (this city only has one mountain plot within its boundaries)

All other WARN messages about built buildings in that city passed without another ERROR following. Additionally all the other WARN messages about built buildings only happen once and are never sent again, the WARN message about Machu Pichu happens twice each turn.

**Comment by stackpoint** [comment]
Could you post the complete warning too? You can use the following for formatting: https://help.github.com/articles/github-flavored-markdown#fenced-code-blocks

**Comment by GrantSP** [comment]
It was just a runtime error in:
Communitas AI and Tools (v 3)\Tools\ClassMethods\MT_Plot.lua:76:
attempt to call global 'Vector2' (a nil value)

Nothing else was shown besides that.

On 19/11/2013, stackpointer notifications@github.com wrote:

> Could you post the complete warning too? You can use the following for
> formatting:
> https://help.github.com/articles/github-flavored-markdown#fenced-code-blocks
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Thalassicus/cep-bnw/issues/15#issuecomment-28760899

## 

"There are 10 types of people in the world: those who understand
binary, and those who don't."

**Comment by stackpoint** [comment]
I was referring to this: "It always followed a WARN notification about my having built Machu Pichu in Akkad (this city only has one mountain plot within its boundaries)"

**Comment by GrantSP** [comment]
Ahh, sorry. Those sort of messages are simply an internal notification of a
building having completed its construction. It will be the same sort of
message for whatever building is built. They are not so much of a WARNING,
more of an INFO that is mislabeled.

They take the form of:
MT_Initialize: WARN   Turn 187 Nebuchadnezzar II built BUILDING_MACHU_PICHU
in Akkad

Except in this case, I, Nebuchadnezzar didn't finish it on turn 187, it was
turn 142 and it keeps logging it every turn.
Only happens with the BUILDING_MACHU_PICHU.

On 19 November 2013 13:52, stackpointer notifications@github.com wrote:

> I was referring to this: "It always followed a WARN notification about my
> having built Machu Pichu in Akkad (this city only has one mountain plot
> within its boundaries)"
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Thalassicus/cep-bnw/issues/15#issuecomment-28761120
> .

## 

"There are 10 types of people in the world: those who understand binary,
and those who don't."

**Comment by stackpoint** [comment]
According to this: http://modiki.civfanatics.com/index.php/Vector2_%28Civ5_API%29 MT_Plot.lua needs the following:

``` lua
include("FLuaVector.lua")
```

I'm not sure if this will fix it though, the problems seems a little bit more extensive than that. Additionally this is related to the wonder changes in the wonders branch.

**Comment by GrantSP** [comment]
FluaVector.lua is a core file found in the original game.

It is possible I made a build using the Wonders branch, though after your
post about some stability issues I was pretty sure I used the branch with
you stable commits.

On 19 November 2013 14:54, stackpointer notifications@github.com wrote:

> According to this:
> http://modiki.civfanatics.com/index.php/Vector2_%28Civ5_API%29MT_Plot.lua needs the following:
> 
> include("FLuaVector.lua")
> 
> I'm not sure if this will fix it though. Additionally this is related to
> the wonder changes in the wonders branch.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Thalassicus/cep-bnw/issues/15#issuecomment-28763226
> .

## 

"There are 10 types of people in the world: those who understand binary,
and those who don't."

**Comment by stackpoint** [comment]
Apparently my build wasn't that stable since it included the wonders changes. I thought I had excluded it but when I double checked it hadn't. So it was my fault.

**Comment by GrantSP** [comment]
That's ok. I'll just do another build now with the stable branch we have
now.
At least it can be viewed as a 'learning experience'.

thanks.

So you'll close the issue then?

On 19 November 2013 15:04, stackpointer notifications@github.com wrote:

> Apparently my build wasn't that stable since it included the wonders
> changes. I thought I had excluded it but when I double checked it hadn't.
> So it was my fault.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Thalassicus/cep-bnw/issues/15#issuecomment-28763561
> .

## 

"There are 10 types of people in the world: those who understand binary,
and those who don't."

**Comment by stackpoint** [comment]
I'll close it for now but this will probably come up in the future.

**Comment by Thalassicus** [comment]
I'm going to reopen because this part shouldn't be happening... it sounds like something else is going on:

> Except in this case, I, Nebuchadnezzar didn't finish it on turn 187, it was turn 142 and it keeps logging it every turn. Only happens with the BUILDING_MACHU_PICHU.

**Comment by stackpoint** [comment]
Okay, so I ran a 150 turn test on quick with the wonders branch to see if any errors logged with Machu Pichu. It seems like my "fix" worked as the original MT_Plot.lua error does not occur and the mountain tile does gain the described +5 yields.

Correct me if I'm wrong, but isn't the event that triggers when a new building is detected in a city running over and over again because the function doesn't have a chance to clear it from the queue because the code errors? That's why the log had both the error and warn logged one after the other.

Below is the code in the build Grant was using to log the buildings:

``` lua
log:Warn("%s built %s in %s", player:GetName(), buildingInfo.Type, city:GetName())
```

**Comment by Thalassicus** [comment]
Where was that line of code? I'm not finding it in a search of Cat.

**Comment by stackpoint** [comment]
I believe it has been deleted in one of the branch merges but I placed it in the BuildingCreated function in CAT\Tools\Cat_Events.lua line 274.

**Comment by stackpoint** [comment]
This hasn't come up in a while so I'm closing it.
