### ISSUE TITLE
Unit that is finished after upgrade is researched doesn't get built

### ISSUE THREAD

**Issue by wguldin** [Thalassicus/cep-bnw#152]
On 3.13

A bad title, but what happened was that I was building a horsemen while researching chivalry. Chivalry was finished the turn before the horsemen was done. The next turn, it said the horsemen had been built, but no unit appeared.

**Comment by stackpoint** [comment]
This might just be a result of the production getting shifted into the more advanced unit (lancers?) which is a vanilla function. Did you get the production in the horseman upgrade?

**Comment by wguldin** [comment]
Sorry, I should've clarified that. I believe the vanilla behavior is for the production to transfer to the upgraded unit, and the city would start building the new unit. Instead, I was prompted to choose production in my city, and the city screen said the horseman unit had been completed, even though it wasn't there. The upgrade, a knight, had no production towards it, either.

**Comment by stackpoint** [comment]
Thanks for the clarification. We will look into this.

**Comment by GrantSP** [comment]
I'm just thinking out loud here. What is state of your horse  numbers?
Do you have ample supply?

**Comment by wguldin** [comment]
If I remember right, I might've only had one available. That could explain it. Doesn't some weird resource toggling happen on unit upgrades?

**Comment by GrantSP** [comment]
That's what I  was thinking, maybe the horseman was produced and then there was a crossover of routines. 
Normally the knight would be cloned sending you into negative resources and then the original unit is deleted restoring your supply. 
It might be s case of the different routines happening out of sequence. 
Not sure if we can replicate that, let alone fix it.
Keep an eye on it, maybe it is something else and we can do something.
