### ISSUE TITLE
Which version to build?

### ISSUE THREAD

**Issue by ghost** [Thalassicus/cep-bnw#154]
It looks like 3.13 is based off the new features branch and it's updates are not reflected in the stable branch.  Is this correct?

Since 3.13 there have been edits to both the new features and stable branch.  It also appears that none of the edits were done to both branches.

So my question is how do I build a new version for myself that incorporates all the changes since and including 3.13?

**Comment by GrantSP** [comment]
Assuming you have the GitHub app (though you could equally do this with the commandline) you would need to merge the two branches and then do a build of the resultant branch:

New-features --> Stable ==> Stable (with New features edits overriding the Stable code)
or
Stable --> New-features ==> New-features (with the Stable code as dominant)

With the app click the icon in the top right with the branch label and choose "manage/merge"
On the page that opens drag the branch labels down to the placeholders at the bottom of the page and then click "merge".

I will be building a new release on Monday using the Stable branch as a base if you want to wait.
I would suggest you do wait as the new-features branch, as well as having 1 or 2 bugs, is primarily for testing new concepts or ideas that may not be implemented into the stable branch. e.g @stackpoint is at the moment doing some testing with AIFlavors that may or may not work. If you add those in then you will have a significantly different mod to the rest of the users.

**Comment by ghost** [comment]
So was 3.13 accidentally built out of the new features branch?  Will your realse have the 3.13 updates?

**Comment by GrantSP** [comment]
I can't say definitively as to whether the latest release was **accidentally** based on the new-features branch. What I can say is when I get back from holidays the code that is there in the **stable** branch will be compiled into the next release.

**Comment by ghost** [comment]
Sounds good, hopefully I will become a little more active in the next few weeks as I should have some free time.

**Comment by stackpoint** [comment]
What you could do is make a fork of the repo and merge both branches together then build off them.

**Comment by GrantSP** [comment]
Not having actually _played_ with the latest release, how much stuff is different between the two?
Are there any **features** that should make there way into the latest?

**Comment by ghost** [comment]
According to the release notes 3.13 seemed to have a good bit of tweaks.

**Comment by stackpoint** [comment]
As it is now, we should merge both branches together before I commit my handicap and flavor modifications.

**Comment by GrantSP** [comment]
Then that is what we will do. ;)

**Comment by stackpoint** [comment]
I'm doing it right now.

**Comment by stackpoint** [comment]
Merge should be finished. When Monday rolls around you can use the changelog from draft release I made here: https://github.com/Thalassicus/cep-bnw/releases/

**Comment by GrantSP** [comment]
Bring on Monday.
I get home, its Australia Day holiday and hopefully a new release to play with. Happy days.
As much as I like vacations, there is something reassuring about home routines. ;)

**Comment by ghost** [comment]
I like it when a plan comes together!
