### ISSUE TITLE
Runtime error: CEAI_Events.lua:296: attempt to perform arithmetic on field 'Mult' (a nil value)

### ISSUE THREAD

**Issue by GrantSP** [Thalassicus/cep-bnw#16]
In the same game as issue 15, this log error occurred early, TURN 99 - 139 and then it was replaced by a similar ERROR in the same file at line:302.
It continued for only ten turns and was never logged again.

**Comment by stackpoint** [comment]
Looks like Info.Mult is called when Info only has FlavorType, Num, and Promos to call. I renamed Num to Mult to keep the more descriptive variable name. I believe this will fix the problem.
