### ISSUE TITLE
3.14 Can't produce(closed)

### ISSUE THREAD

**Issue by wolverine2112** [Thalassicus/cep-bnw#162]
Can't choose a production option at beginning of game.

**Comment by ydhuang28** [comment]
I had this problem when I enabled other mods alongside cep; I don't think cep is compatible with some other mods.
This might be the problem.

**Comment by stackpoint** [comment]
Can't replicate this. Are you using CSD?

**Comment by stackpoint** [comment]
If you are, please refer to the release notes [here](https://github.com/Thalassicus/cep-bnw/releases/tag/v3.14) for instructions.

> City-State Diplomacy Mod (v14 - v15) should be compatible with CEP. Set the USING_CSD option in CAT\Cat_Options.sql.

**Comment by skodkim** [comment]
Perhaps you should look here: https://github.com/Thalassicus/cep-bnw/issues/161

\Skodkim

**Comment by wolverine2112** [comment]
please close...ydhuang28 was correct it was another mod. sorry.
