### ISSUE TITLE
Policy updates

### ISSUE THREAD

**Issue by Thalassicus** [Thalassicus/cep-bnw#167]
I'd like to get started on policy updates based on feedback in the [Strongest and Weakest Policies thread](http://forums.civfanatics.com/showthread.php?t=517804). Several weak policies are stronger, and some strong policies are weaker. If you have time, pick some of these updates to do in the new-features branch of the project.

Update these for each policy we alter:
- Data in Ceg/Policies folder
- Good For priorities [https://docs.google.com/spreadsheet/ccc?key=0Ap8Ehya83q19dFpPbnNDMFhmM2I2YjVXR04tQWN0V2c&usp=drive_web#gid=8](spreadsheet)
- Policy text spreadsheet

Tradition
- [x] Replace Ceremonial Rites (free culture buildings) with Mentors (science bonus)
  "[ICON_SCIENCE] +5 Science.[NEWLINE][ICON_SCIENCE] +5% Science per science building."
- [x] Landed Elite: increased growth bonus. [50% was 25%](GrantSP)
- [ ] Monarchy: new effect - "[ICON_CAPITAL] The capital gains 1 specialist slot of each type."

Liberty
- [x] Citizenship: gives only 1 free worker (was 2). (GrantSP)
- [x] Republic: also improves defense buildings.
  "[ICON_PRODUCTION] +1 Production per City Defense Building." (Skodkim)

Honor
- [x] Spoils of War: increased gold from combat. [4 gold per strength, was 2]
- [x] Military Caste: increased culture per garrison. [3, was 2]
- [x] Gladiators: gives 2 free defense units (in addition to arena bonus). (Skodkim) 
- [x] Professional Army: Helps produce all types of military units, not just melee. (Skodkim)
- [x] Discipline: Improves strength of all units, not just melee. (Skodkim)
- [x] Finisher: in addition to existing bonus, " [ICON_MOVES] Purchased units can move immediately. "

Piety
- [x] Opener: increased faith bonus, reduced happiness bonus. [2 faith 4 happiness, was 1f 5h]
- [x] Unity: increased happiness bonus. [-50% golden age cost, was -25%]
- [x] Meditation: increased faith cost bonus. [-33% was -20%]
- [x] Charity: gives some flat gold (in addition to the percent bonus). [+2g per temple]
- [x] Finisher: removed holy site bonus.

Patronage
- [x] Cultural Diplomacy: in addition to existing bonuses, "[ICON_GREAT_PERSON] +10% creation rate for Great People." (GrantSP)

Aesthetics
- [x] Flourishing of Arts: also speeds production of archaeologists (in addition to culture bonus). [+50%](GrantSP)
- [x] Ethics: increased tourism bonuses. [25% was 15%](GrantSP)

Wealth
- [x] Opener: reduced gold and production bonuses per city. [10% was 15%]
- [x] Caravans: increased gold per trade route. [3 per route, was 2]
- [x] Entrepreneurship: also gives a free Great Merchant.
- [x] Protectionism: no longer gives unintended national production & gold modifiers.
- [x] Maritime Infrastructure: increased production and gold bonuses. [4, was 2]

Exploration
- [x] Pioneer Spirit now improves civilians and city connections.
  "[ICON_MOVES] +1 movement for civilians.[NEWLINE]
  [ICON_GOLD] Civilians cost no maintenance.[NEWLINE]
  [ICON_GOLD] -50% cost for roads.[NEWLINE]
  [ICON_PRODUCTION] +100% production for building harbors."
- [x] Colonization now helps settle cities.
  "[ICON_CITIZEN] Cities start with 2 population.[NEWLINE][ICON_TEAM_2] 2 Settlers, 2 Workers, and 2 Defense Units appear at the Capital." (Skodkim)

Knowledge
- [x] Counterintelligence: also speeds production of espionage buildings, which give extra happiness.
  "[ICON_SPY] +25% chance to catch enemy spies.[NEWLINE][ICON_SPY] -25% enemy spy effectiveness.[NEWLINE][ICON_PRODUCTION] +100% production for constructing Espionage Buildings.[NEWLINE][ICON_HAPPINESS_1] +2 Happiness per Espionage Building."
- [x] Secularism: increased science bonus from specialists. [4, was 2](GrantSP)

**Comment by GrantSP** [comment]
I've a question about Landed Elite.
The text says it gives +2 Food per city but the code is using the **Policy_CapitalYieldChanges**.
Shouldn't that be the **Policy_CityYieldChanges**?
If so does that mean we don't need to adjust the +25% on the **CityGrowthMod** or the **CapitalGrowthMod**?

**Comment by stackpoint** [comment]
It looks like it's using Policy_CityYieldChanges to me. [CEP_Tradition.xml](https://github.com/Thalassicus/cep-bnw/blob/stable/Ceg/Ceg/Policies/Trees/CEP_Tradition.xml) line 72-82.

Not sure how much more food he wants Landed Elite to grant. It doesn't look like there was much discussion on it needing improvement in the thread: http://forums.civfanatics.com/search.php?searchid=2453411

**Comment by GrantSP** [comment]
Damn, I was looking in a vanilla database instead of the modded and didn't check the code itself. It is of course **Policy_CityYieldChanges**.
Still the other 2 tags are there to change. **CapitalGrowthMod** is 0  was 10 and **CityGrowthMod** is 25 was 0.

Looks like we made the Capital grow less and other cities grow more. What is the desired balance? I'm not sure? The forum says nothing specific about Landed Elite.

**Comment by GrantSP** [comment]
Flourishing of Arts: Haven't we already got faster archaeologist production? 100% boost to production of these units. Or is this another code fix that needs some lua to run it?

**Comment by GrantSP** [comment]
Knowledge: Counterintelligence. The forum speaks of maybe adding more spies. Can't we try and add them here?
I can see we have added an **ExtraSpies** column to the **Policies** table.

**Comment by GrantSP** [comment]
Knowledge: Secularism. Wouldn't an increase in Great Scientist rate go well here?

**Comment by GrantSP** [comment]
Diplomacy: Increased spy tech steal rates
About the only place I can think of to give extra spies is the opening bonuses from taking Knowledge.
I'm 100% convinced though that if you are taking Knowledge your spies will not be able to steal anything. You should by this time be either the leading science power or very close to becoming such.

**Comment by AnastaseAlex** [comment]
I think Spies and related benefits should be incorporated in the ideologies, also giving different bonuses to each ideology when they use spies (autocracy +X% bonus strength to units fighting near a city you have a spy in, freedom +X tourism per spy in an enemy city, order +Happyness adn production per spy in your own cities?)

**Comment by GrantSP** [comment]
I've made the Landed Elite have a Yield of food per population in the capital.
The vanilla capital was 2 Food I have now made it 2 Food per 4 population or 50% of a Food yield per pop. This is in addition to the existing modded yield of 2 Food per city.

Wasn't really sure of the balancing here, open to any suggestions.

**Comment by stackpoint** [comment]
That's pretty excessive. That would mean that each citizen would require only 1 food in the capital. Landed Elite as it is now seems fine to me.

**Comment by GrantSP** [comment]
Halve it?
There is to be more food according to this issue.

**Comment by stackpoint** [comment]
I misread what Grant wrote before. 1 food per 2 pop doesn't halve the food requirements in the capital.

With Grant's latest commit, landed elite now provides 1/8 (1 food per 4 pop) of the food required in the capital.

**Comment by skodkim** [comment]
Honor Finisher: It don't think its possible to give purchased units the ability to move immediately without using dll as the field MoveAfterPurchase in the units table does not work without dll modifications (Whoward has a mod for this).

\Skodkim

**Comment by GrantSP** [comment]
I think it may be easy than it first appears.
Each unit has a tag **MoveAfterPurchase** and possibly **Immobile**.
If we write code that will set the units to **MoveAfterPurchase=1** I'm pretty sure that will do what we want.

**Comment by skodkim** [comment]
That was what I was trying to say: The MoveAfterPurchase tag does not work without dll (according to Whowards dll mod).

\Skodkim

**Comment by GrantSP** [comment]
Yes, sorry. I didn't read your comment properly.

**Comment by GrantSP** [comment]
I just tried this code and it does indeed give a unit that can move after purchase.

UPDATE Units SET MoveAfterPurchase=1 WHERE Combat>0 AND Immobile=0;

**Comment by skodkim** [comment]
It does? Seems Whowards code is unneeded then.

And on the bright side you've almost made a policy change :smile: 

\Skodkim

**Comment by skodkim** [comment]
Professional army already gave a production modifier for all unit types So I'll just update the spread sheet.

I did however find a bug: It also had a 50% production modifier for BUILDINGCLASS_BARRACKS, BUILDINGCLASS_ARMORY and BUILDINGCLASS_MILITARY ACADEMY. This was default BNW behaviour, which had not been disabled.

\Skodkim

**Comment by skodkim** [comment]
Updated Discipline. There was a mismatch between text key and which units it affected in old build. In new it affects all unit_combat types. Spread sheet has been updated accourding to this.

\Skodkim

**Comment by skodkim** [comment]
GrantSP: I agree that Flourishing of Arts already has a 100% archaeologist production modifier. I think I tested this at one point and concluded that it worked.

\Skodkim

**Comment by EricB1** [comment]
Hey guys, I'd like to join the modding team if that's okay.

**Comment by skodkim** [comment]
Hi EricB.

That sound great - you're welcome! Have you looked at the collaboration guide: https://github.com/Thalassicus/cep-bnw/wiki/Collaboration-Guide

If you feel like it take a look at some of current issues, e.g. the policy updates in this thread, and work on it.

\Skodkim

**Comment by stackpoint** [comment]
You are always welcome to help. You can PM any of us on the forums if you want our skype information.

**Comment by EricB1** [comment]
So I made a few changes tweaking the Wealth tree.

Lowered the gold and production from the opener from 15% to 10%
Added a free great merchant to Entrepreneurship
Added Harbors getting +2 gold to Maritime Infrastructure and corrected a text error.
Increased gold from trade routes in Caravans from +2 to +3
Removed +10% gold and production from Protectionism, retaining the rest of the policy.
Left Trade Unions as is.
Fixed a typo in the text for the finisher.

If you don't like the changes that's fine.  I tried to stick to modest tweaks.

**Comment by stackpoint** [comment]
@EricB1, I know from your posts on the forums that your changes are well reasoned but for the most part, @Thalassicus handles the changes that has to deal with game balance so I can't say whether or not your changes will be merged.

**Comment by EricB1** [comment]
I undid the changes because it was in the wrong branch.  I wasn't aware of the new features branch vs. the stable branch.  If you don't really want me to make any changes then I won't.  Just was trying to make the game more playable, so I targeted some really obvious issues that are out of whack that there is pretty widespread agreement about.

**Comment by stackpoint** [comment]
From what I've seen, I think your changes will help the balance however I don't participate in the game balancing threads on the forums and I generally don't make any changes regarding balance either. I was just informing you that @Thalassicus will most likely be the one to review and merge your changes and that may take a while depending on when he has more time to be active on the project.

**Comment by EricB1** [comment]
It seems like balance changes are the biggest need (in my view anyways).  Many policies are imbalanced.  Some leaders and their civilizations are perennially lagging behind and doormats.  Some beliefs are always good to take.  Others are always bad.  If Thal doesn't want us to touch these types of things, then what can I help with?  I'd like to be engaged, but really don't have a direction of what to be working on if minor changes to make the game more enjoyable (that can be easily done) are off-limits.

**Comment by EricB1** [comment]
We've been discussing the Piety opener in the forums.  Ahriman suggested +1 culture, +1 faith, and double production for shrines.  I think that seems pretty balanced.  The other 3 starting trees all give some sort of culture on their openers.  It seems like Piety should be consistent with that.

Really you want the 4 openers for Piety, Tradition, Liberty, and Honor to be about equal with each other but depend on circumstances as to which one you'd choose.  The ideal is that a player chooses each one about 25% of the time as their first policy.

Tradition clearly gives the most culture and should be the policy first taken if you have close neighbors and you plan on playing relatively peaceful.  A second policy may be the Piety opener or a further tradition policy.  Piety is best to take first if you want to get a pantheon pretty quick.  I like that it would give a production bonus for shrines.  Essentially, you could get +2 faith along with +1 culture pretty quickly.  Someone should pick Honor first if you're going really aggressive.  Maybe if you are a civ with a free unique unit (such as the Iroquois), you'd take Honor to be able to get benefits from killing barbarians early.  You'd take the Liberty opener first if you have a ton of open space around you and neighbors far away.

IMO, there really shouldn't be any happiness on the Piety opener.

Also, we have been discussing what to do with the Piety tree in general.  An idea was suggested to have a military oriented policy in the tree somewhere that allowed you to purchase some type of military unit with faith.  I like the idea, but it's more complicated in the details than it first appears.  First, there isn't any type of similar policy currently in the policy-related tables.  Lua code would be needed likely to get it to work.  At the very least, we'd need SQL code to add to the tables a new field.  It's easy to create a new unit that is purchasable with faith as this is what missionaries are already.  Just give them some combat strength and make them a different class of unit.  The questions are, what strength should this unit have?  Someone could take this policy in the ancient era or in the information era.  Arbitrarily giving it a fixed combat strength doesn't appear wise.  Also, what about the art for the unit?  And what would it upgrade to?  It may be easier to do something else, although it's an interesting idea.

**Comment by Thalassicus** [comment]
I updated the original post with more details. I should have done this right away, but work & family were taking up my time.

@EricB1 

> Lowered the gold and production from the opener from 15% to 10%
> Added a free great merchant to Entrepreneurship
> Added Harbors getting +2 gold to Maritime Infrastructure and corrected a text error.
> Increased gold from trade routes in Caravans from +2 to +3
> Removed +10% gold and production from Protectionism, retaining the rest of the policy.
> Left Trade Unions as is.
> Fixed a typo in the text for the finisher.

I agree with your suggestions. The only one I recommend doing differently is Maritime Infrastructure. I like when we use different strategies for different buildings. We build Lighthouses and Seaports in almost every port. I want artificial harbors to be different, a situational building we construct only for trade (domestic or foreign). This is why I no longer give a "good in every city" bonus to harbors with Maritime Infrastructure.

I added you as a collaborator on the project so you can contribute directly to the main github branches. Make bugfixes (only) in the stable branch, and place any other changes in the new-features branch. When in doubt, the new-features branch is a better place to work. This ensures the stable branch will almost always be a reliable and bug-free version of the project.

@EricB1
I started a thread here to discuss belief balance:
http://forums.civfanatics.com/showthread.php?p=13069051#post13069051

**Comment by skodkim** [comment]
Republic updated here: https://github.com/Thalassicus/cep-bnw/commit/0de6199f43a1c79b5db4d2e5ef27da041796efe9

@Thalassicus Thanks for the clarification on some of the policies. So much easier to work on them when we know what you expect.

\Skodkim

**Comment by skodkim** [comment]
Colonization updated here: https://github.com/Thalassicus/cep-bnw/commit/7662ee54465b7627ee8983a8a25a8c11a1302c5b

Have not made any changes to Pioneer spirit in this commit even though the two policy changes seem linked (need to figure out how to do it first)

**Comment by Thalassicus** [comment]
@skodkim 
Road cost and building production rate are in the Policies table. The civilian bonuses (worker, workboat, settler, etc) can give a free promotion with movement and no-upkeep effects. I believe Guided Missiles have the latter bonus. I'm not sure if the upkeep reduction is a promotion or unit effect. It might not be possible with the basic data tools.

**Comment by skodkim** [comment]
Of course. I hadn't thought about using promotions for the extra movement!

On 18. feb. 2014 19.00.43 CET, Thalassicus notifications@github.com wrote:

> skodkim
> Road cost and building production rate are in the Policies table. The
> civilian bonuses (worker, workboat, settler, etc) can give a free
> promotion with movespeed and no-maintenance effects. I believe Guided
> Missiles have the latter bonus.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Thalassicus/cep-bnw/issues/167#issuecomment-35413394

## 

Sendt fra min Android telefon med K-9 Mail. Undskyld hvis jeg er lidt kortfattet.

**Comment by skodkim** [comment]
I've been  looking at Pioneer spirit. So far I've removed the old bonuses and have added the road maintenance modifier and the production boost for Harbors.

I'm not really sure about how to use the promotions to make units free and grant them extra moves though, so I hope someone can help me here:
- The code for granting policies just states that "Policy A grants Promotion B". Therefore I'm thinking that the promotion will be given to all valid unitclasses? If so I guess I can't just use the normal promotions (PROMOTION_EXTRA_MOVES_I and ??) but would have to make a copy of them which is only valid for civilians?
- _Maintenance free units_: I can't seem to find the promotion granting this. Could someone point me to it (I'll find it eventually...).

BTW: In CER_Unlocks UNITCLASS_GUIDED_MISSILE is set at TECH_ROCKETRY and later at TECH_SATELLITES. I guess one of them should be removed, but which one?

**Comment by GrantSP** [comment]
My guess would be to make it Rocketry as it is earlier than the vanilla. We
tend to make things appear earlier. But that is just a guess

**Comment by stackpoint** [comment]
You should check the google spreadsheets.

**Comment by skodkim** [comment]
Sorry but I need you to be a little bit more spefific

**Comment by stackpoint** [comment]
Sorry, I was referring to your guided missile observation. The [spreadsheet](https://docs.google.com/spreadsheet/ccc?key=0Ap8Ehya83q19dDE2TURZSnJSdzE2REx3XzNPY3RVZmc&usp=drive_web#gid=1) suggests that Satellites is the correct tech, though I can't be sure.

**Comment by GrantSP** [comment]
Hmm...
Although the spreadsheet does suggest Satellites it is clear the
CER_Unlocks.sql wasn't created with that spreadsheet, otherwise there
wouldn't be the duplication.
Using "Blame" in GitHub shows both those PrereqTech entries were made at
the same time so that file was hand edited.
The edits were made on 6th of December and the spreadsheet was made on the
22nd of November, so could have been used.

I still contend we should go with Rocketry. Moving to Satellites is just a
sideways move to a tech of the same tier.

But what do I know? :)

On 20 February 2014 04:48, stackpointer notifications@github.com wrote:

> Sorry, I was referring to your guided missile observation. The spreadsheethttps://docs.google.com/spreadsheet/ccc?key=0Ap8Ehya83q19dDE2TURZSnJSdzE2REx3XzNPY3RVZmc&usp=drive_web#gid=1suggests that Satellites is the correct tech, though I can't be sure.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/Thalassicus/cep-bnw/issues/167#issuecomment-35526744
> .

## 

"There are 10 types of people in the world: those who understand binary,
and those who don't."

**Comment by stackpoint** [comment]
Actually, the guided missile has two entries in that spreadsheet so it's likely that it was generated using it.

**Comment by GrantSP** [comment]
Once again your excellent sleuthing skills come to the fore. Well done.
Still think Rocketry is the best choice. For what it is worth.

On 20/02/2014, stackpointer notifications@github.com wrote:

> Actually, the guided missile has two entries in that spreadsheet so it's
> likely that it was generated using it.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Thalassicus/cep-bnw/issues/167#issuecomment-35561202

## 

"There are 10 types of people in the world: those who understand
binary, and those who don't."

**Comment by skodkim** [comment]
Thanks for the reply guys. I'll remove the rocketry entry and update the spreadsheet as well.

You wouldn't happen to have input on the policy question as well?

**Comment by skodkim** [comment]
Whoward just offered me some help on the Policy_FreePromotions table:
http://forums.civfanatics.com/showthread.php?t=521372

If we want do grant free promotions from policies only to certain units we need to make copies of the original promotions that are only valid to these units. It's something that can be looked into, but it seems like a rather long way to go to achieve this effect.

\Skodkim

**Comment by stackpoint** [comment]
My experience with policies and promotions are mostly with simple data edits so I'm not sure how to help you here.

**Comment by stackpoint** [comment]
@skodkim, After looking over our options it seems like the only way to implement a maintenance free civilians is through leader traits. And so the only way to do it through policies is through lua coding. I'd put it on the side until someone is willing to write up some code for it.

**Comment by skodkim** [comment]
Pioneer Spirit change here: https://github.com/Thalassicus/cep-bnw/commit/851bbf5a8a70c29872ce9177463a3fc8fff8501e

IT DOES NOT contain the proposed change making civilian units maintenance
free as this can not be done without lua.
- +1 movement for civilian units
- 50% less upkeep for roads
- 100% production for Harbors
- Fix to flavor for colonization (do we need to change these - I haven't
  done it for the other policies I've tweaked..?)

**Comment by AnastaseAlex** [comment]
I am obviously only an amateur, but could we not create a dummy upgrade for civilian units that makes them give +2 gold per turn therefore negating theur upkeep?

**Comment by skodkim** [comment]
So am I (mostly).
Where would you find this ability. Is it a promotion, a policy effect, ..?

\Skodkim

**Comment by stackpoint** [comment]
@skodkim, regarding the flavor changes, we have to go through the spreadsheet and modify the flavors of all the policies. @GrantSP also needs to change the text description of the policies he's modified. 

@AnastaseAlex, as far as I'm aware, there is no promotion effect that implements gold per turn.

**Comment by skodkim** [comment]
Maritime Infrastructure updated here: https://github.com/Thalassicus/cep-bnw/commit/a8b8a2381b0a96ff8ab14522125dba8709684999

**Comment by skodkim** [comment]
Unity Policy updated here: https://github.com/Thalassicus/cep-bnw/commit/f3248cbb52f37ce98a6f509e1d16fcdd2e3cb59b

Whooops. And here: https://github.com/Thalassicus/cep-bnw/commit/8a258fcb9e7de334ad37de386e5504b63a72dd15

**Comment by skodkim** [comment]
Meditation Policy updated here:https://github.com/Thalassicus/cep-bnw/commit/2aa2c2488f1c1a687595a8b23c2b78ed98c8dfff

**Comment by skodkim** [comment]
Piety Finisher Update here:https://github.com/Thalassicus/cep-bnw/commit/1fddaa2ac4dd6139386c394ae3d0f15f576871b5

**Comment by skodkim** [comment]
Charity Policy Update here: https://github.com/Thalassicus/cep-bnw/commit/324296cad1c1181bb7e5bbdb52c0c1be69bcea2c

**Comment by skodkim** [comment]
Just thought I'd let you know that I'd be happy to do more policy updates but. It seems however that the rest are beyond my reach as they are all (partially) dependant on other than normal policy effects.

If anyone has any hints (also concerning research agreements, etc.) I'd be happy to do the coding!
