### ISSUE TITLE
Golden Age Yield Modifiers

### ISSUE THREAD

**Issue by stackpoint** [Thalassicus/cep-bnw#168]
- [x] +20% Surplus Food
- [x] +20% Production
- [x] +20% Gold
- [x] +20% Science
- [x] +20% Culture
- [x] +20% Faith
- [x] +50% Culture from Persia's UA

**Comment by stackpoint** [comment]
[This](https://github.com/Thalassicus/cep-bnw/commit/81a9dcecf124ea449b92dac4c08f92fede8ae75b) should activate the +20% modifiers for production, gold, and science. Also will cause the tooltips to incorrectly display that +20% modifier is active while there aren't any actual additional yields being produced. The rest will require YieldLibrary to handle the extra yields.

**Comment by GrantSP** [comment]
I could have sworn I was getting 50% longer GA times with Persia, now I'm not.
The database still shows a 50% in the **GoldenAgeDurationModifier**, did we change something in the last commit or two? I'm only having 10 turn GA lengths not 15 as expected.

**Comment by stackpoint** [comment]
What are you using to trigger the golden age?

**Comment by GrantSP** [comment]
Playing the game as normal. Just having a break from bugfixing for an hour or two and noticed it.

**Comment by stackpoint** [comment]
The golden age duration modifier and the combat modifier needs to be removed from the trait as well.

**Comment by GrantSP** [comment]
Huh. So we are making the GA lengths the same for them as for the others? That modifier is still active why aren't we getting longer GAs?

I like those parts of the Persian UA. When was this decided?

**Comment by stackpoint** [comment]
Persia's UA reads:

``` sql
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_TRAIT_ENHANCED_GOLDEN_AGES', '+50% [ICON_CULTURE] Culture and +1[ICON_MOVES] Movement during [ICON_GOLDEN_AGE] Golden Ages.[NEWLINE]Starts with a unique Spearman.', '', '');
```

**Comment by GrantSP** [comment]
I was just assuming our additions were just that, additions not replacements.
IMHO this makes it a pretty poor UA then. Big deal +1 to movement & +50% Culture. The greater length of a GA and the _normal_ +20% Culture is pretty good.
Ah well, may be some balancing discussions in the forum again.

Thanks @stackpoint

**Comment by stackpoint** [comment]
It doesn't make sense to leave part of the UA's description out of the text. It's possible that the golden age length modifier and the combat modifier were supposed to be left in and if that's the case then that should be added back into the text description.

And I just ran a test with Persia. Golden ages did receive their 50% bonus. Were you starting golden ages with great people? That could explain the reduced turn count.

**Comment by GrantSP** [comment]
By great people and just as per normal. How strange.

Agreed about the description but I don't know what the actual rationale for this UA was.
I'll check back through the forum discussions later.

**Comment by stackpoint** [comment]
These should be fixed with the activation of the city yields from the YieldLibrary. Any further yield issues should be brought up in the following issue: https://github.com/Thalassicus/cep-bnw/issues/179
