### ISSUE TITLE
City-Capture/Pop-up Queue Bugs

### ISSUE THREAD

**Issue by GrantSP** [Thalassicus/cep-bnw#17]
(Formerly titled: City-Capture/Puppet Status/City Governor/End Turn Production Button)

I have given it this title because I am not sure which area is the problem but as they all relate to one another they are included in the description.

The Aztecs, with 3 cities, DoWed me and I was forced to counter and take their cities.
The first to fall gave me the correct city capture options and after choosing FORCE I was left with exactly what was expected.
Next was the Capital which fell but did not give an option on capture. As I was going to select MERCY and puppet it I didn't feel too bad as the city "appeared" to be the same population and it showed the "puppet" icon as its status.
The last city fell and it too didn't offer a capture option but again the result was what I would have chosen.

Now the first captured city soon began building as expected and it kept pace with the rest of my cities, however, as I was preparing to build a few wonders that require buildings in your other cities to be built I was surprised to find the former Aztec capital included in the calculations.
Despite it showing a "puppet" status, I had to manually assign buildings in it so as to fulfil my quota.
Now the problem presents itself this way.
If it is a puppet it should have its own governor assign buildings and not be included in my cities.
If it in fact was NOT a puppet, then the "End Turn" button would be inactive until ALL production queues are filled. But there was no indication by this method.
Lastly, the third city which I assume was a puppet also never built anything after its capture. I never even went to view it unless it too changed its status and became one of my cities.

**Comment by stackpoint** [comment]
After some testing the other day, Grant found that it was buttonpopup_chooseproduction that was stuck in the popup queue. This may or may not have been fixed with liberation fixes, more testing will be required.

**Comment by GrantSP** [comment]
I have found there is another popup panel being stuck in the queue and forcing this error.
BUTTONPOPUP_TECH_AWARD is also showing as being open after taking a city in capture.

Curiously, after accepting a peace offer which included another city, which I took. I was given the options menu for control of that city: Mercy, Force, Wrath.
However according to the FireTuner the open popup panel is still in the queue somewhere.

**Comment by stackpoint** [comment]
Was this with Assyria?

**Comment by GrantSP** [comment]
No Greece vs Babylon.

**Comment by GrantSP** [comment]
Just quit out of that game and checked the lua log. There is this:

Assets\UI\InGame\Popups\TechAwardPopup.lua:82: bad argument #1 to 'ConvertTextKey' (string expected, got nil)

Not sure if they are related or not as it does happen only once in the log early and combat continued well past that turn.
About the only thing I can see that is different between my capturing the city and the city being given in a peace deal is the code from CEA_Events.lua about partisans rallying to the new capital after the previous one falls. The very next entry after the last listing of those events mention the techtree popups. However, this is only one mention out of 5 or 6 where the CEA_Events code moves the partisans around. So, I am doubtful that that is it.

**Comment by stackpoint** [comment]
The TechAwardPopup.lua:82 error is probably related to the fact that the tech Carvel Hulls doesn't have a Help field. I've added a blank one which shouldn't cause the error to reappear. See https://github.com/Thalassicus/cep-bnw/commit/3cab7b934096ad04cd509c7f4955dc9bc0e7643a

This is likely the source of the stuck popup since a similar one occurred an error with NaturalWondersPopup.lua a while back.

**Comment by GrantSP** [comment]
That is very strange, how difficult was it to catch that?

**Comment by stackpoint** [comment]
I used the database program you recommended to look at the Technologies table and the Help column were all blank except for Carvel Hulls which was pink blank. I then realized from earlier bugfixing that Technologies.Help had been blanked in CEP and that the pink blank must be a NULL value instead. And that's probably the most likely point of error.

**Comment by GrantSP** [comment]
Ahh, I was looking into the lua code to see what you were looking for.

It looks like the function OnPopup uses:
if popupInfo.Data3 == -1 then return

Apparently the HELP section must be that Data3 and as you figured out it
was NULL not a nil value. So clearly the == can't evaluate that.

The text sections in that, and I assume other, tables must be referenced
that way;
Description = Data1, Civilopedia = Data2 and Help = Data3

That may be helpful later on.
Good pick up.

Happy Thanks Giving
Grant

On 30 November 2013 18:49, stackpointer notifications@github.com wrote:

> I used the database program you recommended to look at the Technologies
> table and the Help column were all blank except for Carvel Hulls which was
> pink blank. I then realized from earlier bugfixing that Technologies.Help
> had been blanked in CEP and that the pink blank must be a NULL value
> instead. And that's probably the most likely point of error.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Thalassicus/cep-bnw/issues/17#issuecomment-29547764
> .

## 

"There are 10 types of people in the world: those who understand binary,
and those who don't."

**Comment by GrantSP** [comment]
Found something else that might need looking into for other things.
The HELP fields are all being set to nothing in the file, Interface_Data.sql in the CAT mod.
Since Carvel Hulls is defined later in the CEG mod the first removal of all the HELP fields isn't working on that new entry.
Any new stuff we add for anything needs to be defined fully to avoid these types of errors. Better yet, move all these system wide correction files to be applied at the end of all the additions.
I guess with the 4 separate parts of this mod there will be an even greater chance of slip ups like this.

Without starting a drawn out discussion on it, I can't see the benefit of splitting it into CAT, CEG & CIN. Who is going to use one without the other? And if CEG must depend on CAT it really should have these dependencies reversed or something.

**Comment by stackpoint** [comment]
Actually, line 82 of TechAwardPopup.lua is:

``` lua
        Controls.TechHelp:SetText( Locale.ConvertTextKey( pTechInfo.Help ) );
```

And I assume that the ConvertTextKey() function was getting errors when pTechInfo.Help was NULL. I don't believe it had anything to do with the OnPopup() call.

I believe that Help field are being temporarily blanked until all the tech help text can be revised. And they would probably be revised later on in the project when Techs aren't likely to change. Either way, the Help field being missing from it's initial definition in CEG isn't a problem with CAT loading first, since it should've been defined at that point anyway.

**Comment by GrantSP** [comment]
Where are these 'new' help texts going to be displayed? The civilopedia is now formatted correctly, thanks to your efforts, and the tooltips don't need to provide any more detail. If it is because the text is wrong, wouldn't placing a "To be revised" marker in it's place be better? Leaving all the other correct text in place.

**Comment by GrantSP** [comment]
I don't believe there is any reason for this to still be open.
