### ISSUE TITLE
[31.01.14 stable] Ceremonial Rites building not free

### ISSUE THREAD

**Issue by TimurKelman** [Thalassicus/cep-bnw#171]
Got the policy, it correctly gives the building, but it's not free -- i'm paying maintenance for it.

**Comment by skodkim** [comment]
Very true. This is however a known bug that has been already been documented, e.g. here: https://github.com/Thalassicus/cep-bnw/issues/54

The policy effects are planned to be altered with the next release.

\Skodkim
