### ISSUE TITLE
[31.01.14 stable] Barbarians not acting

### ISSUE THREAD

**Issue by TimurKelman** [Thalassicus/cep-bnw#172]
In the very beginning of my game - something like turn 40 - 2 barbarian units (Brute and Archer) marched towards my only city, but then they just stopped right outside my culture borders, which was unusual, but ok. But then i build an archer and now shooting at the barbarians with no reaction from them, they literally don't do anything, the Brute isn't pillaging, the Archer isn't shooting back. VERY strange.

**Comment by GrantSP** [comment]
This sounds like the new AI routines that are being run in these later
builds.
Barbarians are made stronger but less likely to take you on in the early
game, this is to allow you a chance to build up your empire but at the same
time give more aggressive players some challenge if they want.

On 1 February 2014 04:20, TymurGubayev notifications@github.com wrote:

> In the very beginning of my game - something like turn 40 - 2 barbarian
> units (Brute and Archer) marched towards my only city, but then they just
> stopped right outside my culture borders, which was unusual, but ok. But
> then i build an archer and now shooting at the barbarians with no reaction
> from them, they literally don't do anything, the Brute isn't pillaging, the
> Archer isn't shooting back. VERY strange.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/Thalassicus/cep-bnw/issues/172
> .

## 

"There are 10 types of people in the world: those who understand binary,
and those who don't."

**Comment by stackpoint** [comment]
Barbarians are not allowed into any player owned territory until turn EarliestBarbarianReleaseTurn set by difficulty level. Ranging from turn 100 on settler to turn 20 on deity. This is to offset how much more vicious they are in CEP.
