### ISSUE TITLE
Anti-Tank guns

### ISSUE THREAD

**Issue by GrantSP** [Thalassicus/cep-bnw#175]
Has there been a policy shift recently regarding the use of these units?

I was under the impression we have retired these and Marines from the game. In the most recent game I am running Gatlings are upgrading to Anti-Tanks and I have just received 1 from a CS ally and it has the Settler icon attached.

Additionally the pedia is back to showing the Anti-Tank in the list of units. The production queue likewise has them as available.

If I have missed a memo :smiley: please let me know.

**Comment by stackpoint** [comment]
See if you can make sense of this: https://github.com/Thalassicus/cep-bnw/blame/609f9f861c1b06e1bcb87186cc803ef7f6a7a7fa/Ceg/Ceg/Armies/CEA_Land.xml

**Comment by stackpoint** [comment]
And the only recent change made to them was made by me here: https://github.com/Thalassicus/cep-bnw/commit/1d1581b3ba1df178f4c780106564de0ad7531f83

**Comment by GrantSP** [comment]
Yeah, saw that one. No problem there.

**Comment by stackpoint** [comment]
My changes might have caused a bug with the city state gifting code. It's possible that the units don't depreciate correctly because we moved them out of future tech.

**Comment by GrantSP** [comment]
No I think that is fine. As far as the code for CS gifting is concerned they are giving Machine Guns. It just so happens this edit has made them look like AT Guns.

**Comment by stackpoint** [comment]
I guess the concept is that machine guns are called anti-tank guns and replace them in the tech tree. Something is wrong with their icon though.

**Comment by GrantSP** [comment]
It seems like a needlessly fiddly change though. We aren't actually getting anything from this and the fix is bringing in errors.
Just what is wrong with calling Machine Guns, machine guns. If I want to take down tanks with them I can without the need of calling them such. As it is the impression is they are more suited for this purpose, which they aren't.
If we want Machine Guns to handle tanks more effectively we should rather give them anti-armour bonuses as standard.

**Comment by stackpoint** [comment]
It's a flavor change. Like moving the infantry unit lines an era earlier (arquebusier, musketman, rifleman, etc) for historial flavor. I don't know Thal's specific reasoning but it's not something that's unprecedented.

**Comment by GrantSP** [comment]
Hmm... not quite the same, but I see your point. The problem is the unit chosen to replace the machine gun already exists in a deprecated form.
Moving units up or down the upgrade line is all well and good but the implementation, not to mention the documentation, needs to be sound.
Just what is wrong with machine guns? If that is explained then we can all see the need for replacements.
None of this is mentioned in the [release](https://github.com/Thalassicus/cep-bnw/releases/tag/v3.13) for this commit

**Comment by damunzy** [comment]
I noticed when using a Gatling Gun to explore an Ancient Ruins my unit was upgraded to an Anti-Tank gun with a Strength of 5. I ended up using IGE (In Game Editor) to delete then re-add the unit and Ancient Ruins to get another random goodie.

**Comment by GrantSP** [comment]
The code for this change has been commented out so we can safely close this.
