### ISSUE TITLE
Candi tooltip lacks information about YieldPerReligion

### ISSUE THREAD

**Issue by GrantSP** [Thalassicus/cep-bnw#176]
Looking in the game at the stats for the Candi shows a rogue figure
:1 
in the stats for this UB but doesn't show the +200 Faith for each religion in the city.
The database and the TooltipWriter code have the correct table references to pull this value but for some reason it isn't showing.
The table is: **Building_YieldChangesPerReligion**

The code looks to call this for the value but I can't see why it isn't showing.

**Comment by GrantSP** [comment]
Found the problem, and the solution but I can't seem to get the lua code to function without bugging out the game.

**TW_Init.lua** needs to have an _elseif_ line added to use this table in the tooltip generation. Similar to this one:

```
    elseif lineType == "YieldFromBuildings" then
    return GetYieldInfo{table="Building_BuildingClassYieldChanges", cell="YieldChange", tableExtra="BuildingClasses", cellExtra="BuildingClassType"}
```

However I can not seem to get the right code set up and it renders the game next to useless.

Going through the tooltips for the buildings shows there are a number of tables that buildings/wonders use that are not reflected in the current tooltips.
Someone with a bit more coding skill than me may need to look through this stuff.

**Comment by GrantSP** [comment]
Looking at bit more into this. We may be better to drop our use of the tooltip code and go with [EUI](http://forums.civfanatics.com/showthread.php?t=512263)
From what I have seen, at least for buildings, it is able to handle all the value changes really well, it has no need of modded TXT_KEYs and it can be added to much more simply than ours.

I have yet to do further testing with units and promotions.
Will do so now.

**Comment by stackpoint** [comment]
I believe the lineType will be "YieldFromReligion" as seen from TW_BuildingStats.sql.

**Comment by GrantSP** [comment]
That part I could get. It was the _return_ part of the function that threw me.

**Comment by stackpoint** [comment]
I don't understand the code either. However, even if we use the majority of EUI's tooltip code, we'll still need to write custom code for any custom table/columns/properties we've added in CEP. Which I wouldn't know how to do either.

**Comment by GrantSP** [comment]
that's the thing though, the **InfoTooltipInclude.lua** that bc1 uses in EUI is so simple. As far as I can see all he does is set up some _local_ **UnitFlags** and then list ALL the different variables like this:

```
OneShotTourism = L"TXT_KEY_MISSION_ONE_SHOT_TOURISM" .. " (%g)",    -- Musician
OneShotTourismPercentOthers = "",
```

Here The OneShotTourism uses the vanilla TXT_KEY and a % for the value. The OneShotTourismPercentOthers is yet to be defined and it just shows that variable as the label.
Nothing gets left off and it is all in one file.
Very elegant.

**Comment by GrantSP** [comment]
Thanks to help from @Thalassicus this is now fixed.
He has modified the lua code to have some helpful information about how to set up new tooltips.
