### ISSUE TITLE
Localization issues with tooltips

### ISSUE THREAD

**Issue by GrantSP** [Thalassicus/cep-bnw#177]
A French user that is translating the mod into French has PMed me about a couple of odd  tooltip issues related to the free units given at the outset of the game.

So far the Persian Immortal and the Mongolian Scout are lacking the tooltip that displays when you mouseover the unit in the map display. I have asked if the other units show their tooltips and not been told otherwise so it appears to be the free units.

**Comment by Slogun** [comment]
Yes, it concerns all the free units (Immortal, Horse archer etc.)

**Comment by GrantSP** [comment]
Thank you, I am investigating.

**Comment by stackpoint** [comment]
Could you attach a screenshot? Troubleshooting localization problems is likely to be difficult.

**Comment by GrantSP** [comment]
I am closing this issue as its outcome should be tied in with the #30 .
