### ISSUE TITLE
PolicyNumOptionsConsidered - Max AI Policy Branches

### ISSUE THREAD

**Issue by stackpoint** [Thalassicus/cep-bnw#18]
It looks like PolicyNumOptionsConsidered in the HandicapInfos table controls the number of possible branches the AI can choose from. This may allow us to unlock the AI's ability to pick and choose from multiple trees at once. Below is the code from CvPolicyAI.cpp:

``` cpp
    // If total weight is above 0, choose one above a threshold
    if(m_AdoptablePolicies.GetTotalWeight() > 0)
    {
        int iNumChoices = GC.getGame().getHandicapInfo().GetPolicyNumOptions();
        iRtnValue = m_AdoptablePolicies.ChooseFromTopChoices(iNumChoices, &fcn, "Choosing policy from Top Choices");
    }
    // Total weight may be 0 if the only branches and policies left are ones that are ineffective in our game, but we gotta pick something
    else if(m_AdoptablePolicies.GetTotalWeight() == 0 && m_AdoptablePolicies.size() > 0)
    {
        iRtnValue = m_AdoptablePolicies.ChooseAtRandom(&fcn, "Choosing policy at random (no good choices)");
    }
```

**Comment by Thalassicus** [comment]
Why do you think they let the AI choose _fewer_ trees on higher difficulties? If we fill every tree we open, we pick a lot of policies useless for our situation. It seems this would make the AI perform worse on higher difficulties. I'm trying to figure out what their thought process was... what was the logic behind this? Am I overlooking something?

**Comment by stackpoint** [comment]
Back in the vanilla game, it was in the player's interest to fill out every tree they open in order to unlock the Utopia project. So on lower difficulties they allow the AI to get "sidetracked" or open multiple trees at once which sets them back in terms of the old victory conditions.

**Comment by Thalassicus** [comment]
That's a very good point - this might be a leftover from before BNW. My suspicion of that is strengthened because settler-difficulty AIs can choose from 10 policy branches, but there's not 10 branches to select from anymore!

It sounds like we can broaden the AI's options now. I'll add a tweak for this to the new-features branch.
