### ISSUE TITLE
Making the variables easier to translate.

### ISSUE THREAD

**Issue by GrantSP** [Thalassicus/cep-bnw#186]
I would like a bit of input if I might, please.

The different languages are handling the variables in different manners, not all the variables get nerfed in the same way and combinations of them produce errors where single variables do not.

What I would like to know is, do you think changing the curly braces to brackets in the spreadsheet and then running a series of regular expressions over the text files is an acceptable way to handle this.

If you look [here](https://docs.google.com/spreadsheet/ccc?key=0Ap8Ehya83q19dGtjX2JldHBzdXhRbGNxVFgxT1E2OHc&usp=drive_web#gid=8) you can see some tests of different ways of setting out the text and the results given.

The variables in [ ] seem to provide a consistent and accurate result.
Also the percentage sign needs to be enclosed to ensure the correct placement.

Ideas would be appreciated. I don't want to make the task harder than it needs to be.
I am quite comfortable using regex but others may not be and if they forget to run it the files won't work.

**Comment by stackpoint** [comment]
Shouldn't google spreadsheets have some sort of replace function? You can do cell operation [SUBSTITUTE ](https://support.google.com/drive/answer/3094215) to replace { with [[ and } with ]] and once it's translated use it to replace [[ back to { and ]] back to }.

**Comment by GrantSP** [comment]
hmm...

It is a very rudimentary UI. I can't say I have used it all that much. Good idea though, keeps all the grunt work in one place.

On second thought maybe Thal has already got something like this set up.

The only concern I have is I don't think these sort of functions work on the cell containing the result of the previous function.
The stuff we need to change is just the end result of the translate tool.
More thinking is needed. Substitute would be a good option though.

**Comment by stackpoint** [comment]
Looks like google spreadsheets will also accept regex too: https://support.google.com/drive/answer/3098245

So some pseudo code would go something like =REGEX(TRANSLATE(REGEX(text, expression, replacetext), language),expression replacetext)

**Comment by stackpoint** [comment]
You should be able to chain several functions together as far as I know.

**Comment by GrantSP** [comment]
Need brain food.

And coffee.
