### ISSUE TITLE
Policy : Rebublic (Liberty tree)

### ISSUE THREAD

**Issue by Slogun** [Thalassicus/cep-bnw#192]
**EDIT : i got my defense buildings, but 2 turns later.**
Someone could confirm that the Republic policy doesn't work, as it won't give any free defense building at all ?

**Comment by stackpoint** [comment]
Did you have the tech for Walls researched when you picked the Republic?

**Comment by Slogun** [comment]
I didn't, SP.

**Comment by stackpoint** [comment]
This is a common oversight. I've also done this a couple times myself. Do you think that we should add some sort of tooltip information regarding this?

**Comment by GrantSP** [comment]
I think we should and in fact I have already added this line to the spreadsheet:
_Free City Defense building in all cities (current, new, and conquered) With the appropriate tech researched._

**Comment by stackpoint** [comment]
Need a fullstop between "conquered) With".

**Comment by GrantSP** [comment]
Done.
