### ISSUE TITLE
No upgrade path for Hunnic Hand-Axe unit

### ISSUE THREAD

**Issue by p0rkjello** [Thalassicus/cep-bnw#203]
Hunnic Hand-Axe unit gained from barbarian encampment cannot be upgraded. Using current Steam server. Do not see mention in Github changelog.

**Comment by GrantSP** [comment]
Hunnic Hand-Axe? The Axman is a **barbarian** unit and it does not have an upgrade path.

**Comment by stackpoint** [comment]
The old German UA has been moved to the Huns. It looks like Thal moved the hand-axe from the chariot archer class without setting many of the miscellaneous properties (including promotion path): https://github.com/Thalassicus/cep-bnw/blob/stable/Cat/Cat/Fixes/Cat_Fixes.xml

**Comment by GrantSP** [comment]
Huh! What? How is that related? That 'fix' has been in place for some time now. Had to do with the strength of the axman being formulated along with other Chariot Archer units.

**Comment by stackpoint** [comment]
The Hand-Axe upgrades to a Knight in the base BNW game. The Unit_ClassUpgrades table needs to be updated to take into account the modified hand-axe class.

**Comment by GrantSP** [comment]
My apologies. You are correct. (again)
I assumed that like the other barbarian units, Archer & Warrior, it didn't have a suitable upgrade path.

**Comment by stackpoint** [comment]
The other barbarian units should be able to upgrade in the base game too.

**Comment by stackpoint** [comment]
There are a bunch of duplicates in this table too.

**Comment by GrantSP** [comment]
Barbarian archer & warrior have no ObsoleteTech or GoodyUpgrade, so I assume they don't upgrade.
To be honest I don't get these units and keep them long enough to see.
It is a different matter to the units inside the camps upgrading on era change.

Which table are you looking at?

**Comment by stackpoint** [comment]
ObsoleteTech refers to the Tech that the unit can be built until. GoodyUpgrade is the UnitType that the the Unit upgrades into from Ancient Ruins.The **Unit_ClassUpgrades** table contains both units.

**Comment by GrantSP** [comment]
Time for another coffee I think, too many stupid comments from my side.
Of course that is where they are defined. I knew that. At least I thought I did. :(

**Comment by Thalassicus** [comment]
I'd like this unit to essentially be an Archer variant, with the same promotions and upgrade path. It fits the unit better than the chariot skirmisher designation.

**Comment by Thalassicus** [comment]
I added the axman -> composite bowman upgrade and Ancient Ruins upgrade links.
