### ISSUE TITLE
Incorrect Icon AntiTank Gun

### ISSUE THREAD

**Issue by p0rkjello** [Thalassicus/cep-bnw#206]
Using Current Steam Workshop version.

When upgrading a unit from Gatling to AntiTank the unit looks like an AntiTank but the unit icon is the Settler flag.

**Comment by GrantSP** [comment]
That is interesting that bug is still present in the Steam version.
The upgrade path for Gatlings has been reverted to Machine Guns and this bug no longer appears in the current CivFanatics or GitHub releases.
It is however known about and your next Steam release **should** have the error fixed.

**Comment by p0rkjello** [comment]
Switched to the Github version 3.14.1 & the same issue exists. Gatling converts to AntiTank and the icons are the Settler flag.

![civ5screen0001](https://f.cloud.github.com/assets/392383/2349851/89cf158a-a568-11e3-820c-8a9bb775d485.png)

**Comment by GrantSP** [comment]
Thank you p0rkjello.
It seems we have been lax in keeping the **releases** up-to-date.
To confirm [this](https://github.com/Thalassicus/cep-bnw/blob/stable/Ceg/Ceg/Armies/CEA_Land.xml) is what the **actual** file in question should look like.

Lines 12 -24 should be commented out. If they are not then just do so in your copy.

Apologies for the inconvenience, and thanks for the confirmation or **our** error.
