### ISSUE TITLE
UI not loading after LocalizedText + New Features + Minor Update

### ISSUE THREAD

**Issue by GrantSP** [Thalassicus/cep-bnw#212]
This is very perplexing.
The release as of yesterday was working very well, no obvious problems.

I made 6 commits today to add in some changes that were made in the **Stable** branch that weren't in the **New Features** branch as well as some small changes to address #209 as reported a few hours ago.

The only commits that make changes to the CAT module is the [Database & Lua Errors](https://github.com/Thalassicus/cep-bnw/commit/712a86b90d6e803ff07691d15ebae02c7a1a606a)

Now, even with just CAT loaded as a mod, the game UI refuses to show.
Even after reverting the change, I still cannot fix this. Vanilla games have their UI, so it isn't an issue with the integrity of my install.

**Comment by stackpoint** [comment]
I just tested a build of the latest new-features branch and it works fine.

**Comment by GrantSP** [comment]
So you built it, not used the released zip?
That may be the problem. I will do the same at my end and see.
I was having problems with GitHub accepting the file. Weird error messages like:
**"We don't accept files of that type"** or **"Yowza! that's a big file!"**

**Comment by stackpoint** [comment]
Also, things of note:
- The changelog of the changes is [here](https://github.com/Thalassicus/cep-bnw/issues/193) and your release post should contain them
- I don't believe you've added your [policy adjustments](https://github.com/Thalassicus/cep-bnw/commits/new-features?author=grantsp&page=1) from six weeks ago to the linked changelog or made the corresponding text changes to the spreadsheet/sql files.

**Comment by GrantSP** [comment]
Are you yelling at me?!

**Comment by stackpoint** [comment]
Just a formatting issue. Interestingly enough, if you leave an empty bullet point "-" in GitHub it gets formatted into emphasized text.

## \- test

**Comment by GrantSP** [comment]
The build you just did, was it of **New-Features** or my **LocalizedText+New Features**?

I am still getting no UI.

**Comment by stackpoint** [comment]
It was of new-features. UI errors should produce lua errors unless you are using the EUI DLC?

**Comment by GrantSP** [comment]
Could you do a build and see? I was not using anything except our stuff.

Regarding the logs, since the New Year I have been unable to get anything in my logs except the first line.
I have all the config files set up but I get **nothing**. I just gave up in frustration weeks ago. Even after input from both you and @Thalassicus I still have nothing. Put that issue aside for the time being.

**Comment by GrantSP** [comment]
Also, I think I didn't do anything with those Policies texts because @Thalassicus was umming and ahhing about using the tooltipwriter to generate them.
If we could get that working then the text changes will be easy to implement.

**Comment by stackpoint** [comment]
I thought it might've been EUI since you didn't mention any lua log errors but I believe the following might be the error: https://github.com/Thalassicus/cep-bnw/commit/ed26580a01d67582a08892cbfb240f58d48dbf44

**Comment by stackpoint** [comment]
I'm not sure what you were planning on doing with that section of code but I had successfully fixed the errors by removing that whole new section. But it may(?) be fixed by fixing the comma syntax errors.

**Comment by GrantSP** [comment]
I know what I was doing now! I moved KO_KR up the list to be alphabetical and forgot to add the comma after it and remove the ending comma from ZH_HANT_HK.
Should work now.

**Comment by stackpoint** [comment]
That's what I mentioned in your commit.

**Comment by GrantSP** [comment]
Damn this GitHub upload takes a long time.

Anyway, you found it. The commas, one missing and one extra, in the CAT_Start.sql file screwed up the UI.

I've just now uploaded the _"fixed"_ release.
I guess I must have made that small change later than I thought. I could've sworn that was made yesterday before the initial release, guess not.

All we have to do now is make sure that it includes ALL the fixes from both **Stable** & **New Features** and we can switch the mod over to it as the Stable.
I'm 99.9% sure it has all the New features stuff, and I see you have made a merge or two recently, so if we can verify all the Stable changes are there we should be good to go.

I'll close this now.

**Comment by stackpoint** [comment]
I've already pushed both stable and new-features into your "Localized-Text-+-New-Features" branch so what you should do now is merge "Localized-Text-+-New-Features" into new-features and then delete the "Localized-Text-+-New-Features" branch.

**Comment by GrantSP** [comment]
The point I was trying to make is:
Stable will be substantially different to either new-features or my
localizedtext branch.
Making new features and localizedtext merge is done, at least in one
direction. Going back the other way is not necessary.
Same thing can be accomplished by deleting newfeatures and renaming
localizedtext to newfeatures.

The problem is having the stable and the working branches closer in
lineage. IMO.

On 14 March 2014 15:47, stackpointer notifications@github.com wrote:

> I pushed both stable and new-features into your
> "Localized-Text-+-New-Features" branch so what you should do now is merge
> "Localized-Text-+-New-Features" into new-features and then delete the
> "Localized-Text-+-New-Features" branch.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/Thalassicus/cep-bnw/issues/212#issuecomment-37616474
> .

## 

"There are 10 types of people in the world: those who understand binary,
and those who don't."

**Comment by stackpoint** [comment]
I don't believe the automatic tooltips are going to be coded for policies anytime soon so I would suggest making your corresponding text changes if you plan on releasing updates.
