### ISSUE TITLE
Compatibilty with Colonialist Legacies civilizations

### ISSUE THREAD

**Issue by GrantSP** [Thalassicus/cep-bnw#218]
TPangolin, the lead of [this mod project](http://forums.civfanatics.com/showthread.php?t=512802) has contacted me about making 2 of his mods work with CEP, namely Mexico & Phillipines.
I have looked at what is wrong and it appears our ProductionPopup.lua sorts the buildings into order and then displays them in the panel.
The error with the Mexico civilization (I assume the Phillipines also) and CEP is the production panel only shows Units.

The lua shows an error at line 105 of the above file.
I think we can fix this with having the load order or references changed to allow these mods to use our modded lua. How that is done isn't clear to me. CSD had no problem with their new buildings so I may be wrong in my assumptions.

**Comment by stackpoint** [comment]
What are the lua errors?

**Comment by GrantSP** [comment]
ProductionPopup.lua:105: bad argument #2 to '?' (Key must be of type 'number' or 'string'.)

**Comment by stackpoint** [comment]
Adding a reference to the mod in CAT should solve this?

**Comment by GrantSP** [comment]
If you mean like this:

```
<Mod id="5a13b06d-9298-40f9-a511-522a825af190" minversion="0" maxversion="999" title="[BNW] Colonialist Legacies - Mexican Republic" />
```

Then no, didn't work.

**Comment by stackpoint** [comment]
The mod author did not set the domains of his units which is why the domain call fails.

**Comment by stackpoint** [comment]
The two units in question for the Mexico civ is UNIT_FAKE_OVERRIDE and UNIT_FAKE_HACIENDA. I presume that the Phillipines civ has a similar problem.

**Comment by GrantSP** [comment]
I would NEVER have found that.
Thanks. Good man.

**Comment by stackpoint** [comment]
I'm going to list a couple of possible errors for the Phillipines mod:
- BUILDINGCLASS_JFD_CARGO_SHIPS is listed as BUILDINGCLASS_JFD_CARGO_SHIPS_2 in Civilization_FreeBuildingClasses table.
- BUILDING_JFD_PHILIPPINE_TEMPLE incorrectly named BUILDING_JFD_TEMPLE in Buildings table.

**Comment by GrantSP** [comment]
Mexico mod also seems to be lacking in <Description> tags for both the dummy buildings.

**Comment by GrantSP** [comment]
Made all the changes discussed and there don't appear to be any further errors.

**Comment by stackpoint** [comment]
Thanks for your help.
