### ISSUE TITLE
Spreadsheet formula problem

### ISSUE THREAD

**Issue by GrantSP** [Thalassicus/cep-bnw#219]
This isn't a big issue but if anyone wants to have a crack at it I will describe it here.

Have a look at the formula as working on a specific problem CELL like B70 of the [Policies tab of CEP_Language](https://docs.google.com/spreadsheets/d/1ptQRfVsW7UT_8gPexioizS31sM7K_3eBT3tjr4jruTs/edit#gid=817561923)

The formula has a **regexreplace** to handle the variables in the other language columns. Some of the languages mangle the text inside { }.
**This doesn't need to change.**
The "problem" is when the CELL contains a variable that shouldn't be changed, like the one listed here.

Here the new TXT_KEY will call the existing TXT_KEY from something else. This is useful in making composite TXT_KEYs like in CELL B77 where the TXT_KEY_IN_ALL_CITIES is inserted into the new TXT_KEY.

If we can make some IF clauses or similar this will fix it.
I am making this just because I stumbled upon it whilst updating some of the text not because it is something that needs urgent attention.
Having said that, a lot of the foreign text files are now flawed and will need to be updated.
Also there is a slight difference in the formula in the German column as that threw up some specific errors only with German, so the formula cannot be copied across the range of languages.

**Comment by stackpoint** [comment]
[This](https://support.google.com/translate/?hl=en) states that you can use "notranslate"? Or something like it.

**Comment by GrantSP** [comment]
Not quite. That has more to do with the actual API that is used in many places, like inside the spreadsheet formula **googletranslate**.

If we set up a **custom** webpage with its own API then we would have full control on what is translated and how. Unfortunately for us, this is not the case.

Nevermind, this isn't a high priority issue. We can always use the **Manual Translation Override** columns to provide corrected text.

**Comment by GrantSP** [comment]
Simple really when I put my mind to it.

`regexreplace($B5,"_[^\{TXT]*\}","}")`

instead of:
`regexreplace($B5,"_[^\{]*\}","}")`
