### ISSUE TITLE
3.15.1 Ancient Ruins rewarded anti-tank gun as a unit upgrade with a cbat str of 5

### ISSUE THREAD

**Issue by Seredin** [Thalassicus/cep-bnw#221]
So it looks like the anti-tank gun might be removed from BNW as a buildable unit, but I still received one as an ancient ruins weapon upgrade. This isn't really a big deal in and of itself, except for the fact that the anti tank gun has a combat strength of 5, not 50 (as per the https://drive.google.com/folderview?id=0B58Ehya83q19eVlvWXdmLXZ6UUE table), thus rendering my highly decorated barbarian crusher unit... useless.

It's possible that hunting down this bug isn't worth the time, but a suggested simple workaround is to take a look at CEG\Armies\CEA_Start.sql and change the cost and combat strength of the anti tank gun from .044 and 0.1 strength to .444 and 1.0 strength.

**Comment by stackpoint** [comment]
The goal is to remove the anti-tank gun from CEP completely. What version of CEP are you running and what unit upgraded into the ATG?

**Comment by Seredin** [comment]
Version 3.15.1 as per the title of the post, downloaded from https://github.com/Thalassicus/cep-bnw/releases/tag/3.15.1, and installed manually with standard practice (for me) deletion of cache/moduserdata/saves/moddedsaves folders before running the game. The 3.15.1 version has run quite smoothly with the exception of that one glaring oddity of the ancient ruins "upgrade" to ATG over the course of two games. The only mods in use were the 4 communitas mods (CAI,  CEG, C Interface, C Map). 

I have since deleted the games, so I cannot with any certainty give you the exact unit name which was upgraded via the ancient ruins into the Anti Tank Gun. My apologies about that. I assumed incorrectly that the previous (but no longer in use) promotion pathway for anti tank guns was a known sequence.

**Comment by Thalassicus** [comment]
It was probably a Lancer. I changed it the same upgrade path as Cavalry now.
