### ISSUE TITLE
Is there a current timeline for tooltip / description updates?

### ISSUE THREAD

**Issue by Seredin** [Thalassicus/cep-bnw#222]
First of all, I'd just like to say that this project and its collaborators have done amazing work transforming and continually improving the game. I understand there is currently a project in progress to make the game descriptions auto generate based on actual effects of each wonder, etc.  My question is simply where in the priority queue is this effort?

Currently, many of the wonders descriptions upon completion do not match the research tree descriptions which also do not match the actual in-game effects. This lack of clarity detracts from the game play decision making process, and overall feel of the quality of this amazing mod in a significant way. It's hard to plan a strategy when you can't be certain what each option actually does.

**Comment by stackpoint** [comment]
Does the incorrect wonder effect text appear anywhere else other than on the completion of the wonder? I understand that strategy will be affected by the wonder effect so please let us know.

That specific wonder text has been low priority since I believe it only appears on completion of the wonder. We should however, blank the text out so the contradicting effects don't appear at all

**Comment by GrantSP** [comment]
**ALL** buildings, including the Wonders, should have correct TooltipWritten text inside the pedia and the production queue.
Nothing fancy or constructed in the form of a sentence, just the basic gist of what it does.
At the time of release, excluding our custom Wonders like Wat Phra Kaew, only a handful of vanilla Wonders have their TXT_KEYs with new text.
This text is the one that ends in _HELP. This is the text that displays on the splash screen upon completion.
Unfortunately, the tooltip written format doesn't fit properly in this space and flows off the bottom of the panel in an ugly manner.
Stonehenge in particular is very ugly. Part of the reason that prompted me to start this issue #75 
As that issue shows I stopped after @Thalassicus prompted me to drop it in favour of going with the tooltip writer.

Perhaps we should add a line in the code to blank all the _HELP text and just have the graphic display?

**Comment by stackpoint** [comment]
Yeah, we should use sql to assign all the wonder help fields to TXT_KEY_GENERIC until further notice.

**Comment by GrantSP** [comment]
I've added a NULL command to my copy and I am about to test it to see if any issues arise.
I'm 99% sure the problem we had with Units having an empty HELP field wont affect the buildings if we just NULL them. Many buildings already have a NULL HELP field.

**Comment by stackpoint** [comment]
Having a NULL help will only be a problem if the LUA calls on the help field in question.

**Comment by GrantSP** [comment]
I have a brain like a sieve sometimes.
It was precisely the reason Stonehenge's HELP field was a NULL that prompted me to look at the wonder splash text.
It is when this filed is NULL that the tooltip written text displays (poorly) and makes the splash screens look weird.
So I have placed a sql command to point to TXT_KEY_GENERIC and it works fine.
Each splash now has the small historical snippet shown to the left and an empty field to the right with just the name of the wonder.
