### ISSUE TITLE
City Unrest

### ISSUE THREAD

**Issue by GrantSP** [Thalassicus/cep-bnw#224]
[This issue on CivFanatics](http://forums.civfanatics.com/showthread.php?t=522826)  looks like it needs urgent attention. Most of my latest games have been very peaceful as I have been looking into building production and UI elements so I can't say I have noticed this. If however it is as described it is a major bug.

**Comment by stackpoint** [comment]
This was Thal's intended design goal since the Mercy/Force options were introduced 6 months ago. You should be able to find several posts on the forum by him describing his intentions with the options.

Mercy - No population loss, No unrest
Force  - Half population loss, Unrest equal to new population

**Comment by GrantSP** [comment]
Apologies, I do vaguely remember something about it.
I still think we need to re-examine it.
The end result is not giving a good experience. Too many variables at play
in conquest. The overall results are not what I think Thal was after.

**Comment by stackpoint** [comment]
I'm not going to argue the merits of the current system here. However, I've taken an extensive look at the mechanics of this system while trying to solve the various auto-annexing bugs so I'm pretty familiar with the code.

Find the thread with Thal's explanation and open it up for discussion again and I'll make any changes from that. The main things we can change is the amount of population lost and the unrest period.

**Comment by GrantSP** [comment]
Sounds good. Will do.
