### ISSUE TITLE
No upgrade path for Landsknechts from Wealth Social Policy 

### ISSUE THREAD

**Issue by p0rkjello** [Thalassicus/cep-bnw#225]
No upgrade path for Landsknechts from Wealth Social Policy.

**Comment by GrantSP** [comment]
I think the greater problem here isn't so much the lack of an upgrade path but rather the fact these units are next to useless compared to contemporary units. They have the worst stats for any unit that appears in this era, and are quickly overtaken in usefulness by units unlocked very soon.

Perhaps we should again examine alternatives for this particular policy. If we keep these units, then by all means let's buff them and give them something to upgrade to.

**Comment by stackpoint** [comment]
Sounds like both are a problem. Increase the strength of the unit and let it promote it into the melee line.

**Comment by Thalassicus** [comment]
Landsknechts are also incredibly complex with too many different effects and promotions. I don't like them. I've never seen a good idea for how to replace them, however. In the short term, I've given them the same upgrade path as pikemen.
