### ISSUE TITLE
Quick and easy improvements

### ISSUE THREAD

**Issue by Thalassicus** [Thalassicus/cep-bnw#227]
Some things I found while playing:

**AI**
- [x] Increase AIFreeXPPercent to help successful military AIs. 856783115682862f23a2e8edf9d1f30b4c69a54d

**Cities**
- [x] Increase income from connecting cities of less than 10 population. 754a472b0cec849eaed94f3bd1eeb19d6190991f
- [x] Land trade income is now approximately equal to sea trade income (but still less range and can't cross water). 754a472b0cec849eaed94f3bd1eeb19d6190991f
- [x] Reduce cost of courthouse to make conquest more appealing. 754a472b0cec849eaed94f3bd1eeb19d6190991f
- [x] Reduce puppet science and culture penalties. 754a472b0cec849eaed94f3bd1eeb19d6190991f
- [x] Increase odds of science building destruction upon city capture. 754a472b0cec849eaed94f3bd1eeb19d6190991f
  **Leaders**
- [x] Increase Legion cost and strength by +5%. 06bdadb223b6b09c7607a38c9813132713391042

**Interface**
- [x] Visually rearrange the Piety tree to bring more attention to under-used policies. c81364d29e524fe74b60d829927e20d81789cf48
- [x] Discipline effect no longer shows over units. (since all units in the army get the identical effect) 118fb930bfcbc110bc70ac5136af2494e95e6ba6

**Research**
- [x] Increase rewards from Research Agreements. f1415131eed06c6dd9d26540f215055a95ca2ca1

**Terrain**
- [x] Great Improvements connect resources for trade. 856783115682862f23a2e8edf9d1f30b4c69a54d

**Misc**
- [x] Citystates give yields when captured, as intended. 856783115682862f23a2e8edf9d1f30b4c69a54d
- [x] Purchasing something in a city does not close the production panel. (Helps for multiple purchases) 856783115682862f23a2e8edf9d1f30b4c69a54d
- [x] Fix function AIMilitaryHandicapPerTurn by multiplying "odds" times 100. 856783115682862f23a2e8edf9d1f30b4c69a54d
- [x] Correct the Piety opener to show intended effects. c81364d29e524fe74b60d829927e20d81789cf48
- [x] Fix Peace Gardens belief tooltip.
- [x] Fix a bug allowing Admirals to cross oceans in the ancient era. 118fb930bfcbc110bc70ac5136af2494e95e6ba6
- [x] Fix the mismatch between CAT and CEG unit flavors. 118fb930bfcbc110bc70ac5136af2494e95e6ba6
- [x] Isles are only a line-of-sight obstacle for ships. 118fb930bfcbc110bc70ac5136af2494e95e6ba6

**Comment by GrantSP** [comment]
I'll piggy-back onto this issue.
When you upgrade a unit there is a blue text that rises from it that says something like:

"+45 XP"

Clearly the unit isn't gaining experience from upgrading so what exactly is this figure doing and can we use it to actually do something useful or at the worst, disable it?

**Comment by Thalassicus** [comment]
When a unit upgrades, the game does these steps:

1) Create a new unit.
2) Copy stats from old unit to new.
3) Delete the old unit.

The new unit starts at 0 xp, and gains xp from the old unit in step 2, displaying that text. I suspect the new unit doesn't know it's a clone. This happens whenever we embark or disembark a unit too: it clones the original, then kills it. Sorta like ideas about cloning, teleportation, or brain-uploading in science fiction.

Most interface stuff is done in Lua, so it **might** be possible to stop the visuals when a new unit gets XP. We'd have to replace the text-displaying function with our new one, which would accept an "isUpgrading" parameter... and if this function is defined in the game core, without linking to a class we can easily access, we'd need to create a c++ module to replace it.

**Comment by Thalassicus** [comment]
Done with the changes.
