### ISSUE TITLE
3.8 Churches of Labibela

### ISSUE THREAD

**Issue by wolverine2112** [Thalassicus/cep-bnw#24]
I didn't build it, but it says it gives a great artist still.

**Comment by stackpoint** [comment]
Could you please describe the issue in a little bit more detail?

**Comment by wolverine2112** [comment]
It still gives a great person point...great artist. At least it says that in the text tree.

Sent from my Virgin Mobile Android-Powered Device

----- Reply message -----

**Comment by stackpoint** [comment]
It seems like there were artist/writer/musician points/slots added to various wonders in CEP. This might be a more of a balance/mechanics discussion more than anything else.

**Comment by wolverine2112** [comment]
I guess I don't understand ...where would the great artist point go?  Does it just have no value?

**Comment by wolverine2112** [comment]
Oh wait..lol...there are great artists still. Haha.  If its as intended then you can close this. sorry.

**Comment by stackpoint** [comment]
We can reopen this if there's discussion on the main forums about it.
