### ISSUE TITLE
Belief text

### ISSUE THREAD

**Issue by Thalassicus** [Thalassicus/cep-bnw#241]
Update belief text to follow the "[ICON] Text" standard.

**Comment by Thalassicus** [comment]
Mostly done with this in commit 0ebc8e1176181b78acde542c54e6a3ab07ea4cd0

**Comment by GrantSP** [comment]
Why is the address of that spreadsheet different to the one I modified?
Are we getting different addresses depending on who looks at it?

**Comment by Thalassicus** [comment]
Oh! I forgot we replaced the file, and I was following my original link.

**Comment by GrantSP** [comment]
That's a relief.
If you haven't updated the spreadsheet with those changes I can do so tomorrow. At the moment I have flaky internet and Google isn't allowing me to update that file. The new month should fix that.
