### ISSUE TITLE
Establishing a Stable release

### ISSUE THREAD

**Issue by GrantSP** [Thalassicus/cep-bnw#242]
Before we progress any further with these minor changes and additions, can we at least get the new-features version to a stage were it can replace the current stable version?

The localized text alone means the merge itself won't be an easy one, although @stackpoint did manage to make the new-features branch work with apparently little effort.

The stable version doesn't reflect the state of the mod used by a vast number of users, Steam users excepted.

**Comment by Thalassicus** [comment]
I'm ready to release the update when you are. I played through a game the past week and solved all the issues I found. :thumbsup:

I tackle small tasks when getting involved in a project again. Playing a match of Civ and making quick-win changes are the best way for me to get excited and motivated for the work.

I agree we need to get the new-features version out there for everyone to play. For reference about demographics, there's 48,500 people currently subscribed to the stable CAT version on the workshop from 106,800 unique visitors, a respectable views-to-subscribers ratio for our project. There's 1,200 unique downloaders of the last stable release on github, and under a hundred people with the new-feature versions downloaded or cloned to their desktop.

**Comment by GrantSP** [comment]
I also released that version on CivFanatics so the number of users is greater again than those figures.
Anyway we look at it, the most users come to this mod via Steam and you are the only one with access to that distribution method, if the same mod page is kept. It might be possible to make a new mod page on Steam using a communal email address recorded in Steam but I think the problems that that would bring far outweigh **any** benefit from having other contributors gain access to that distribution method.

Welcome back. :smiley:

**Comment by Thalassicus** [comment]
The civfanatics pages should no longer need to be updated. I'm relatively sure I genericised those by linking to the github releases page. This lets us update the project just 2 places: github and steam.
