### ISSUE TITLE
Set new-features branch as default

### ISSUE THREAD

**Issue by GrantSP** [Thalassicus/cep-bnw#249]
This is not an issue!!!!

@Thalassicus could you, since you are the owner of the repo, set the branch **'new-features'** as the default?
Since most work is done in this branch and most of the time users of the code will move in and out of its directories, setting it as default will eliminate the need to select it each time from the drop-down selection box, when we move back to the "Code" tab.
The extra step for us isn't great but can eliminate needless commits to the **'stable'** branch when it was chosen by mistake.
This only ever is a problem with simple code-edits in the browser, not commits from the app.

**Comment by Thalassicus** [comment]
Done.
