### ISSUE TITLE
Need to fix TECH_NULL in spreadsheet

### ISSUE THREAD

**Issue by stackpoint** [Thalassicus/cep-bnw#25]
I fixed a PrereqTech issue with the Shrine being set to TECH_NULL instead of NULL. However, the code is automatically generated using a [google spreadsheet](https://docs.google.com/spreadsheet/ccc?key=0Ap8Ehya83q19dDE2TURZSnJSdzE2REx3XzNPY3RVZmc) and I don't know how to fix the spreadsheet so that it doesn't generate the TECH_ prefix in front of NULL.

See the following commit for more information: https://github.com/Thalassicus/cep-bnw/commit/56efc194199b247f8c5d5377081c1f78bf35b043

**Comment by GrantSP** [comment]
I'll take that. Should be just a cell reference that needs changing.

**Comment by GrantSP** [comment]
Well I was going to but it looks I don't have editing rights on that file.
All we have to do is change the formula in Cell I47 to not add in TECH_
It joins that to the data from Cell C47
It would be good if all the collaborators have access.

**Comment by stackpoint** [comment]
You have to join the group: https://github.com/Thalassicus/cep-bnw/issues/6#issuecomment-28624815

**Comment by GrantSP** [comment]
Thanks. Didn't see that.

**Comment by stackpoint** [comment]
I'll close this for now.
