### ISSUE TITLE
Upcoming release

### ISSUE THREAD

**Issue by Thalassicus** [Thalassicus/cep-bnw#256]
I completed all remaining issues for the [v3.16 milestone](https://github.com/Thalassicus/cep-bnw/issues/milestones). I'd like to release this by Wednesday. Please update the [release notes](https://github.com/Thalassicus/cep-bnw/releases/tag/untagged-ddf3f03848055f820b3e) if you see anything missing. Good job everyone!

I moved most remaining issues that are not easily solved into the [v3.17 milestone](https://github.com/Thalassicus/cep-bnw/issues/milestones) for next time.

**Comment by GrantSP** [comment]
Just a point, and this is probably my mistake, there is already a [3.15 release](https://github.com/Thalassicus/cep-bnw/releases/tag/3.15.1)
When the text re-structure was completed I released it as a **pre-release** along with a minor update taking it to 3.15.1.

This next release should, at the least, be **3.16**

Sorry for the mixup.

**Comment by Thalassicus** [comment]
It's no problem, the milestones are easily renamed. :thumbsup:
