### ISSUE TITLE
3.16 LUA Error

### ISSUE THREAD

**Issue by ghost** [Thalassicus/cep-bnw#261]
Just fired up a game and played a few turns and checked the LUA log and found this entry a couple times:

Runtime Error: \Users\WarEagleUser\Documents\Aspyr\Sid Meier's Civilization 5\MODS\Communitas AI and Tools (v 3)\AI\CEAI_Events.lua:176: attempt to call global 'PurchaseUnitOfFlavor' (a nil value)

**Comment by GrantSP** [comment]
Can you provide a bit more detail? What civs were involved, map size, other mods, etc.
I cannot replicate this without further background.
The game I just loaded using the latest release, as opposed to a build from source, works with no errors at all.

**Comment by ghost** [comment]
Just did another game and had the same error.  It was epic speed, standard size communitas map, 6 civs (Korea, Byzantine, Greece, Aztecs, Vikings, India (Me)), using info addict light, colored religions, city limits, and EUI in addition to 3.16.

**Comment by GrantSP** [comment]
Interesting.
So you prefer City Limits' CityView.lua over EUI?
InfoAddict or the lite version shouldn't have any impact, neither should Coloured Religions.

I'll set up a game with the same details minus the mods I don't have and see what happens.

**Comment by ghost** [comment]
I just started using EUI i did not know it had the same capabilities!  Attached is my latest lua.log.
![lua](https://cloud.githubusercontent.com/assets/6225004/2688595/083e4272-c2b2-11e3-9def-1e2ddcda9cd1.jpg)

**Comment by GrantSP** [comment]
Can you give me a copy of your CEG_Options.sql or at the least tell me what you have selected in it?
The logs show it isn't loading in your game.

**Comment by ghost** [comment]
Here is my CEG_Options.sql

![ceg_options](https://cloud.githubusercontent.com/assets/6225004/2688691/0381e0fa-c2c0-11e3-8399-d85524a373d8.jpg)

**Comment by ghost** [comment]
Here is another lua.log file from a game i played a little while longer.

![lua](https://cloud.githubusercontent.com/assets/6225004/2688697/8d4e6fb0-c2c0-11e3-8317-aa0c8f6c1e35.jpg)

**Comment by GrantSP** [comment]
OK found it.
The commit that fixes it can been seen [here](https://github.com/Thalassicus/cep-bnw/commit/1663df2a53b5e74baf28bdb878fb86a003e8a422).
You can either edit the **CEAI_Events.lua** yourself, copy the file from the repo or compile a new build from source.
It's just the *.lua file, the other file just happened to be committed at the same time.

**Comment by GrantSP** [comment]
I forgot to mention, you are missing a ) at the end of one of the lines in your CEG_Options.sql.
After the Barbarians upgrade I think. 
Currently away from my computer.

**Comment by ghost** [comment]
Thanks!
