### ISSUE TITLE
Game Crashes when trying to start a game.

### ISSUE THREAD

**Issue by axtscz** [Thalassicus/cep-bnw#264]
I've been having this problem where whenever I try to start a game with CEP, the game crashes. This used to happen to me when I tried to load up a saved game that I had started with CEP, but know it happens when trying to start a modded game.

EDIT: Do you want the minidump log?

**Comment by GrantSP** [comment]
Make sure your system is completely up-to-date with the game engine.
This is the most likely reason for the crashing.
**If** it persists then follow these steps and provide us with the logs from the **logs** folder.
1) Clear your **cache** and **moduserdata** folders.
2) Start a game with **ONLY** the CEP modules selected and see if the problem persists.
3) Add half of the other mods you have and see if the problem returns.
4) Repeat steps 1 & 2 and the **OTHER** half of you mods.
5) Keep repeating these steps and each time **half** the group of mods that results in the error until you have only that mod and CEP loaded.

**Comment by axtscz** [comment]
Did all this and came up with a halfway solution. If I disable the Interface module, I can load up a new game. Then I can play until about the 50th turn and then the game crashes.

**Comment by Thalassicus** [comment]
Crashes are usually not caused by things that can be solved through the normal methods (clearing the cache and such). Crashes are extraordinary rare and often hard to figure out. I've been encountering a crash like you describe, but this one seems to be caused by something in AI & Tools. I'm trying to narrow down the problem.

**Comment by GrantSP** [comment]
Do you have either CSD or Whoward's DLL mod installed?

**Comment by axtscz** [comment]
No but i do have info addict and perfectworld 3

**Comment by GrantSP** [comment]
Infoaddict is known to cause a crash on exit, in some circumstances. #180 
Perhaps your setup is triggering that crash at other times too.
Try disabling it. Although it is helpful the details it provides may not be 100% accurate anyway with the YieldLibrary we use changing some yields slightly.

**Comment by axtscz** [comment]
OK, running just CEP and the modules works, thanks!
