### ISSUE TITLE
[3.16] Problems with notifications - incompatibility

### ISSUE THREAD

**Issue by skodkim** [Thalassicus/cep-bnw#265]
I'm having a problem with notifications not showing up in the game screen. Have never seen this before but from the log file it seems the mod is now incompatible with the Emigration mod (running a lot of other mods as well :blush: ).

Running current new features build (3.16 with fixes).

Any ideas?

![lua log](https://cloud.githubusercontent.com/assets/6018459/2700073/faed40f6-c40e-11e3-884b-e46081550307.jpg)

\Skodkim

**Comment by skodkim** [comment]
Actually the problem is the same with other mods that "fiddle" with notifications, e.g. UI - Notification Options (GK) (v 12)

\Skodkim

![lua log](https://cloud.githubusercontent.com/assets/6018459/2716344/04c2e2ba-c528-11e3-8d91-8dae0a7a63eb.jpg)

**Comment by GrantSP** [comment]
Don't you have BNW?

**Comment by skodkim** [comment]
Yes

On 16. apr. 2014 07.34.11 CEST, GrantSP notifications@github.com wrote:

> Don't you have BNW?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Thalassicus/cep-bnw/issues/265#issuecomment-40564629

## 

Sendt fra min Android telefon med K-9 Mail. Undskyld hvis jeg er lidt kortfattet.

**Comment by skodkim** [comment]
Ohh, I see where you're going here! Sorry about the last post.

Emigration mod is updated to BNW and I suppose the notifications "module" in there should be too but it isn't really that important and I'll just close the issue :smile:

**Comment by GrantSP** [comment]
Actually I was going to ask why does your version of **UI - Notification Options (GK) (v 12)** specify the (GK) as in (Gods & Kings). The copy of I have makes no distinction.
I was assuming that was the G&K version and you needed a new update.
