### ISSUE TITLE
[3.16_NF] dll incompatibility introduced 

### ISSUE THREAD

**Issue by skodkim** [Thalassicus/cep-bnw#269]
Hi

I've been using Whowards dll without any problems for the last six months or so. Today I made a New Features build and all of a sudden the game crashes to desktop when I start a new game. The thing is that it did nont happen when using a New Features Build from yesterday, i.e. I think it must be related to one of the following commits:

https://github.com/Thalassicus/cep-bnw/commit/d4e568db7bd50257ae8a6dfc08a97b51bf03b3bd
https://github.com/Thalassicus/cep-bnw/commit/d074c8daefa6eaa4195db5efbbed6e5eeff92f92
https://github.com/Thalassicus/cep-bnw/commit/a0f24cc82fd05ed2b1bfff411f276e8ef7ace176

Whoward thinks we may have intoduced a "divide by zero" error somewhere: http://forums.civfanatics.com/showpost.php?p=13172274&postcount=130

Oh, and I should say that it doesn't happen without the dll mod (but I't be sorry to loose compaibility!)

\Skodkim

**Comment by GrantSP** [comment]
Is this DLL the same as the one in CSD because since v22 I have been having
crashes.
I installed that mod last month and have been having intermittent crashes.

**Comment by skodkim** [comment]
I don't know. I **think** CSD is made directly from the standard BNW dll while Whowards also includes CSD's changes.

The crash I'm seeing happens right after I select civ, map type, etc. and select the "start game" button,

\Skodkim

**Comment by GrantSP** [comment]
Hmm...
My crashes are more random.

**Comment by skodkim** [comment]
Actually I don't know if this is related but we seem to have introduced some syntax errors.

\Skodkim

![stopwatch log](https://cloud.githubusercontent.com/assets/6018459/2716241/d614f8de-c524-11e3-9e7e-19c426cb9aee.jpg)
![database log](https://cloud.githubusercontent.com/assets/6018459/2716242/d61525b6-c524-11e3-99c4-ae96be53bf4d.jpg)

**Comment by skodkim** [comment]
I can confirm that the syntax error is in one of the **leader related** files from the above mentioned commits. Reverting these changes also solves the crash issue.

\Skodkim

**Comment by GrantSP** [comment]
Apart from the lack of a ";" at the last line of **CEAI_LeaderPersonalities.sql** are there any other places you can see?

I don't think these are the cause of the crashes. I was experiencing crashes long before these changes were made.

**Comment by skodkim** [comment]
I haven't been able to identify the locations but stopwatch.log helped me narrow it down to these files (which were also in the commits). I solves the consistant crash I was experiencing, but that was another crash than yours (consistant crash at start if game). This crash was only seen with Whowards dll activated - somehow it must be more sensitive to the changes in the commits.

\Skodkim

**Comment by skodkim** [comment]
Just updated CEAI_LeaderPersonalities.sql with the missing ";" (CAT and CEG copy) and tried starting a new game again.

Same result: Immediate CTD and same error messages in the log file.

**Comment by GrantSP** [comment]
See this issue #264

**Comment by skodkim** [comment]
Yeah, I already saw this but since my crash doesn't seem to happen without whowards dll and is with a non-official release from the new features brach I'm guessing its not related.

**Comment by GrantSP** [comment]
Wow. Just built the latest release and had only Communitas with nothing else and couldn't even get past the setup screen.

**Comment by skodkim** [comment]
Yes... (but I was kind of confident this only happened with Whowards dll..?)

**Comment by GrantSP** [comment]
There's a file in the Project file that is incorrectly set: **MultiUnitFormations.xml**

Either it is in there by mistake or it isn't fully defined in the project.
It is in the GitHub repo but doesn't get inserted into the built directory.

**Comment by skodkim** [comment]
I don’t think that’s it.

If I take the newest build and replace the two leader\* sql files (both in CAT and CEG) with older versions it works (for me). I **must** be those two files.

Fra: GrantSP [mailto:notifications@github.com] 
Sendt: 16. april 2014 08:08
Til: Thalassicus/cep-bnw
Cc: skodkim
Emne: Re: [cep-bnw] [3.16_NF] dll incompatibility introduced (#269)

There's a file in the Project file that is incorrectly set: MultiUnitFormations.xml

Either it is in there by mistake or it isn't fully defined in the project.
It is in the GitHub repo but doesn't get inserted into the built directory.

**Comment by GrantSP** [comment]
Yeah you're right, that didn't work. Still it shouldn't have been there, no reason why we can't clean up as we go. :smiley: 

I **WILL** find this before the night is through. I am determined.

Okay most of the lines in those files are similar so most likely it is tripping on the first occurrence.
Let's start looking.

**Comment by GrantSP** [comment]
Ok the **CEAI_LeaderFlavors.sql** aren't loading, now to find out why.

**Comment by GrantSP** [comment]
Think I've got it.
This is the way the SQL is structured in each of those files:

```
INSERT OR REPLACE INTO Leader_Flavors(FlavorType, LeaderType, Flavor) SELECT ('FLAVOR_MILITARY_TRAINING', LeaderType, 8) FROM Leaders WHERE Personality = 'PERSONALITY_CONQUEROR';
```

The trouble here is it is looking for the column _LeaderType_ in the **Leaders** table when it should be just _Type_.
Secondly the parantheses in the SELECT part of the statement are not needed. At least it baulks at working when inserted into SQLiteSpy one line at a time.

I've made those changes in my copy and I am just about to try.

**Comment by GrantSP** [comment]
Success!
I'll see if I can make changes to the spreadsheet.
In the meantime I will post the commits immediately.

**Comment by skodkim** [comment]
Great news!

On 16. apr. 2014 09.17.28 CEST, GrantSP notifications@github.com wrote:

> Success!
> I'll see if I can make changes to the spreadsheet.
> In the meantime I will post the commits immediately.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Thalassicus/cep-bnw/issues/269#issuecomment-40569916

## 

Sendt fra min Android telefon med K-9 Mail. Undskyld hvis jeg er lidt kortfattet.

**Comment by GrantSP** [comment]
hmm... It looks like @Thalassicus may have already seen the mistake in the spreadsheet and corrected it but forgot to update the repo.

Needs a bit of smoothing over...

At any rate I believe we are good to go from here.
Just copied the data from the spreadsheet into my editor and it looks fine

The commit is [here](https://github.com/Thalassicus/cep-bnw/commit/9232ee1679fabac2647ead0b0a1cbcdf91fa3573)

It is only the **CEAI_LeaderFlavors.sql** files that are important, the other stuff are just edits in my queue.
