### ISSUE TITLE
CEC_END questions

### ISSUE THREAD

**Issue by gdwitt** [Thalassicus/cep-bnw#27]
What does this do in GEM end?
I deleted it and nothing seemed to change in terms of buildtime, production cost or hurry cost

UPDATE Buildings
SET Cost = ROUND(Cost / 50, 0) \* 50
WHERE Cost > 0;

UPDATE Projects
SET Cost = ROUND(Cost / 50, 0) \* 50
WHERE Cost > 0;

Additionally, what is the necessity of  Buildings tab of GEM_Details.xls spreadsheet.
There are about 40 lines that appear to modify buildings.
Is that modifying maintenance cost or construction time or both?

Finally, the two seem to contradict each other. First we adjust costs, then we override them all.

I ask because I have my own mod for construction-production and I would rather use it if these are relics of GEM.

**Comment by stackpoint** [comment]
Both code are used. The first segment of code you posted rounds the cost to the nearest 50 and the code in spreadsheet adjusts the overall values. Cost is the cost of the building in production.
