### ISSUE TITLE
Some UU/UB issues: Greek Odeon, German Hanse, and German Panzer

### ISSUE THREAD

**Issue by Spheniscine** [Thalassicus/cep-bnw#274]
Odeon is strange; no base culture-per-turn, and costs more to maintain? Is the strategy to raze and rebuild over and over for the flat culture bonus?

Hanse seems to lack its special ability (+5% prod. per city-state trade route in empire), or is it just a display issue?

Panzer seems OP, having same strength as Modern Armor (next upgrade), in fact Modern Armor seems to be a downgrade, as has only 5 moves to Panzer's 6 while having same strength.

**Comment by GrantSP** [comment]
Yes I agree, Odeon is strange, we need to put some sort of per-turn yield. Nice strategy though.

Hanse is just a display issue, we haven't done anything with that building.

Panzer issue has been raised many times and knocked back by @Thalassicus at every turn. Last time I raised it here #204 the end result was a reduction in it's strength.

**Comment by Spheniscine** [comment]
From the discussion in #204 it would appear that the Panzer issue has been resolved.

As for Odeon I think it should simply restore the cpt yield and gpt maintenance of the Theater. Most UBs, especially the 'instant yield' ones (see Vedi) are all-upside.

**Comment by GrantSP** [comment]
Odeon fixed in next release.
