### ISSUE TITLE
[3.16] Gp text string

### ISSUE THREAD

**Issue by skodkim** [Thalassicus/cep-bnw#277]
All text strings from GP (Great Engineer, Great Artist, ...) seem to show up as TXT_KEY_UNIT_...
![civ5screen0000](https://cloud.githubusercontent.com/assets/6018459/2886960/c397d450-d4f2-11e3-9d31-c2dbac5ece05.jpg)
![civ5screen0002](https://cloud.githubusercontent.com/assets/6018459/2886961/c399537a-d4f2-11e3-8a78-e10d96914e0b.jpg)

**Comment by GrantSP** [comment]
What do have installed that recently that has changed your setup? I have been using the latest build and CSD for quite a while and have not seen this.

**Comment by GrantSP** [comment]
Can't replicate.
