### ISSUE TITLE
Gladiators Policy Bug

### ISSUE THREAD

**Issue by EricB1** [Thalassicus/cep-bnw#279]
The Gladiators policy doesn't give any free units like it's supposed to.  Looking at the code, it's clear that the issue is the line IncludesOneShotFreeUnits isn't set to true for that policy.

Is this a known bug?  If you would like, I can fix it and sync it.  Just don't want to step on anyone's toes.

**Comment by GrantSP** [comment]
The only toes left are yours and mine I think.
