### ISSUE TITLE
Monasteries description change

### ISSUE THREAD

**Issue by Hawawaa** [Thalassicus/cep-bnw#28]
Right now the description takes up 3 lines and spills over. Here is my change to it-

Monasteries
Faith buildable Science Monasteries: 4(S), 1(F), 1(C)

**Comment by stackpoint** [comment]
Right now the description is:

``` xml
Can build [ICON_RESEARCH] Monasteries with faith. [NEWLINE](4 [ICON_RESEARCH] Science, 1 [ICON_PEACE] Faith, 1 [ICON_CULTURE] Culture)
```

This format fits the format that the rest of the religious beliefs follow. However, to address the overflow, we can remove the "Science", "Faith" and "Culture" text from the description.

**Comment by Hawawaa** [comment]
That will do.

**Comment by GrantSP** [comment]
Perhaps removing the [NEWLINE] would allow it to flow better.
