### ISSUE TITLE
Embarked units on land

### ISSUE THREAD

**Issue by qqqbbb** [Thalassicus/cep-bnw#282]
![embarked 20unit 20bug 1](https://cloud.githubusercontent.com/assets/6333704/3142756/fbbf6016-e9d1-11e3-9c33-59062ebc2c91.jpg)

Save file and log: https://dl.dropboxusercontent.com/u/28753474/embarked%20units%20bug.rar

**Comment by qqqbbb** [comment]
In another  game I saw not embarked  land units on water tiles.

**Comment by GrantSP** [comment]
The code that handles the graphics is not something that this mod handles, or sees a need to.

What you are seeing are simply graphical glitches that might occur in ANY game, modded or not.

**Comment by qqqbbb** [comment]
It's not just a graphics bug. Look at screenshot, the game thinks that unit is embarked.

**Comment by GrantSP** [comment]
That maybe true, but it still isn't a result of the mod, in my opinion. 

As I  said elsewhere, I can't get to my game system for some time yet and as it looks like I'm the last man standing, well I can't promise anything.
