### ISSUE TITLE
Skip city attack

### ISSUE THREAD

**Issue by qqqbbb** [Thalassicus/cep-bnw#285]
Sometimes you don't want to city attack a low HP enemy unit so that one of your units ( that  currently  has 0 MP) can kill it next turn  to get experience.

**Comment by GrantSP** [comment]
I don't understand, what exactly is the issue?

**Comment by qqqbbb** [comment]
The issue is your units don't get experience  if your cities kill enemy units. I edited my first comment, it should  be more clear now.

**Comment by GrantSP** [comment]
If I am understanding what you are saying, this isn't an 'issue' as such, it is more along the lines of 'how you play the game'.
There is no gameplay issue at work here. If you don't want to kill that unit with the city attack, don't. The game is not halted in anyway, there isn't a bug that needs to be fixed.
If the enemy unit comes into view you can gauge how many attacks will be needed to remove it and plan  your attacks accordingly. City first, then any garrisoned troops, then any ranged units nearby and lastly a melee unit if needed.
