### ISSUE TITLE
Tech Tree descriptions changes

### ISSUE THREAD

**Issue by Hawawaa** [Thalassicus/cep-bnw#29]
Ok I'll be updating this as I find them. If this isn't the right format please correct me. 
1. Future Tech description
   In the tech tree screen for some weird reason the Marine and Anti-Tank Gun icon are there.
2. Unit descriptions on mouse over- 
   "Animal Husbandry"- Caravan Icon description leave only 1 set of dashes at the top
   "Sailing"- Bireme Icon description leave only 1 set of dashes at the top,
   "Archery" Archer Icon description leave only 1 set of dashes at the top
   "The Wheel" Chariot Archer Icon description leave only 1 set of dashes at the top
   "Mathematics" Catapult Icon description leave only 1 set of dashes at the top
   "Civil Service" Landsknecht Icon description leave only 1 set of dashes at the top
   "Machinery" Chu-Ko-Nu Icon description leave only 1 set of dashes at the top
   "Physics" Trebuchet Icon description leave only 1 set of dashes at the top
   "Gunpowder" Arquebusier Icon description leave only 1 set of dashes at the top
   "Archaeology" Archaeologist Icon description leave only 1 set of dashes at the top
   "Smokeless Powder" Musketman Icon description leave only 1 set of dashes at the top
   "Industrialization" Rifleman Icon description leave only 1 set of dashes at the top
   "Dynamite" Artillery Icon description leave only 1 set of dashes at the top
   "Flight" Triplane Icon description leave only 1 set of dashes at the top
   "Combustion" Carrier Icon description leave only 1 set of dashes at the top
   "Rocketry" Rocket Artillery Icon description leave only 1 set of dashes at the top
   "Combined Arms" Airborne Icon description leave only 1 set of dashes at the top
   "Computers" Missile Sub Icon description leave only 1 set of dashes at the top
   "Computers" Bazooka Icon description leave only 1 set of dashes at the top
   "Nuclear Fusion" Xcom Squad Icon description leave only 1 set of dashes at the top but keep Good Luck, Commander! 
   (Double check other unique units/buildings in tech tree)
   (most units have no description and a few do so I'm assuming we are going that route?)
3. Wonder description fixes- 
   "Civil Service" Chichen Itza text error for golden age
   "Printing Press" Taj Mahal text error for golden age
   "Rocketry" Apollo Program add dashes between name and Good for

**Comment by Hawawaa** [comment]
Ok, I think I can actually make time to pitch in now and then to help out. Anyone want to point me in the direction of how to help you guys out on fixing the smaller stuff like this. 

I joined the google drive group and here you guys have a Skype?  I'll also assume Notepad++ will do the job.

**Comment by stackpoint** [comment]
I sent you an email @Hawawaa.

**Comment by GrantSP** [comment]
If you are asking about what tools you might need then I can also suggest you get SQLiteSpy http://www.yunqa.de/delphi/doku.php/products/sqlitespy/index. It is helpful for looking into the database after all the changes have been made and seeing where/how everything fits together.

A good text editor is essential.
A reasonable understanding of SQL/XML.
An ability to be wrong and still keep going. (I find this one very helpful)
But for the most part, a desire to help. Which you already have.

As for the points in your first post, I believe the actual format of the text used in the tooltips is defined in InfoTooltipInclude.lua. So have a look through that file and see what you make of it.

**Comment by GrantSP** [comment]
Points 1 & 2 are completed.
I will close this and open a new Issue regarding Wonder descriptions.
As new wonders are modified we can keep an eye on which ones are lacking their pedia & splash text updates
