### ISSUE TITLE
Text placed in the Localization database. 

### ISSUE THREAD

**Issue by GrantSP** [Thalassicus/cep-bnw#30]
I have been doing a bit of experimentation on the TXT_KEY entries and I believe I know how to ensure they get loaded into the correct database.
All the text in the core game are defined in:
... < Gamedata>... ... < Language_en_US> ...or your local language.
We currently are not defining our text to be in the ...< Language_en_US>... table.
If we change this then alot of the db loading will be shuffled onto another database. As we translate the text more and more this will become even more necessary. 
I'm not sure yet how to structure our sql to focus on this table rather than the current. If it proves to be too tricky a switch to xml isn't all that much of a problem. 

I'm not sure how many notifications this generated, it is very hard to get this formated correctly on a phone. Sorry.

**Comment by Thalassicus** [comment]
I don't understand your question?

The steps basically are:
1. add text to temporary language tables
2. move the more recent text to the main language table

This way if someone translates the text, but the meaning changes later, the more recent and accurate English version gets displayed.

---
1. The translation for TXT_KEY_GOOD_FOR_RANKS adds to two temporary tables:

``` sql
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality)
VALUES (date('2013-08-26'), 'TXT_KEY_GOOD_FOR_RANKS', 'Good For', '', '');

INSERT INTO Cep_Language_DE_DE (DateModified, Tag, Text, Gender, Plurality)
VALUES (date('2013-08-25'), 'TXT_KEY_GOOD_FOR_RANKS', 'Gut Für', '', '');
```

---

2a. Language_End.sql then moves the English translation into the German table:

``` sql
INSERT OR REPLACE INTO Language_DE_DE (Tag, Text, Gender, Plurality) 
SELECT Tag, Text, Gender, Plurality 
FROM Cep_Language_EN_US 
WHERE EXISTS (SELECT * FROM Cep WHERE Type='LANGUAGE' AND Value='DE_DE');
```

---

2b. If the German translation is more recent, it overrides the English translation:

``` sql
INSERT OR REPLACE INTO Language_DE_DE(Tag, Text, Gender, Plurality) 
SELECT _local.Tag, _local.Text, _local.Gender, _local.Plurality 
FROM Cep_Language_EN_US _en, Cep_Language_DE_DE _local 
WHERE EXISTS (SELECT * FROM Cep WHERE Type='LANGUAGE' AND Value='DE_DE') 
AND (_local.Tag = _en.Tag AND _local.DateModified >= _en.DateModified); 
```

---

There's probably a way to combine steps 2b and 2a to save processing time. The main problem, however, is the database loads all localized translation files, even if it doesn't need them. I haven't figured out an automatic way to fix that. The only solution I can think of is 1. disable all translation folders then 2. end-user enables the folder for their localization.

The game would handle all this automatically, in an ideal world.

**Comment by GrantSP** [comment]
I'll try, but typing on a phone is not as easy as I would like.
All our TXT_KEY entries are, at the moment, ending up inside the game
database, Civ5DebugDatabase, instead of the localized version as is the
case with the vanilla game.
I have found that this is because we have been placing the text inside the
<GameData> database not the <GameData><Language_en_US> where it should go.
This is of course easy to fix in xml files by adding that tag. Fixing sql
files may be a bit fiddly.
Doing so will mean improved load times as not all the TXT_KEYs for each
additional language need to be loaded.
All the vanilla text goes into the LocalizedText table in the Merged db
file. By adding that tag, our TXT_KEY entries also go there.
The "views" we discussed the other day only happen inside the Localization
databases, so our text doesn't even get there at the moment.
When my system gets back online next week l will be able to elaborate more.

**Comment by GrantSP** [comment]
You might see a lot of mods packaged these days with 2 main folders. One
called Database that contains all the code for the change. The other called
Localization with all the language files.
Usually 1 file per language but it can be just 1 file with several
languages divided by their respective tags.
If we adopt a  similar format it may make the distinction more apparent.

As I look closer it looks like the sql commands aren't working outside the
debugdatabase. I'll look more to verify.

**Comment by GrantSP** [comment]
Thal, the point I was trying to make was ALL the TXT_KEY references within the vanilla game are now stored in a different database to the gameplay database. Why was the change made by Firaxis? I can only imagine that there could be some performance issues with all the extra stuff included in it.

The way this mod is structured now is ALL text, of whatever language, is loaded along with everything else into the main gameplay database, Civ5DebugDatabase.db when it doesn't have to!

It is a simple step to change the text being loaded into the correct database if we move away from (if another sql solution can't be found) using the spreadsheet to formulate the files.
If we have all our english text stored on a Google spreadsheet it can still be automatically translated when needed. It just means using that text and inserting it into the correct xml files with the proper location for the text to go.

I can't verify any performance issues, but if this mod eventually has 5 or 6 different languages included in the package, there may well be a degradation of load times IF ALL the languages are in the same database.

As far as I can tell, we are the only major mod that does this with the text location. If it is just a relic from the previous mods, CivUP, VEM etc. then we should re-evaluate it. Firaxis made the change for a reason.

**Comment by GrantSP** [comment]
Ok, let me see if this explains it.

We have included these checks for date etc. so that the game checks to see which is the latest and move that into the default language.
I believe this is redundant if we just load the text into the appropriate localized table.

e.g.
**INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_GOOD_FOR_RANKS', 'Good For', '', '');**

can be changed to:
**UPDATE Language_en_US SET Text = 'Good For' WHERE Tag = 'TXT_KEY_GOOD_FOR_RANKS';**
if the specific TXT_KEY exists or
**INSERT INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_GOOD_FOR_RANKS', 'Good For', '', '');**
if we need to make new ones.

This removes the unnecessary step of loading it into 2 tables and making the date check. If all the text for whichever language is inserted into the localization table along with all the vanilla text, then the game just treats it as it would vanilla stuff. Load the language based on the user's settings and display English if nothing is set in the current language.

Looking at the spreadsheet the Google translation is working pretty well, we just haven't made any other language files. As users that use that language see the text, if needed, they can make changes as necessary.

**Comment by Thalassicus** [comment]
I'm confused. Are you concerned about the English version, local versions, or both? The basic steps for the English version are:
1. add text to Cep_Language_EN_US
2. copy it to Language_en_US

Other languages like German compare the most recent German translation with the English version. If the German version is out of date, it uses the English version instead. This could be done by adding date and "IsModded" fields to all the normal language tables. I wasn't very familiar with altering tables when I created this system. This only affects pregame load times, so I feel it's a low priority to change to a new system.

> we have been placing the text inside the <GameData> database
> not the <GameData><Language_en_US> where it should go.

The first block of Language_End.sql should add the English text to Language_EN_US. 

> if this mod eventually has 5 or 6 different languages included in the package,
> there may well be a degradation of load times IF ALL the languages are in the same database.

Database statements like adding text take a fixed amount of time to process regardless of what table we add it to. I know of two ways to prevent statements from running to reduce load times:
1. cause an error to abort processing a file.
2. give the file a different name than its UpdateDatabase statement, then let the user rename it manually.

I lean towards #2 because I don't know how to automatically detect a user's language, to use that information stop processing a file. I've tried to figure this out many times over the years.
I tried to figure that out. I even asked

**Comment by GrantSP** [comment]
My concern is we are needlessly adding to the gamedata database, performing an action (check the date) then copying the newest data into the localization database. Surely this must have a performance hit, checking each entry against another and then copying it if newer.
I just can not see why we just don't have one file, or set of files, for en_US and another (set) for each other language that is supported.

The game engine handles other language files just fine when they are set up that way, why this extra step? It makes no sense.

I know of no other mod that makes a check of the date of its language files in order to load the most recent.
We have a large enough user base to have all the languages checked if we use Google to translate them first. I have no doubt the forum will run hot with requests to verify the languages.

As usual, I have no evidence to back my belief of degradation in load times. Just a hunch.
If you like I will drop this and you can close this issue. As I appear to be the only one with a problem with it. It will just gnaw away at me until I am 100% convinced one way or the other.

**Comment by GrantSP** [comment]
Ok there is something not working with this.

A French user has translated the Leaders.sql and followed the steps outlined in the [Translations instructions](http://forums.civfanatics.com/showthread.php?t=484767), as have I.

There doesn't appear to be any errors in the sql. The modinfo correctly checks for a file called _Leaders.sql_ in the FR_FR folder, although there wasn't an **Import** listing for the new file.
After adding this listing the French text was correctly added into the CEP_LANGUAGE_FR_FR table.

When I added the French file into the mod however and set my language to French the text that describes the Leader traits was not shown.

Perhaps the calculations that check for the newest text doesn't happen until the game has actually started.

**Comment by GrantSP** [comment]
We are getting closer to a solution.
After lengthy discussions it does indeed appear there was a change in the "Fall patch" that screwed the code that was working for these INSERT commands for all this time.
We have modified the code to avoid the now useless and unnecessary DateModified check and gone with a simple load into the localized text database.

I have sent some French text to a user for testing and I am awaiting his results.

**Comment by GrantSP** [comment]
This is the position we find ourselves at. The translation work should now be under way with the confirmation that this type of sql command **will** place the desired text in the correct place.

_INSERT OR REPLACE INTO Language_FR_FR (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_AAA_BBB_CCC', 'Text in french.', '', '');_

As you can see the real only difference is the **Language_FR_FR** without the **CEP_** prefix.
This means all our text just go straight into the user's language for immediate use without the _DateModified_ check to load the latest version, English or otherwise.
