### ISSUE TITLE
Crash (without any error message) while loading modded savegame.

### ISSUE THREAD

**Issue by Zakara** [Thalassicus/cep-bnw#302]
There seems to be a Syntax error with a certain mod. There was no Civilization V update recently and the game worked fine 6 days ago.
[Lua.TXT](https://github.com/Thalassicus/cep-bnw/files/101841/Lua.TXT)

**Comment by GrantSP** [comment]
This mod is not being maintained and any errors you see will either need to be fixed by you or ignored.
Your best bet is to switch to using the Community Balance Patch.
