### ISSUE TITLE
Gun unit types, resource requirements, & Longswordsman / Samurai upgrade track

### ISSUE THREAD

**Issue by Volver1** [Thalassicus/cep-bnw#31]
I found that as of 3.8 Gatling guns, machine guns, & bazookas are classified as soldier units. Longswordsmen & samurai, as well as crossbows, upgrade to Gatling guns. Finally, Gatling guns require iron, while machines & bazookas require oil.

**Comment by Thalassicus** [comment]
Which part are you asking about?

**Comment by Volver1** [comment]
I guess I'm asking if this is intentional, and if not, how do I correct it? I don't think it's better for melee (warrior>swordsman>longswordman) units to upgrade to a ranged unit track, especially since this is what archers upgrade into. Second is the strategic resource also by design? There isn't enough iron in the game to support this, let alone oil. Even if there were, why should these defensive city garrison units have a strategic requirement? Strategic resources are for knights & tanks, not these.

**Comment by Hawawaa** [comment]
How about Gatling Guns can still be built without iron but have a penalty -10% and Machine Guns don't require iron at all. And Bazookas require no oil.

**Comment by GrantSP** [comment]
As with a lot of things in this consensus driven mod, there will simply be some things that we personally don't like or think fit properly. However, as this was discussed at length elsewhere, this should probably be closed and taken up elsewhere.
