### ISSUE TITLE
Eiffel Tower tourism bonus

### ISSUE THREAD

**Issue by TimurKelman** [Thalassicus/cep-bnw#32]
Tooltip says, the Eiffel Tower gives 12 tourism, but it doesnt. And it's not just a UI bug, there is indeed 0 tourism from that wonder.

**Comment by stackpoint** [comment]
I just remembered why this issue looked so familiar: http://forums.civfanatics.com/showthread.php?t=514047

> The yield bonus only comes into play upon the researching of 'Radio'. Have you reached that tech yet?
> 
> CEP changes the PrereqTech for the Eiffel Tower to Electricity so it is possible to have built it before the bonus kicks in.
> 
> Maybe the two techs could be synchronized.

and:

> I wonder why the tower had the tourism on an EnhancedYieldTech that was the same as it's PrereqTech? Well Thal will have to clarify if this was intentional or not and either the EnhancedYieldTech or text description will have to be updated.

**Comment by stackpoint** [comment]
So either the descriptive text of the Eiffel Tower needs to clarify that the tourism bonus unlocks at Radio or that the EnhancedYieldTech needs to be synchronized with the PrereqTech with the CER spreadsheet updated to reflect that too.

@Thalassicus will have to clarify on the intent.

**Comment by stackpoint** [comment]
I have synced the enhanced yield techs here: https://github.com/Thalassicus/cep-bnw/commit/6587c2b4943744603f9ee949be7dcdf5c650ad34
