### ISSUE TITLE
TXT_KEY_FLAVOR_GOLDEN_AGE not defined

### ISSUE THREAD

**Issue by skodkim** [Thalassicus/cep-bnw#37]
It seems TXT_KEY_FLAVOR_GOLDEN_AGE is not defined. This should probably be in Text\en_US\Flavors.sql of CAT.

![civ5screen0016](https://f.cloud.github.com/assets/6018459/1639986/71260c64-582e-11e3-88a7-402ab5cbeb6a.jpg)

\Skodkim

**Comment by Hawawaa** [comment]
I got ya covered at point 3- https://github.com/Thalassicus/cep-bnw/issues/29 and Taj Mahal
