### ISSUE TITLE
Error in lua.log

### ISSUE THREAD

**Issue by skodkim** [Thalassicus/cep-bnw#38]
Version 3.8.1

I had the following line in lua.log when looking at Buildings in the game (civilopedia I think). Sorry that I can't be more specific, but I don't exactly know when it happened.

[21209.911] TW_Init: FATAL  Turn 0   GetDefaultBuildingStatText lineType=YieldFromTech : column EnhancedYieldTech does not exist in GameInfo.Building_TechEnhancedYieldChanges

I use a lot of other mods as well but I did a search of the community mod files for key words from the error message and it seems to be related to this.

\Skodkim

**Comment by stackpoint** [comment]
Take a look at your database.log file. I wouldn't be surprised if there were errors in loading the CAT_AlterTables.sql file or some sort. This specific error suggests there is some sort of compatibility problem somewhere with your mods.

**Comment by skodkim** [comment]
how do I attach other files than images?

\Skodkim

**Comment by stackpoint** [comment]
You can't. You can rename the files lua.jpg and upload them and I could rename them back to look at them. You can also use [pastebin](http://pastebin.com/).

**Comment by skodkim** [comment]
Hmm - just realized that I had cleared the cache due to testing the modmod bug you're helping me with on the civ fanatics forums. Will post here again if I see the bug again.

\Skodkim
