### ISSUE TITLE
Initial Capital Palace building yields

### ISSUE THREAD

**Issue by GrantSP** [Thalassicus/cep-bnw#43]
When you found your first city the Palace has a (2) next to it and 'some' of the yields shown are for multiples of the building.

Production shows 4 from buildings and the Palace is the only building that gives a yield, which is 2.
Gold shows 6 from buildings. Subtract the 2 from the Capital and the Palace again is giving double the Gold yield.
Science, like Gold shows 6 with the same circumstances as Gold.
Likewise Culture shows 6.

Is the Palace building somehow being duplicated in the Capital? I haven't yet founded a new city so I cannot say if it also does this in new cities.

I should have checked the Aztec capital earlier. I forgot that the Palace building also goes into captured cities if your total number of cities is less than 3.
So, the palace in Tenochtitlan is only giving yields for a single building and it doesn't have a (2) after it, so I can assume the building is working correctly here.

**Comment by stackpoint** [comment]
Found the source of this bug. Looks like the old Great Hall Building from GEM hasn't been completely removed. I've pushed a commit with the fix. Doesn't look like any yields were changed. May need further investigation.

**Comment by stackpoint** [comment]
Whoops. It looks like I commented out the wrong capital reference. Back to the drawing board.

**Comment by stackpoint** [comment]
Okay, I think I fixed it without breaking functionality this time: https://github.com/Thalassicus/cep-bnw/commit/9f4b85f5a68425248b79325e734b5ced995962e2

**Comment by GrantSP** [comment]
Looks good.
