### ISSUE TITLE
Strategic resources, only Coal

### ISSUE THREAD

**Issue by Klaumbaz** [Thalassicus/cep-bnw#44]
no horses, no iron, and now no Oil. Steam comments on your mod are showing same thing. Please fix.

**Comment by stackpoint** [comment]
@Thalassicus, I recommend that you remove CivUP and GEM from the workshop due to the numerous bugs.

**Comment by Thalassicus** [comment]
I wish I had time to work on that. I've had to choose between working on the BNW or G&K version, and the BNW one takes precedence since more people are playing that expansion.
