### ISSUE TITLE
Beserkers

### ISSUE THREAD

**Issue by GrantSP** [Thalassicus/cep-bnw#45]
The Danish Beserker is described as a Longswordsman replacement yet once it is available to build the Swordsman is still available in the build queue.
Is this by design or error?
To have both available is odd.

Swordsmen upgrade to Beserkers so there is the strange occurrence that you can build a Swordsman quicker and cheaper than a Beserker and then if you have taken Honor and have cheaper upgrades as a policy you can then upgrade it for less Gold than it costs to buy it outright.

At King level it costs 450 for a Swordsman and 720 for a Beserker. Yet to upgrade only costs 65 (with Honor policy, 100 without, still cheaper).
To build it is about 5 turns compared to 8 for the Beserker.

**Comment by Thalassicus** [comment]
Lines 7-17 of CER_End.sql should make each unit obsolete at the tech of the unit it upgrades to. Swords upgrade to longswords, which are on the Steel tech, so swords should obsolete there.

The units table of the database shows swordsmen obsoleting at TECH_STEEL, and that's what's shown ingame when I look at the sword unit. I don't know why they might not go obsolete with longswords...

**Comment by Thalassicus** [comment]
I see now what you're talking about. Berserkers are available earlier than longswords. Swords still correctly disappear at steel. I don't know why berserkers are on Metal Casting. The only unique object I know which I specifically set to an earlier time than normal is the English unique factory.

**Comment by Thalassicus** [comment]
It looks like Firaxis specifically moved the berserker to metal casting in BNW. They chose to make swords and berserkers available simultaneously. I don't know why they did this. Do you think we should move berserkers back to steel? Why might Firaxis have chosen to do this?

**Comment by GrantSP** [comment]
It would be desirable to have them removed from the selection but if not make the upgrade and production of them worse than building longswords

**Comment by GrantSP** [comment]
All the other Longswordsman type units are at Steel, it probably makes sense to have them set to that as well.
