### ISSUE TITLE
[3.9]Select synrax error in database.log

### ISSUE THREAD

**Issue by skodkim** [Thalassicus/cep-bnw#47]
I get a "[9734.275] near "SELECT": syntax error" in database.log using CEP/CIN/CAT 3.9.

No other mods used and cache cleared prior to this. Log file uploaded - renamed to *.jpg.

![database log](https://f.cloud.github.com/assets/6018459/1695366/a796dbf6-5eb0-11e3-8079-6fe373e678a8.jpg)

**Comment by stackpoint** [comment]
Fixed here: https://github.com/Thalassicus/cep-bnw/commit/01518c22326f7c5a2650352e6d825a911268e525
