### ISSUE TITLE
[3.9] ProductionPopup: ERROR  BUILDING_### PrereqTech=TECH_NUL

### ISSUE THREAD

**Issue by skodkim** [Thalassicus/cep-bnw#48]
I get the following erros in lua.log using CEP/CIN/CAT 3.9:

[9840.574] ProductionPopup: ERROR  BUILDING_MAYA_PYRAMID PrereqTech=TECH_NULL
[9840.574] ProductionPopup: ERROR  BUILDING_SHRINE PrereqTech=TECH_NULL
[9840.574] ProductionPopup: ERROR  BUILDING_VEDI PrereqTech=TECH_NULL

The error seems to come when I select the shrine Building in the Building queue.

No other mods used and cache cleared prior to this. Log file uploaded - renamed to *.jpg.

![lua log](https://f.cloud.github.com/assets/6018459/1695388/2e515310-5eb1-11e3-8f39-f511385ebe74.jpg)

**Comment by stackpoint** [comment]
This was fixed previously here: https://github.com/Thalassicus/cep-bnw/issues/25

Looks like it became unfixed with the conversion of the file from xml to sql.

**Comment by stackpoint** [comment]
Fixed this here: https://github.com/Thalassicus/cep-bnw/commit/4286236d64cf267b1dadb3a2c56a85a425d02e99
