### ISSUE TITLE
[3.9] No Culture from killing barbs after Honor

### ISSUE THREAD

**Issue by skodkim** [Thalassicus/cep-bnw#50]
Using 3.9 I get no Culture from killing barbs after selecting the Honor opener.

Was reported in the "3.9 - Policies" thread on Civ fanatics but reported there as always getting the culture boost (even when no having selected the honor opener) but this is the way I've seen it in four test games (used fire tuner to place units and add culture to get social policy).

No other mods and cache cleared. Logs attached.

\Skodkim
![logs zip](https://f.cloud.github.com/assets/6018459/1695828/0bb401d8-5eb9-11e3-8b24-476885cdc996.jpg)

**Comment by stackpoint** [comment]
Thanks for posting your logs in all these bug reports (and taking the time to rename them to jpg for easy access).

I just pushed an update to fix this bug.

**Comment by stackpoint** [comment]
Just saw your post on the forums. Reopened it for further analysis.

**Comment by skodkim** [comment]
Thanks. Was just about to object :-)

\Skodkim
