### ISSUE TITLE
Can't select production or research after upgrade to 3.9.1

### ISSUE THREAD

**Issue by bhearsum** [Thalassicus/cep-bnw#51]
After I found my city I try to select production and the quick menu doesn't come up. If I dive into the city and click "change production", nothing happens. If I use the quick menu for research, it shows up but has no techs in it, and the bottom half of it shows the map underneath.

This happens with just the AI mod enabled as well as with all mods enabled. Please let me know how I can provide additional information to help debug this!

**Comment by GrantSP** [comment]
Are you working from the 'released' version or have you pulled the source from GitHub?
There was a problem a few hours ago with the source here on GitHub but it should be fine now, I am in fact running tests with the code from the Stable branch as pulled from GitHub.

Either way, if you pull the last Stable source and build you should have no errors.

**Comment by stackpoint** [comment]
It looks like Thal updated the release version to 3.9.1 which was the stable build before the minor typo error. I reverted the update back to 3.9 for now.

**Comment by bhearsum** [comment]
Ah, OK. I see 3.9 on the release page now. Cheers!
