### ISSUE TITLE
Dummy Policy Branches Error

### ISSUE THREAD

**Issue by stackpoint** [Thalassicus/cep-bnw#52]
I've found the cause of the errors but not the reason why it would. In CEG\Policies\CEP_End.sql line 3:

``` sql
INSERT INTO PolicyBranchTypes(Type, Description, EraPrereq, AIMutuallyExclusive)
SELECT DISTINCT Type, Description, 'ERA_FUTURE', 1
FROM Policies;
```

Commenting this code out fixes all the opener/finisher issues but since this is the method that creates the dummy branches we may want to find an alternative fix.

**Comment by stackpoint** [comment]
Relevant issues here: 
https://github.com/Thalassicus/cep-bnw/issues/49
https://github.com/Thalassicus/cep-bnw/issues/50

**Comment by stackpoint** [comment]
There was a syntax error in this file fixed here: https://github.com/Thalassicus/cep-bnw/commit/01518c22326f7c5a2650352e6d825a911268e525

Not sure if this could be the cause of the bug with the dummy branches code.

**Comment by Thalassicus** [comment]
I'm unsure how this happens. I think the sequence of events is like:
1. player opens the POLICY_BRANCH_TRADITION
2. the branch awards a FreePolicy: POLICY_TRADITION
3. function DoPolicyBuildingUnlocks gives the policy _branch_ called "POLICY_TRADITION"

It's really odd step 2 wouldn't give the bonuses associated with the Tradition policy. It must be some weird internal bug in the game core.

If this problem happens only for openers and finishers, we can easily exclude those by checking if the added branch is found in the FreePolicy or FreeFinishingPolicy columns. I made this change in CEP_End.sql.
