### ISSUE TITLE
Some policies lost after loading game

### ISSUE THREAD

**Issue by bhearsum** [Thalassicus/cep-bnw#55]
Noticed this after upgrading to 1.9. I had a game where I had completed all of Liberty (and part of Honor). After loading my game the next day all of the Liberty policies could be chosen again. I _think_ they're still considered active, because I have Walls in all of my cities from Republic, but it's hard to be sure.

**Comment by stackpoint** [comment]
There was an error with 3.9 that was causing unusual behavior with the policies. I believe it was fixed in 3.9.3 but please let us know if anything like this occurs again and I will reopen this.
