### ISSUE TITLE
3.9.3 Promotions don't give your units a small heal. 

### ISSUE THREAD

**Issue by Hawawaa** [Thalassicus/cep-bnw#59]
When units level up and are damaged they don't get any health.

**Comment by stackpoint** [comment]
I have not encountered this bug. My units gain health after they gain their promotions and the turn ends.

**Comment by Thalassicus** [comment]
The intended behavior is units get the heal instantly. I haven't had time to update the required user interface file to do this after BNW changed the file. This will change when I get to the UI part of the project.

**Comment by stackpoint** [comment]
Should be fixed here: https://github.com/Thalassicus/cep-bnw/commit/c6cd6b4eafdab71e4699701cff88890e44aefe52
