### ISSUE TITLE
Impi unit shows notification of promotion with no promo available

### ISSUE THREAD

**Issue by GrantSP** [Thalassicus/cep-bnw#60]
I have a Impi that gained experience in the field against barbarians. The tuner shows it reached 66 experience.
The right-side notification panel shows a small unit icon for it with the promotion flashes overlay and the text says "A Unit has gained enough experience to be promoted".
Clicking that icon takes me to the specific unit that engaged in combat the turn preceding, yet no available promotions are given.

I can select it and give more experience with the tuner and promotions become available and applied to it yet the notification persists.

EDIT:
Now happened a second time. The first unit was an upgraded Scout so it had different promotions to what is available to a freshly trained unit. I thought that might be the reason however, a new unit that gained experience in combat against a CS now has 28 experience and should be promoted yet despite the notification cannot be promoted and loose the right-side icon.

**Comment by stackpoint** [comment]
I haven't been able to replicate this. Any lua errors or stuck popups?  

Also, if I remember correctly, the Zulu gain promotions at 10, 30, 60, 100 --> 7.5, 22.5, 45, 75. So it would be weird for your promotion to be delayed all the way to 66 experience.

**Comment by GrantSP** [comment]
No errors in the logs.
The unit passed the 60 limit and was at 66.
After saving and reloading the notifications disappeared so the error is
not with the unit or the promotion. It seems it is a stuck piece of code.
No errors of any kind anywhere I look.

**Comment by stackpoint** [comment]
The Zulu should be gaining promotions 25% faster, so instead of at 60, you should've gotten the promotion at 45.

**Comment by GrantSP** [comment]
Good point. Then I am at a loss as to why the promotion would show at the 60 level.
Unless the Zulu ability was somehow hindered or in conflict with the normal promotion timing and the triggering happened for one and was applied with the other and the first call was somehow not given the release. Seems unlikely though. At any rate the re-load of the save removed the notifications.

I think it best to close this. We can always re-visit it if someone else sees the same issue again.
