### ISSUE TITLE
[3.10] lua.log ERROR: Failed to load CEP_Start.sql

### ISSUE THREAD

**Issue by skodkim** [Thalassicus/cep-bnw#61]
On a clean start (cache cleared, other mods deleted) using only CAT/CIN/CEP 3.10 I get the following in lua.log: ERROR: Failed to load CEP_Start.sql

log file attached

\Skodkim
![lua](https://f.cloud.github.com/assets/6018459/1726580/e0596cb2-6291-11e3-9bfa-7a1f18d68dca.jpg)

**Comment by stackpoint** [comment]
This is the same error as this: https://github.com/Thalassicus/cep-bnw/issues/62
