### ISSUE TITLE
[3.10] database.log no such column: NUM_POLICY_BRANCHES_ALLOWED

### ISSUE THREAD

**Issue by skodkim** [Thalassicus/cep-bnw#62]
On a clean start (cache cleared, other mods deleted) using only CAT/CIN/CEP 3.10 I get the following in database.log: no such column: NUM_POLICY_BRANCHES_ALLOWED

There may be one more undescribed error message (blank line beneath this error message)

log file attached

\Skodkim

![database](https://f.cloud.github.com/assets/6018459/1726598/24f6e0de-6292-11e3-9d80-b68b141a12e8.jpg)

**Comment by stackpoint** [comment]
Fixed here: https://github.com/Thalassicus/cep-bnw/commit/063dcad3a3849521d7200a1c73c556ac817fc148
