### ISSUE TITLE
Research Tree disappears

### ISSUE THREAD

**Issue by KielMartin** [Thalassicus/cep-bnw#63]
Sometime in the middle of the game the available techs disappear and I am unable to continue.  Big fans of the mods.  First post to help fix bugs
![database](https://f.cloud.github.com/assets/6165997/1750842/dfc9cb5a-65b8-11e3-8ec7-14c1e26a859e.jpg)
![lua](https://f.cloud.github.com/assets/6165997/1750843/e31bd640-65b8-11e3-8875-6061e8b77b6a.jpg)

**Comment by stackpoint** [comment]
Could we get your lua.log and database.log files? Rename them to .jpg and you'll be able to attach them.

**Comment by brutha2** [comment]
Hi, I've had a similar issue, and in my case the trigger was going "restart map"; it worked fine before restarting. I lose all or most of the techs and cannot go forward.

![database](https://f.cloud.github.com/assets/6180391/1744730/8de7829c-6422-11e3-8417-bf5067c1afb4.jpg)

![lua](https://f.cloud.github.com/assets/6180391/1744734/a418017c-6422-11e3-9bf9-e591df04bd31.jpg)

**Comment by stackpoint** [comment]
There is some sort of incompatibility with loading and restarting the map from outside the main MODs menu. I'm not sure what causes it but it's the reason why we disabled the loading from within the game feature. We'll have to disable restarting the map too.

**Comment by Thalassicus** [comment]
Reloading from within an active game breaks all mods with lua code. The game doesn't re-initialize global lua variables. It reuses the variables from the cache. Modders can't fix this, and I don't think Firaxis can easily fix it either.
