### ISSUE TITLE
[3.10] Rome only starts with iron under the first city

### ISSUE THREAD

**Issue by skodkim** [Thalassicus/cep-bnw#64]
Just started a new game as Rome using [3.10].  The description says Rome should get 1 free iron under the first five cities but I only seem to get it under my first city.

I'm playing with other mods and even though none of these should effect this I can't be sure. I'm not really keen to test without other mods at the moment as I'm afraid this will mess up my current game (and I just got started after months of waiting :-) ). Should be easy enough to test using the fire tuner though,

\Skodkim

**Comment by stackpoint** [comment]
This is a leader function that does not have code implemented.

Trait_FreeResourceFirstXCities does not have any lua code built around it.

**Comment by skodkim** [comment]
just tested again and it worked. Maybe I was just seing things...

anyway i'd like to do one more test tomorrow. Will report back.

\Skodkim

**Comment by GrantSP** [comment]
This function is also used by the:
Japanese, Denmark, Songhai, Greece, Huns, Mongols, Byzantines and Egypt.

Any error in the function will result in these civs lacking either Iron or Horses in their first city.

**Comment by stackpoint** [comment]
The function doesn't exist. The only civ that should receive a starting resource should be the Mongols because of code in another area unrelated to this field.

**Comment by GrantSP** [comment]
This is a vanilla function. The Trait_FreeResourceFirstXCities is set in vanilla code and has some C++ code as defined in CvTraitClasses.cpp.

It used to work with Rome before,I haven't seen it fail so I can't say if we have changed anything, but there should be no reason why it doesn't work.
Famous last words.

**Comment by stackpoint** [comment]
@skodkim, the next time you have this problem, could you post your database.log file? I'll close it for now.
