### ISSUE TITLE
[3.10] Compatibility with CSD broken

### ISSUE THREAD

**Issue by skodkim** [Thalassicus/cep-bnw#65]
Compatibility with City State Diplomacy mod seems broken. I've set USING_CSD and DISABLE_GOLD_GIFTS to 1 in Cat_Options.sql. Furthermore I've made sure gold gifting is disabled in the options file from CSD and still I'm able to give gold gifts to City States.

A quick search of the CIN/CAT/CEP files shows that "DISABLE_GOLD_GIFTS" are only found in Cat_Options.sql

As inspiration on how to do this I've uploaded the options.sql file from CSD and the file optional.sql which alters values based on the options.sql file.

![options sql](https://f.cloud.github.com/assets/6018459/1733377/8060b644-6336-11e3-8434-7b8a87059a6c.jpg)

![optional sql](https://f.cloud.github.com/assets/6018459/1733370/6965503a-6336-11e3-9d7c-ec66ee980195.jpg)

\Skodkim

**Comment by stackpoint** [comment]
I'd appreciate it if you kept compatibility issues to the bug report forums since this isn't a direct issue related to CEP. I handle all compatibility problems on a case by case basis and it'll be better if the process was recorded in a forum format.

**Comment by stackpoint** [comment]
However, I'd start by following this: http://forums.civfanatics.com/showpost.php?p=12863114&postcount=1205
