### ISSUE TITLE
Churches of Lalibela

### ISSUE THREAD

**Issue by GrantSP** [Thalassicus/cep-bnw#67]
Do you think this wonder should have a prerequisite that the player or AI civ must first have established a religion?

Just saw Egypt only get their pantheon and then 5 or 6 turns later they have built this wonder.
Their missionary is just standing around with nothing to do. Or does he spread the pantheon belief? Surely not.

**Comment by stackpoint** [comment]
Yeah, it should be the same as the Borobudur wonder so it must be built in a holy city.

**Comment by GrantSP** [comment]
Changed it to check for the Holy City so only players or AI with a religion can build it.
