### ISSUE TITLE
[3.10] Forge production modifiers

### ISSUE THREAD

**Issue by skodkim** [Thalassicus/cep-bnw#68]
Just noticed that the Forge give a 15% production modifier for Land Units AND a 15% production modifier for Mounted/Skirmish units.

The second bonus is from standard BNW. This hasn't been removed and CEP introduces the first bonus in \Cities\CEC__End.sql

\Skodkim

**Comment by GrantSP** [comment]
No, I believe these Building_UnitCombatProductionModifiers are added for UNITCOMBAT_MOUNTED & UNITCOMBAT_GUN units by the Forge, only in CEG.

I can't see any modifiers added to the Forge in the vanilla code.
The Building_UnitCombatProductionModifiers table for vanilla only affects the Stable, Ducal Stable, Kremlin & ToA.

**Comment by skodkim** [comment]
are you sure? I dont have access to the files right now but I checked before posting.

Try looking in the civilopedia and see what it says there. Otherwise maybe I can look tomorrow when I get home.

\skodkim

**Comment by GrantSP** [comment]
Well, I have been known to wrong on more than one occasion. ;)
But yes, pretty sure. I keep copies of all the databases from the first release up to our latest mod and BNW doesn't show any change to the Forge in the database. Additionally, there is no code showing a change to that table in the vanilla code.

**Comment by skodkim** [comment]
Well if you look at line 2565-2569 of Steam\steamapps\common\sid meier's civilization v\Assets\DLC\Expansion2\Gameplay\XML\Buildings\CIV5Buildings.xml you'll see Building_DomainProductionModifiers listed for BUILDING_FORGE for DOMAIN_LAND

If you look at line 365-376 of communitas_enhanced_gameplay__v_3_10\Cities\CEC__End.sql (version 3.10, not 3.10.1) you'll see Building_Building_UnitCombatProductionModifiers listed for BUILDINGCLASS_FORGE for UNITCOMBAT_MOUNTED and UNITCOMBAT_GUN

OK?

\Skodkim

**Comment by GrantSP** [comment]
OK? It is more than OK!. It is brilliant. Excellent observation. You have seen the result of the two tables that modify land units being added together. I on the other hand was just looking at one table.

The question we are left with is: which is the best way to rectify this? Remove one and leave the other, if so, which one? Or. Lower the values in both tables for a cumulative effect?

Skodkim, I tip my hat to you, if I had a hat.

**Comment by skodkim** [comment]
:-)

I think the production modifier should be for all land units but thats really a design question.

\Skodkim

**Comment by skodkim** [comment]
Hmm

After spending so much time of our mutual time on this I found out that it doesn't really matter at all since the forge has been removed by the tech tree, i.e. the building exists in the game but isn't buildable. I only found it because I was running a modmod that involved a UB that replaces the Forge and therefore I was able to click on the Forge from the UB's civilopedia page.

There seems to be a lot of these "redundant things" around in CEP at the moment. A week ago I was doing some bug tracking of policies and found a lot of policies that seems to be in game but aren't assigned to any of the trees, e.g. they're not used. Won't these policies, buildings etc. take up memory thereby slowing down the game?

\Skodkim

**Comment by GrantSP** [comment]
All this time I was under the impression the Forge was just renamed to something else. I thought it was the smith.
It seems the Forge is gone, the windmill is now the workshop and the workshop is now the smith.
Sometimes I think it is done just to confuse me.
I have no definitive proof one way or the other as to whether these sort of things take up memory and slow the game down. I am trying at the moment to sway opinion towards moving all the TXT into the localized database and not the gamedata one for that same reason. It seems, to me, logical that unnecessary entries in the gamedata database will be a detriment to the speed of the game. But who am I?
I think there is quite a lot of house-keeping that needs to done to be honest.
