### ISSUE TITLE
Readme, credits  and sundry files

### ISSUE THREAD

**Issue by GrantSP** [Thalassicus/cep-bnw#7]
With the new structure placing ALL the separate projects under the one location I think it is also a good idea to move out all duplicate documentation to either the wiki or just placing a general copy for all the parts inside the CEP_BNW project's main folder.

So:
- 1) re-do the facing page on the project here in GitHub. I suggest using _markdown_ so it can be formatted well here but still readable in a text editor if wanted. Now that the process is more structured the readme should reflect how to contribute to it in its new shape.
- 2) Move all the credits file updates to the [wiki credits page](http://communitas.wikia.com/wiki/Credits), and just place a URL if needed in the main folder and/or sub-folders.
- 3) Inside each folder/project part add a new readme describing the purpose of that specific part.

**Comment by stackpoint** [comment]
Is this a duplicate of another issue? I ask because of the duplicate label.

**Comment by GrantSP** [comment]
Sorry my mistake. No it isn't a duplicate issue. Clicked that by accident and didn't remove it.

**Comment by GrantSP** [comment]
Thalassicus has now moved most of the minor documentation, so this can be closed.
