### ISSUE TITLE
Mod cannot be loaded and successfully run without quitting out to the desktop.

### ISSUE THREAD

**Issue by GrantSP** [Thalassicus/cep-bnw#70]
I was conducting some tests to investigate something and first started a vanilla game to act as a baseline.

No mods of any sort were loaded, just a straight 'Single player' game as chosen from the main menu.
After gathering the information I needed with that game I exited to the main menu and proceeded to setup a modded game. All the CEP components including the MAP.

After the map was created the two units had promotion tooltips with empty slots visible and the Settler had action buttons for a bombing raid and other things. Upon founding a city the production queue is empty and the game is unplayable.

Now I can understand how the reverse may be true, start a modded game and then a vanilla game and 'perhaps' some modded code gets stuck in memory. This though baffles me. How does the mod get screwed up after loading a vanilla game?

To clarify, if I start a game as normal, by immediately going to the mod screen and starting that way, there are no errors. Everything is as expected.

What action is or isn't completing or getting stuck in memory that prevents the modded game from setting up correctly after quitting from a vanilla game?

The log clearly shows that the database isn't being updated between quitting the vanilla game and starting a modded game. I thought the popup panel that says "configuring data" as the mods load was the data being inserted into the vanilla database?

Errors are shown for
Communitas AI and Tools (v 3)\Interface\Bugfixes/**TechButtonInclude.lua**:112:  _Cannot find key - IsVisible_
Communitas AI and Tools (v 3)\Tools/**Cat_Events.lua**:29:  _Cannot find key - Reverse_
Communitas AI and Tools (v 3)\Tools/**Cat_Events.lua**:656:  _Cannot find key - FreePromotionAllCombatUnits_
Communitas AI and Tools (v 3)\AI/**CEAI_Events.lua**:788:  _Cannot find key - AIBonus_
Communitas AI and Tools (v 3)\AI/**CEAI_Events.lua**:705:  _Cannot find key - NoWarrior_
Communitas AI and Tools (v 3)\AI/**CEAI_Events.lua**:749:  _Cannot find key - FreeShip_
Communitas AI and Tools (v 3)\Tools\TooltipWriter/**InfoTooltipInclude.lua**:143:  _Cannot find key - Class_
Communitas AI and Tools (v 3)\Tools\TooltipWriter/**TW_Init.lua**:557:  _Cannot find key - ListPriority_
This produces a 'Runtime Error' at line 557
_attempt to perform arithmetic on field 'ListPriority' (a nil value)_
The stack traceback is

```
...\Communitas AI and Tools (v 3)\Tools\TooltipWriter\TW_Init.lua:557: in function <C:\Users\Grant\Documents\My Games\Sid Meier's Civilization 5\MODS\Communitas AI and Tools (v 3)\Tools\TooltipWriter\TW_Init.lua:548>
    =(tail call): ?
...\Communitas AI and Tools (v 3)\Tools\TooltipWriter\TW_Init.lua:656: in main chunk
    =[C]: ?
```

Also a whole lot of references to TW_Init to do with _cep.ObjectInfo_ where the specific keys can't be found.

**Comment by Thalassicus** [comment]
I think I've seen this too, and it looks like a cache issue modders can't change or fix.

**Comment by GrantSP** [comment]
That is unfortunate. I will close it for now. Someone can re-open it if we get an idea of what to fix.
