### ISSUE TITLE
Wonder pedia & splash descriptions

### ISSUE THREAD

**Issue by GrantSP** [Thalassicus/cep-bnw#75]
User Hawawaa opened an issue with various text errors. As they are all fixed except for the Wonder texts, and others have made comments about the need to update the Wonder descriptions, I have made this new issue to care for these.

Generally the text is contained in the tag formatted as:
TXT_KEY_WONDER_[name of wonder]_HELP

(moved from original issue)
- [x] Chichen Itza text error for golden age (not sure what the error is)
- [x] Taj Mahal text error for golden age (not sure what the error is)
- [x] Stonehenge -- needs a description
- [x] TerraCotta Army
- [x] Pyramids
- [ ] Temple of Artemis
- [ ] Mausoleum of Halicarnassus
- [ ] National Epic
- [ ] National Treasury
- [ ] Hermitage
- [ ] Ironworks
- [ ] Grand Temple
- [ ] Statue of Liberty
- [ ] Hagia Sofia

Possibly many other wonders with minor changes that aren't reflected in the text. Those listed also may not need text changes if the "Good For:" display shows enough information. I just started listing wonders that I know are changed, some slightly.

**Comment by Thalassicus** [comment]
What do you mean by "description"? There are four text entries per building:

Description - name of the building
Civilopedia - history
Help - unused / deprecated
Strategy - unused / deprecated

**Comment by GrantSP** [comment]
eg. Stonehenge doesn't have a description text that accompanies the splash screen in the same manner as the others. I removed it as it was displaying the "Good For:" text and it flowed off the bottom of the page.
The others are not to be taken as a definitive list. Those that I see all the time are eg. TerraCotta now gives a border increase yet the text still describes free copies of units or Pyramids which now gives a free settler. That sort of thing.
I didn't change anything yet as I was under the impression the Wonders were still a work in progress and may revert to vanilla values.

Whether the text block is "Description" or "Civilopedia" doesn't matter, I think.
The location of the text is secondary to what to change it to. If indeed we are changing these wonders.
Some of the minor changes may not need text changes at all. I simply started a list to focus our attention.

**Comment by AnastaseAlex** [comment]
Hagia Sofia bug: it sais that it gives 1 faith per specialist and that is seen on the city screen, but it does neither show up nor accumulate in the faith pool every turn.

**Comment by GrantSP** [comment]
Just a little reminder to any that look at these TXT_KEYs and say: WTH!

Firaxis in there wisdom have used TXT_KEYs with overlapping names for the various wonders.
e.g.
Pyramids of Egypt = TXT_KEY_WONDER_CHICHEN_ITZA_HELP
Taj Mahal = TXT_KEY_WONDER_PYRAMIDS_HELP
Chichen Itza = TXT_KEY_WONDER_TAJ_MAHAL_HELP

Now I have to check if it is just the names that are wrong or if the actual tags are transposed. Grrrr.

**Comment by GrantSP** [comment]
Well I have learnt something today. (well many things but this one is pertinent)

None of this is of any importance.
The tooltip writing code will handle all these descriptions automatically and there will not need to be **ANY** need for human checking.

So, I have updated a few of them to tide us over in the mean time.
