### ISSUE TITLE
Production queue errors

### ISSUE THREAD

**Issue by GrantSP** [Thalassicus/cep-bnw#77]
As of the changes made today, by me, the production queue errors have returned.

It is impossible to queue any buildings upon founding the new city.
I strongly suggest no-one builds this version until I remove the errors I have introduced.
Apologies.

**Comment by GrantSP** [comment]
This is the error message that now happens:
Interface\Bugfixes\ProductionPopup.lua:112: attempt to index field '?' (a nil value)

I just can't figure out why it is introduced, the edits I made weren't that extensive.

After removing the edits I made, I am still getting this error. This is very puzzling, I have no clue.

**Comment by mithrawnundo** [comment]
I don't know if this is the same error I have but I cannot build anything besides civilian units.

See http://forums.civfanatics.com/showthread.php?p=12963153#post12963153 for LOG

**Comment by GrantSP** [comment]
It appears my attempt to fix the tech tree from showing 2 unused units has caused this error.
Now fixed.
