### ISSUE TITLE
3.10.2 Can't built anything except workers

### ISSUE THREAD

**Issue by wolverine2112** [Thalassicus/cep-bnw#78]

**Comment by skodkim** [comment]
Critical bug!

I experience this too. No other mods, cache and user data cleared prior to launch etc.

Log files attached. There's an error message in lua.log

![logs zip](https://f.cloud.github.com/assets/6018459/1774364/e5a4e2f8-67f7-11e3-8a2a-5aee6eb91ed3.jpg)

\Skodkim

**Comment by GrantSP** [comment]
This is the same error I reported.
I will close this one and you can keep up-to-date here. https://github.com/Thalassicus/cep-bnw/issues/77
