### ISSUE TITLE
[3.10.2] TXT keys missing for Trade Office

### ISSUE THREAD

**Issue by skodkim** [Thalassicus/cep-bnw#80]
With 3.10.2 two text keys are missing for the Trade Office

![civ5screen0011](https://f.cloud.github.com/assets/6018459/1785153/417b0b60-68df-11e3-8174-18c9df1d3b82.jpg)

\Skodkim

**Comment by GrantSP** [comment]
I have left a note alongside the change in the commit that changed it asking for clarification.
It may be a mistake or the first step in a change with the Dutch UB.
Several minor "fixes" took place with that commit, not all make sense to me.

**Comment by skodkim** [comment]
ok

**Comment by stackpoint** [comment]
Many of the text changes may have simply been overwritten by the code generated by the spreadsheet. If you had not made the text changes to the corresponding spreadsheet then it's likely the code ended up overwritten.

I would check the spreadsheet and if the text entries you added aren't there then that's probably the cause of the missing text.
