### ISSUE TITLE
[3.10.2] Inconsistent unit costs

### ISSUE THREAD

**Issue by skodkim** [Thalassicus/cep-bnw#81]
It seems building costs for different units are rather inconsistent. I've only been through some of the early units but have found some examples which are posted below.

Costs are (Standard speed):
- Archer (available at Archery) cost 80
- Spearman (available at Bronze working) cost 70 - sounds really cheap and cheaper the the Archer which comes earlier
- Swordsman (available at Iron working) cost 150
- Composite Bowman (available at Mathematics) cost 110 - rather cheap compared to the swordsman which is from the same tier
- Pikeman (available at Civil Service) cost 120 - really cheap compared to ealier units
- Knight (available at Chivalry) cost 260
- Crossbowman (available at Machinery) cost 170 - rather cheap compared to the knight and longsowrdsman which are from the same tier
- Longswordman (available at Steel) cost 240
- Arquebusier (available at Gunpowder) cost 160 - sounds really cheap and cheaper the the Longswordsman/knight/Crossbowman which comes earlier

I don't mind differentiated costs for units from the same tier (actually I think they ought to be) but I think the examples given above shows something is wrong (or at least inconsistent).

\Skodkim

**Comment by GrantSP** [comment]
All the costs are modified based on CLASS using formulae outlined in the [Armies Spreadsheet](https://docs.google.com/spreadsheet/ccc?key=0Ap8Ehya83q19dGdOZWk5OS0xamFFQlBqYUthYnVQR2c&usp=drive_web#gid=1).

Any specific adjustment to an individual unit would need to be balanced against these formulae.
Comparisons should better be made against the CLASS upgrades, Archer - Composite Bowman - Crossbow etc.

Having said that, any discussion regarding the structure of the cost matrix is good.

**Comment by skodkim** [comment]
Should I take this to the forms then? Or are you going to discuss it with the other modders?

As I see it there are some seriously weird changes here (even though a lot of Work seems to have been put into the spreadsheet).

\Skodkim

**Comment by GrantSP** [comment]
Well you can discuss it in the forum, although these details were hashed over quite extensively many months ago.
I'm not sure how much change @Thalassicus is willing to put into it.

I agree, there are _some_ areas that _might_ need attention, but I suggest you get ALL the details of each needed change detailed **before** starting a discussion. They tend to go on a long time if the structure is too open ended. :)

Personally I tend to steer clear of _balance_ issues, my playing experience is too limited to have any serious weight.
By all means, investigate and discuss. No harm can result from it.

**Comment by stackpoint** [comment]
Cost modifiers should probably be discussed on the forums.
