### ISSUE TITLE
Building_Flavors_Human table

### ISSUE THREAD

**Issue by GrantSP** [Thalassicus/cep-bnw#83]
I'm assuming this is a new table that will handle some specific differences with how the AI and human players view the buildings.

My question is:

There are differences between the two, besides the obvious one of the Great Hall being removed.
Building_Flavors_Human table has the _FLAVOR_WONDER_ set for a number of wonders but the Building_Flavors (which I would imagine should be an exact copy of the original) does not.

Is this intended? If so, why?

The wonders that are lacking this FLAVOR are:
- Alhambra
- Brandenburg Gate
- Great Lighthouse
- Great Wall
- Himeji Castle
- Kremlin
- Panama Canal
- Pentagon
- Statue of Zeus
- Temple of Artemis

I can see where the changes are made and when, the WHY is most puzzling.

**Comment by stackpoint** [comment]
The following is the code that is deleting the FLAVOR_WONDER from those wonders in CEAI_Buildings: 

``` sql
DELETE FROM Building_Flavors
WHERE FlavorType = 'FLAVOR_WONDER'
AND BuildingType IN (
    SELECT BuildingType FROM Building_Flavors
    WHERE FlavorType IN (
        'FLAVOR_OFFENSE'            ,
        'FLAVOR_MILITARY_TRAINING'  
    )
);
```

I assume this is presumably to get the more military minded civs to build these military related wonders.
