### ISSUE TITLE
TXT Issues with stories

### ISSUE THREAD

**Issue by mitsho** [Thalassicus/cep-bnw#84]
Text Strings (?) seem to not have been updated, i.e.

[ ] the costs for the 2 'costly' options in "scout stories" were not displayed.
[ ] notification (in the upper centre of the screen) for story in another civ was missing the later part (x investment in y "helps z culture" - latter part missing)

Instead it showed the txt_key string.

**Comment by GrantSP** [comment]
Is this still a current issue? I have not seen it and triggering the stories is problematic.

**Comment by skodkim** [comment]
It would be very good to find a way of triggering stories to bug test them.

\Skodkim

**Comment by stackpoint** [comment]
You can set the TriggerRatePercent to 100 and that should make an event trigger every turn and you can also disable triggers in the CES_Stories.xml file.

**Comment by skodkim** [comment]
Just tested and it works now

\Skodkim
