### ISSUE TITLE
Golden Age gives +1 gold on all fields producing gold (CEP 3.10.1)

### ISSUE THREAD

**Issue by bernd-das-brot** [Thalassicus/cep-bnw#85]
Since GA now give +20% to all yields, I thought they should not give the vanilla extra gold. Bug or intended? And GA from GPs do not get shorter, but the tooltip says otherwise.

**Comment by GrantSP** [comment]
I believe this may just be a text error from using an older version of the TXT_KEY_MISSION_START_GOLDENAGE_HELP tag.
Previous versions of CivV mentioned the decreasing of GA lengths and we used the existing tag as a base in VEM/GEM. Quite likely this tag can be removed and the vanilla one used instead.
