### ISSUE TITLE
Lake Victoria a land hex? (CEP 3.10.1)

### ISSUE THREAD

**Issue by bernd-das-brot** [Thalassicus/cep-bnw#86]
Lake Victoria (Natural Wunder) can be passed by units like a land field. I was really surprised seeing the AI set up its artillery on its surface.;-)

**Comment by GrantSP** [comment]
I believe this is a 'bug' in ALL water tiles, not just Lake Victoria. I have been besieged by units on the coast as they stood on the water.

Not sure yet why this occurs. Keep looking. There may be some, as yet found, consistency to this bug.

**Comment by GrantSP** [comment]
On closer inspection, I think this may be a bug related to Lake Victoria.
We may have to change the 'Impassable' flag to its vanilla state.

**Comment by GrantSP** [comment]
Definitely a bug that views Lake Victoria as a land tile.
If you have it in your territory and select a worker near it, the preferred option for that unit's task is to build a road on the tile.

**Comment by skodkim** [comment]
I've seen this discussed in the general discussion sub forum on Civfanatics so its not an issue CEP introduced.

\Skodkim

**Comment by GrantSP** [comment]
Thanks Skodkim, I was going to change the passable boolean on this feature, but maybe this isn't necessary.
Although if we make it so you can't enter the tile then it wont look as weird as artillery firing from it.
