### ISSUE TITLE
Attempting to found a city warning: An antiquity site.

### ISSUE THREAD

**Issue by GrantSP** [Thalassicus/cep-bnw#87]
Although the tech has not been reached yet, and no sites are visible on the map, when I try to found a city, a warning message about an antiquity site is given.

The log shows this message at the time of the event:
CES_Events.lua:85: attempt to call global 'Plot_GetYield' (a nil value)

I can only assume the Plot is not defined properly in the CES_Events.lua.
The tile in question is a hill and the function at this line is checking if it is an empty mountain.

Actually looking all through the log shows this error message occurring regularly.

**Comment by stackpoint** [comment]
Is this still an active issue? Is this error still appearing?

**Comment by GrantSP** [comment]
The specifics of how this happen are very rare. I would imagine that not many users will see this.
I have only had it happen the once.

Probably best to leave this active for the time being.

**Comment by stackpoint** [comment]
I just double checked the Plot_GetYield() function and it seems like it was a function defined in YieldLibrary.lua. Thal seems to have included it here: https://github.com/Thalassicus/cep-bnw/commit/764b8ccd049fabe4daa193737dc9849748e46a38#diff-234fc8fc96360f84d5fc4086f8051d53
