### ISSUE TITLE
Great merchant of Venice of Danemark.

### ISSUE THREAD

**Issue by AnastaseAlex** [Thalassicus/cep-bnw#88]
I saw that in my latest game. I guess it is from a city-state gift perhaps? Should that be happening?

**Comment by GrantSP** [comment]
Yes this is a vanilla game experiance. CSs can gift you Great People and they take the gift from a 'pool' of ALL the types available.
It is related to the often weird experience of UUs from not used civs appearing as gifted units in the game.
I just had the Ethiopians come calling with Winged Hussars!
