### ISSUE TITLE
Auto-Annexing Bug

### ISSUE THREAD

**Issue by stackpoint** [Thalassicus/cep-bnw#9]
I finally found an relatively unmodified, older version of TechTree.lua (so I could compare it to a patched TechTree.lua) found here: http://forums.civfanatics.com/showthread.php?p=12492195#post12492195

And it turns out that bc1 had solved the bug way back in June. I can make the update(s) to our TechTree.lua and that should fix our problems with the auto-annexing bug. I just need confirmation on whether or not Thal wants me to update directly to the master branch or develop branch or stackpointer branch....

**Comment by stackpoint** [comment]
On second look it seems like Thal made those modifications back in version 3.5 in September... Not sure where to look for this bug now.

**Comment by GrantSP** [comment]
Interesting, the post does mention the 'Fall patch' was suppose to fix the
problem, searching in the core files shows the exact same code though, so
who knows?

I don't think Thal has fix that specific code, I can still it in all the
files I have, both from before and now with this new project structure.

On 15 November 2013 11:41, stackpointer notifications@github.com wrote:

> I finally found an relatively unmodified, older version of TechTree.lua so
> I could compare it to the recent TechTree.lua found here:
> http://forums.civfanatics.com/showthread.php?p=12492195#post12492195
> 
> And it turns out that bc1 had solved the bug way back in June. I can make
> the update to our TechTree.lua and that should fix our problems with the
> auto-annexing bug. I just need confirmation on whether or not you want me
> to update directly to the master branch or develop branch or stackpointer
> branch....
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Thalassicus/cep-bnw/issues/9
> .

## 

"There are 10 types of people in the world: those who understand binary,
and those who don't."

**Comment by stackpoint** [comment]
I fell for the same visual trick. That code originally appears twice. The fixed code from bc1 and vanilla BNW is below:

``` lua
function OnCloseButtonClicked ()
    UIManager:DequeuePopup( ContextPtr );
    Events.SerialEventGameMessagePopupProcessed.CallImmediate(ButtonPopupTypes.BUTTONPOPUP_TECH_TREE, 0);
    g_isOpen = false;   
end
Controls.CloseButton:RegisterCallback( Mouse.eLClick, OnCloseButtonClicked );

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

function InputHandler( uiMsg, wParam, lParam )
    if g_isOpen and uiMsg == KeyEvents.KeyDown then
        if wParam == Keys.VK_ESCAPE or wParam == Keys.VK_RETURN then
            OnCloseButtonClicked();
            return true;
        end
    end
end
ContextPtr:SetInputHandler( InputHandler );
```

This code is already implemented in our TechTree.lua file.

**Comment by GrantSP** [comment]
So the bug/fix is for 'InputHandler' not 'OnCloseButtonClicked' ?

On 15 November 2013 12:12, stackpointer notifications@github.com wrote:

> I fell for the same visual trick. That code originally appears twice. The
> fixed code from bc1 and vanilla BNW is below:
> 
> function OnCloseButtonClicked ()
>     UIManager:DequeuePopup( ContextPtr );
>     Events.SerialEventGameMessagePopupProcessed.CallImmediate(ButtonPopupTypes.BUTTONPOPUP_TECH_TREE, 0);
> 
> ##     g_isOpen = false;   endControls.CloseButton:RegisterCallback( Mouse.eLClick, OnCloseButtonClicked );
> 
> function InputHandler( uiMsg, wParam, lParam )
>     if g_isOpen and uiMsg == KeyEvents.KeyDown then
>         if wParam == Keys.VK_ESCAPE or wParam == Keys.VK_RETURN then
>             OnCloseButtonClicked();
>             return true;
>         end
>     endendContextPtr:SetInputHandler( InputHandler );
> 
> This code is already implemented in our TechTree.lua file.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Thalassicus/cep-bnw/issues/9#issuecomment-28539716
> .

## 

"There are 10 types of people in the world: those who understand binary,
and those who don't."

**Comment by stackpoint** [comment]
Yes.

**Comment by GrantSP** [comment]
So that means, this bug is a vanilla one and although at least two
different people have come up with a fix, the problem still exists?
That InputHandler block is found elsewhere, but unfixed, in lots of
different files, maybe one the other occurrences is causing the bug?

From a quick look most of the blocks use OnClose() instead of
OnCloseButtonClicked(). Am I off target here?

On 15 November 2013 12:19, stackpointer notifications@github.com wrote:

> Yes.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Thalassicus/cep-bnw/issues/9#issuecomment-28540067
> .

## 

"There are 10 types of people in the world: those who understand binary,
and those who don't."

**Comment by stackpoint** [comment]
I don't think so. Vanilla uses bc1's fix and i doubt he would've missed the other function calls if they were a problem.

I am going to try following the instructions here: http://forums.civfanatics.com/showthread.php?t=501084 and play a game to see if something else is causing the queue to get stuck.

**Comment by GrantSP** [comment]
I'll do the same and see.

On 15 November 2013 12:35, stackpointer notifications@github.com wrote:

> I don't think so. Vanilla uses bc1's fix and i doubt he would've missed
> the other function calls if they were a problem.
> 
> I am going to try following the instructions here:
> http://forums.civfanatics.com/showthread.php?t=501084 and play a game to
> see if something else is causing the queue to get stuck.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Thalassicus/cep-bnw/issues/9#issuecomment-28540750
> .

## 

"There are 10 types of people in the world: those who understand binary,
and those who don't."

**Comment by stackpoint** [comment]
Make sure to use your escape key when possible. 

Or maybe not. The cause could be anywhere.

**Comment by GrantSP** [comment]
Will do.

On 15 November 2013 12:37, stackpointer notifications@github.com wrote:

> Make sure to use your escape key when possible.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Thalassicus/cep-bnw/issues/9#issuecomment-28540852
> .

## 

"There are 10 types of people in the world: those who understand binary,
and those who don't."

**Comment by stackpoint** [comment]
Okay, so I was able to get a stuck window by doing the following:
1) Need a new technology to research
2) Click the "Choose Research" button
3) Open the tech tree by clicking on the beakers in the top bar
4) Choose your technology
5) Exit out of the tech tree
6) Exit out of the tech sidebar without using escape
7) Get stuck

Not sure if this is what people actually did to get to this point....

**Comment by GrantSP** [comment]
Hang on, are you able to do that without going through the hassle of
capturing cities? Have I completely missed the point of this exercise?
I just spent a couple of hours in battle just to get the city-capture
opportunities.

Don't tell me all I had to do was try some different clicking and "esc"
pressing.

On 15 November 2013 14:17, stackpointer notifications@github.com wrote:

> Okay, so I was able to get a stuck window by doing the following:
> 1) Need a new technology to research
> 2) Click the "Choose Research" button
> 3) Open the tech tree by clicking on the beakers in the top bar
> 4) Choose your technology
> 5) Exit out of the tech tree
> 6) Get stuck
> 
> Not sure if this is what people actually did to get to this point....
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Thalassicus/cep-bnw/issues/9#issuecomment-28544437
> .

## 

"There are 10 types of people in the world: those who understand binary,
and those who don't."

**Comment by stackpoint** [comment]
Haha, yeah, I just did the same here. I ended up using IGE to conquer a bunch of civs but then I realized that the conquering doesn't really matter since we have the tuner to tell us whether the window gets stuck or not....

**Comment by stackpoint** [comment]
The steps shown above is a vanilla bug.

It's also possible that this was related: http://forums.civfanatics.com/showthread.php?t=509337

Since natural wonders have a popup too that could've caused the popups to hang before I fixed the issue here: https://github.com/Thalassicus/cat/issues/5#issuecomment-28148230

**Comment by stackpoint** [comment]
Okay, I was able to confirm in a test game that it was this natural wonder bug that was also the auto-annexing bug. With my fix in place we shouldn't encounter it unless someone encounters the vanilla bug using the steps above.
