### ISSUE TITLE
Itaipu Dam

### ISSUE THREAD

**Issue by AnastaseAlex** [Thalassicus/cep-bnw#90]
Does not give order civs +1 free social policy.

**Comment by GrantSP** [comment]
I didn't think it is supposed to.
+1 Engineer, 15% Production in all cities, +1 Hydro Plant

**Comment by AnastaseAlex** [comment]
The description on the tech path indicated otherwise. Which wonder gives +1 social policy for order now? I cannot build the Kremlin any more, it became an autocracy thing...

**Comment by GrantSP** [comment]
My tech tree descriptions don't mention anything about +1 policies! Version 3.11

Statue of Liberty (Freedom), Kremlin (Autocracy) and the Oracle all give +1 Social Policy.
The Sydney Opera House gives +2

**Comment by AnastaseAlex** [comment]
I guess I must not have the lattest version. It is 2 in the morning here, I just finished a game with Siam. I keep winning tourism victories in King without much trouble. Anyhow, I will check it tomorow again but for now I trust you and will close this.

**Comment by AnastaseAlex** [comment]
I probably saw that it requires order and assumed it would give +1free social policy too. I am too tirred right now to check it again.
