### ISSUE TITLE
[3.11.2] Error in CES_Stories.xml

### ISSUE THREAD

**Issue by skodkim** [Thalassicus/cep-bnw#94]
Using 3.11.2 (cache, moduserdata cleared, no other mods, ...)

I get the following error message in database.log (attached):

[1052.211] column Type is not unique
[1052.211] While executing - 'insert into Triggers('Type', 'ImprovementType') values (?, ?);'
[1052.211] In XMLSerializer while inserting row into table insert into Triggers('Type', 'ImprovementType') with  values (COMMERCIAL_FARMING, IMPROVEMENT_FARM, ).
[1052.211] In XMLSerializer while updating table Triggers from file Stories/CES_Stories.xml.
[1052.211] column Type is not unique
[1055.767] 

\Skodkim

![database log](https://f.cloud.github.com/assets/6018459/1814572/d71a52e8-6ef7-11e3-8a62-c9fce8636cde.jpg)

**Comment by ghost** [comment]
I am wondering if 'Type' is a reserved word in the database.

**Comment by ghost** [comment]
'Type' is not a reserved word, so scratch that idea.

**Comment by skodkim** [comment]
Yeah, thats not the case. Just saw that you posted a similar issue on 3.11.3.

Lets hope we get a big round of bug fixing soon. Theres been talk about stories only triggering once for human players. I dont know if this is related but usually an error message like this indicates that a part of the mod isnt working. i've been holding out on playing with 3.11 because of these bugs (+policy and barbarian bugs) so no personal experience though.

\Skodkim

**Comment by GrantSP** [comment]
I don't really think this is much of a problem. It is closely related to the vanilla situation shown at the top of every database.log:
[21062.038] columns StrategicViewType, TileType are not unique
[21062.038] While executing - 'INSERT INTO ArtDefine_StrategicView(StrategicViewType, TileType, Asset) VALUES(?,?,?)'
[21136.528] no such table: ContentPackage.LocalizedText
[21140.974] no such table: ContentPackage.LocalizedText
[21150.178] columns StrategicViewType, TileType are not unique
[21150.178] While executing - 'INSERT INTO ArtDefine_StrategicView(StrategicViewType, TileType, Asset) VALUES(?,?,?)'
[21152.440] no such table: ContentPackage.LocalizedText
[21174.078] 

I think it may be more of a difference between the way the XML is treated by differing engines.

**Comment by skodkim** [comment]
Really? I mean, we're doing so much modding here, numerous inserts and such, and I've never seen a message like this other than the ones from vanilla.

\Skodkim

GrantSP notifications@github.com skrev:

> I don't really think this is much of a problem. It is closely related
> to the vanilla situation shown at the top of every database.log:
> [21062.038] columns StrategicViewType, TileType are not unique
> [21062.038] While executing - 'INSERT INTO
> ArtDefine_StrategicView(StrategicViewType, TileType, Asset)
> VALUES(?,?,?)'
> [21136.528] no such table: ContentPackage.LocalizedText
> [21140.974] no such table: ContentPackage.LocalizedText
> [21150.178] columns StrategicViewType, TileType are not unique
> [21150.178] While executing - 'INSERT INTO
> ArtDefine_StrategicView(StrategicViewType, TileType, Asset)
> VALUES(?,?,?)'
> [21152.440] no such table: ContentPackage.LocalizedText
> [21174.078] 
> 
> I think it may be more of a difference between the way the XML is
> treated by differing engines.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Thalassicus/cep-bnw/issues/94#issuecomment-31303702

## 

Sendt fra min Android telefon med K-9 Mail. Undskyld hvis jeg er lidt kortfattet.

**Comment by GrantSP** [comment]
Well going by my recent track record NO, it is probably THE cause of all the problems.
But think about it, do we really have major problems from the "Stories"? Surely our focus should be on why the barbarians aren't showing up or fixing some long-standing policy bugs?
As far as I can see, this doesn't actually "bug out" the game, just logs a message about non-unique keys.

**Comment by skodkim** [comment]
I haven't really played 3.11 yet but I was under the impression that there was a bug where stories only occurred once for human players. Noone has really been able to confirm whether it's a general problem or not though.

IF it is then there is a serious problem with stories and therefore I've been pushing this. If not then...

\Skodkim

GrantSP notifications@github.com skrev:

> Well going by my recent track record NO, it is probably THE cause of
> all the problems.
> But think about it, do we really have major problems from the
> "Stories"? Surely our focus should be on why the barbarians aren't
> showing up or fixing some long-standing policy bugs?
> As far as I can see, this doesn't actually "bug out" the game, just
> logs a message about non-unique keys.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Thalassicus/cep-bnw/issues/94#issuecomment-31303920

## 

Sendt fra min Android telefon med K-9 Mail. Undskyld hvis jeg er lidt kortfattet.

**Comment by GrantSP** [comment]
Yes that WAS true. But I was trying to narrow the barbarian bug down last night and had stories occurring more than once with 3.11.3 and I see Thal has released a 3.11.4 so perhaps that may 'fix' that.

At any rate, are the "Stories" truly an issue at the moment? I can live without my scout upgrading or a plot of land being improved but not having barbarians is a game-breaker.

**Comment by Thalassicus** [comment]
There were duplicate entries for CES_Stories.xml in the project file, which attempted to load that file into the database twice. I fixed this. It should not have affected anything else, since the game simply stops processing a file when it encounters a problem like this.
