### ISSUE TITLE
Indus Sanitation abilities description missing symbol

### ISSUE THREAD

**Issue by TimurKelman** [Thalassicus/cep-bnw#95]
2nd line of Indus Sanitation description says:
": 1 for Lake Tiles"
there is no symbol before colon, so no idea what 1 exactly would I get from it. (btw, I was even unable to google it.)

**Comment by skodkim** [comment]
Just tested and in 3.12.2 it says "Food:": 1 for Lake Tiles"

Issue should be closed.

\Skodkim

**Comment by stackpoint** [comment]
Thanks for the clarification.
