### ISSUE TITLE
Promotions

### ISSUE THREAD

**Issue by GrantSP** [Thalassicus/cep-bnw#98]
Just tried a new game with the latest Flag Promotions enabled.

It's turn 34 and just met an Aztec warrior with the following promos:
Drill 1
Siege
Blitz
+33% in Forest/Jungle
+2 Visibility
Heal 25 from defeated units
Woodsman

Now obviously the last two are from trait bonuses but since there were no barbarians between him and my capital just where is this unit getting this experience?
How many promos do the AI get on Emperor?

**Comment by Thalassicus** [comment]
You can see all AI modifications on the Handicaps table:

https://docs.google.com/spreadsheet/ccc?key=0Ap8Ehya83q19dG5nbDBhM0FmSzhPM1piQTE0MklSWnc&usp=drive_web#gid=2

AIs in the unmodded game are good at economics, and bad at warfare. I changed the bonuses so AIs should be equally capable at both economics and warfare. Firaxis did not write effective code for AIs to seek out barbarians, either, so they start with extra experience to compensate.

**Comment by GrantSP** [comment]
Thanks. So on emperor the AI gets 40XP & 16XP per era. Does that mean they start the game at 56? Just 1 small fight from 3 promotions?

**Comment by Thalassicus** [comment]
Human and AI units should have approximately equal experience in wars. Emperor-level humans can usually start wars with 3 promotions per unit from clearing barbarians. Militaristic AIs therefore have about 3 promotions per unit on Emperor. (Peaceful AIs have less experience.)

The exact amount depends on whether that uses computer numbering for eras (0, 1, 2) or human numbering (1, 2, 3). Computers usually start counting at 0. I don't remember what this part of the game uses. It's easy to check by searching the project for that tag in lua files.
