### ISSUE TITLE
Barbarian Axman

### ISSUE THREAD

**Issue by GrantSP** [Thalassicus/cep-bnw#99]
It looks like the Axman has been beefed up incorrectly as it was several versions ago.

It now has a Ranged strength or 20 and a Combat of 15 compared to 9 & 9 in vanilla.

Probably adjusted along with the other Chariot Archer units.

**Comment by Thalassicus** [comment]
The best way to fix this is to create a "UNITCLASS_AXMAN" for the unit so it's no longer affected by changes to chariots. I don't know why Firaxis made the unit a "chariot class" when it shares little in common with chariots (different strength, speed, range, promotions, techs, and resource requirement).

**Comment by GrantSP** [comment]
Wouldn't be just as easy to change it to "UNITCLASS_ARCHER"?

**Comment by Thalassicus** [comment]
No, then it would be affected by the archer changes. It's an independent barbarian unit that needs its own unit class. The Galley barbarian ship has an independent unit class we can look at to see how to do this for Axmen.

**Comment by Thalassicus** [comment]
I added a new file Cat_Fixes.xml to solve this issue in v3.12.1. Please close this issue once someone can confirm it's fixed.

**Comment by GrantSP** [comment]
Very nice fix. Should enable future changes to avoid this unit very effectively.
